/* agent.c generated by valac, the Vala compiler
 * generated from agent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <globalmenu-settings.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/Xregion.h>
#include <gdk/gdkx.h>
#include <gobject/gvaluecollector.h>


#define TYPE_MENU_BAR_AGENT (menu_bar_agent_get_type ())
#define MENU_BAR_AGENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MENU_BAR_AGENT, MenuBarAgent))
#define MENU_BAR_AGENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MENU_BAR_AGENT, MenuBarAgentClass))
#define IS_MENU_BAR_AGENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MENU_BAR_AGENT))
#define IS_MENU_BAR_AGENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MENU_BAR_AGENT))
#define MENU_BAR_AGENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MENU_BAR_AGENT, MenuBarAgentClass))

typedef struct _MenuBarAgent MenuBarAgent;
typedef struct _MenuBarAgentClass MenuBarAgentClass;
typedef struct _MenuBarAgentPrivate MenuBarAgentPrivate;

#define MENU_BAR_AGENT_TYPE_QUIRK_TYPE (menu_bar_agent_quirk_type_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_MENU_BAR_AGENT_FACTORY (menu_bar_agent_factory_get_type ())
#define MENU_BAR_AGENT_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MENU_BAR_AGENT_FACTORY, MenuBarAgentFactory))
#define MENU_BAR_AGENT_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MENU_BAR_AGENT_FACTORY, MenuBarAgentFactoryClass))
#define IS_MENU_BAR_AGENT_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MENU_BAR_AGENT_FACTORY))
#define IS_MENU_BAR_AGENT_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MENU_BAR_AGENT_FACTORY))
#define MENU_BAR_AGENT_FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MENU_BAR_AGENT_FACTORY, MenuBarAgentFactoryClass))

typedef struct _MenuBarAgentFactory MenuBarAgentFactory;
typedef struct _MenuBarAgentFactoryClass MenuBarAgentFactoryClass;
#define _menu_bar_agent_factory_unref0(var) ((var == NULL) ? NULL : (var = (menu_bar_agent_factory_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_SERIALIZER (serializer_get_type ())
#define SERIALIZER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERIALIZER, Serializer))
#define SERIALIZER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SERIALIZER, SerializerClass))
#define IS_SERIALIZER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERIALIZER))
#define IS_SERIALIZER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SERIALIZER))
#define SERIALIZER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SERIALIZER, SerializerClass))

typedef struct _Serializer Serializer;
typedef struct _SerializerClass SerializerClass;
typedef struct _SerializerPrivate SerializerPrivate;
#define _serializer_unref0(var) ((var == NULL) ? NULL : (var = (serializer_unref (var), NULL)))
typedef struct _ParamSpecMenuBarAgent ParamSpecMenuBarAgent;

typedef enum  {
	MENU_BAR_AGENT_QUIRK_TYPE_NONE = 0,
	MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET = 1,
	MENU_BAR_AGENT_QUIRK_TYPE_MATECOMPONENT_PLUG = 2,
	MENU_BAR_AGENT_QUIRK_TYPE_WX_GTK = 4
} MenuBarAgentQuirkType;

struct _MenuBarAgent {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MenuBarAgentPrivate * priv;
	MenuBarAgentQuirkType quirks;
};

struct _MenuBarAgentClass {
	GTypeClass parent_class;
	void (*finalize) (MenuBarAgent *self);
	void (*quirks_changed) (MenuBarAgent* self, MenuBarAgentQuirkType old_quirks);
};

struct _MenuBarAgentPrivate {
	GtkMenuBar* _menubar;
	MatenuSettings* _settings;
	GdkWindow* _event_window;
	GtkWidget* _toplevel;
	gboolean dirty;
};

struct _Serializer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SerializerPrivate * priv;
	gboolean disable_pixbuf;
	gboolean pretty_print;
};

struct _SerializerClass {
	GTypeClass parent_class;
	void (*finalize) (Serializer *self);
};

struct _ParamSpecMenuBarAgent {
	GParamSpec parent_instance;
};


static GdkAtom menu_bar_agent_atom_select;
static GdkAtom menu_bar_agent_atom_select;
static GdkAtom menu_bar_agent_atom_deselect;
static GdkAtom menu_bar_agent_atom_deselect;
static GdkAtom menu_bar_agent_atom_activate;
static GdkAtom menu_bar_agent_atom_activate;
static gpointer menu_bar_agent_parent_class = NULL;

gpointer menu_bar_agent_ref (gpointer instance);
void menu_bar_agent_unref (gpointer instance);
GParamSpec* param_spec_menu_bar_agent (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_menu_bar_agent (GValue* value, gpointer v_object);
void value_take_menu_bar_agent (GValue* value, gpointer v_object);
gpointer value_get_menu_bar_agent (const GValue* value);
GType menu_bar_agent_get_type (void) G_GNUC_CONST;
GType menu_bar_agent_quirk_type_get_type (void) G_GNUC_CONST;
#define MENU_BAR_AGENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MENU_BAR_AGENT, MenuBarAgentPrivate))
enum  {
	MENU_BAR_AGENT_DUMMY_PROPERTY
};
gboolean menu_bar_agent_quirk_type_has (MenuBarAgentQuirkType self, MenuBarAgentQuirkType value);
static void menu_bar_agent_set_menubar (MenuBarAgent* self, GtkMenuBar* value);
static void menu_bar_agent_menubar_disposed (MenuBarAgent* self, GObject* object);
static void menu_bar_agent_set_toplevel (MenuBarAgent* self, GtkWidget* value);
static void menu_bar_agent_toplevel_disposed (MenuBarAgent* self, GObject* object);
static void menu_bar_agent_set_event_window (MenuBarAgent* self, GdkWindow* value);
static void menu_bar_agent_event_window_disposed (MenuBarAgent* self, GObject* object);
gpointer menu_bar_agent_factory_ref (gpointer instance);
void menu_bar_agent_factory_unref (gpointer instance);
GParamSpec* param_spec_menu_bar_agent_factory (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_menu_bar_agent_factory (GValue* value, gpointer v_object);
void value_take_menu_bar_agent_factory (GValue* value, gpointer v_object);
gpointer value_get_menu_bar_agent_factory (const GValue* value);
GType menu_bar_agent_factory_get_type (void) G_GNUC_CONST;
MenuBarAgentFactory* menu_bar_agent_factory_get (void);
void menu_bar_agent_factory_associate (MenuBarAgentFactory* self, GtkMenuBar* menubar, MenuBarAgent* agent);
static void menu_bar_agent_set_settings (MenuBarAgent* self, MatenuSettings* value);
static void menu_bar_agent_show_local_menu_changed (MenuBarAgent* self);
static void _menu_bar_agent_show_local_menu_changed_g_object_notify (MatenuSettings* _sender, GParamSpec* pspec, gpointer self);
MatenuSettings* menu_bar_agent_get_settings (MenuBarAgent* self);
static void menu_bar_agent_show_menu_icons_changed (MenuBarAgent* self);
static void _menu_bar_agent_show_menu_icons_changed_g_object_notify (MatenuSettings* _sender, GParamSpec* pspec, gpointer self);
static void _menu_bar_agent_menubar_disposed_gweak_notify (gpointer self, GObject* object);
static void _lambda0_ (MenuBarAgent* self);
static void __lambda0__gtk_widget_hierarchy_changed (GtkMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self);
static void menu_bar_agent_sync_quirks (MenuBarAgent* self);
static void _menu_bar_agent_sync_quirks_gtk_widget_hierarchy_changed (GtkMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self);
static void menu_bar_agent_sync_toplevel (MenuBarAgent* self);
static void _menu_bar_agent_sync_toplevel_gtk_widget_hierarchy_changed (GtkMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self);
void menu_bar_set_children_menubar (GtkMenuBar* menubar);
MenuBarAgent* menu_bar_agent_new (GtkMenuBar* menubar);
MenuBarAgent* menu_bar_agent_construct (GType object_type, GtkMenuBar* menubar);
GtkMenuBar* menu_bar_agent_get_menubar (MenuBarAgent* self);
static void menu_bar_agent_release_menubar (MenuBarAgent* self);
static GtkWidget* menu_bar_agent_get_toplevel (MenuBarAgent* self);
static void menu_bar_agent_sync_event_window (MenuBarAgent* self);
static void _menu_bar_agent_sync_event_window_gtk_widget_realize (GtkWidget* _sender, gpointer self);
static void _menu_bar_agent_sync_event_window_gtk_widget_unrealize (GtkWidget* _sender, gpointer self);
static void _menu_bar_agent_toplevel_disposed_gweak_notify (gpointer self, GObject* object);
static void menu_bar_agent_release_toplevel (MenuBarAgent* self);
static GdkWindow* menu_bar_agent_get_event_window (MenuBarAgent* self);
static GdkFilterReturn menu_bar_agent_event_filter (GdkXEvent* xevent, GdkEvent* event, MenuBarAgent* self);
static GdkFilterReturn _menu_bar_agent_event_filter_gdk_filter_func (GdkXEvent* xevent, GdkEvent* event, gpointer self);
static void _menu_bar_agent_event_window_disposed_gweak_notify (gpointer self, GObject* object);
static void menu_bar_agent_release_event_window (MenuBarAgent* self);
static gboolean menu_bar_agent_send_globalmenu_message (MenuBarAgent* self);
static gboolean _menu_bar_agent_send_globalmenu_message_gsource_func (gpointer self);
void menu_bar_agent_queue_changed (MenuBarAgent* self);
static gboolean menu_bar_agent_has_parent_type_name (MenuBarAgent* self, const char* typename_pattern);
void menu_bar_map (GtkWidget* widget);
static GdkFilterReturn menu_bar_agent_real_event_filter (XEvent* xevent, GdkEvent* event, MenuBarAgent* self);
static gboolean menu_bar_agent_atom_equal (MenuBarAgent* self, GdkAtom a1, GdkAtom a2);
char* menu_bar_agent_get_by_atom (MenuBarAgent* self, GdkAtom atom);
GtkMenuItem* locator_locate (GtkMenuBar* menubar, const char* path);
static void menu_bar_agent_select_item (MenuBarAgent* self, GtkMenuItem* item);
static void menu_bar_agent_deselect_item (MenuBarAgent* self, GtkMenuItem* item);
static void menu_bar_agent_activate_item (MenuBarAgent* self, GtkMenuItem* item);
Serializer* serializer_new (void);
Serializer* serializer_construct (GType object_type);
gpointer serializer_ref (gpointer instance);
void serializer_unref (gpointer instance);
GParamSpec* param_spec_serializer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_serializer (GValue* value, gpointer v_object);
void value_take_serializer (GValue* value, gpointer v_object);
gpointer value_get_serializer (const GValue* value);
GType serializer_get_type (void) G_GNUC_CONST;
void menu_bar_agent_set_by_atom (MenuBarAgent* self, GdkAtom atom, const char* value);
char* serializer_to_string (Serializer* self, GtkMenuBar* menubar);
static void menu_bar_agent_quirks_changed (MenuBarAgent* self, MenuBarAgentQuirkType old_quirks);
static void menu_bar_agent_real_quirks_changed (MenuBarAgent* self, MenuBarAgentQuirkType old_quirks);
static void menu_bar_agent_finalize (MenuBarAgent* obj);



gboolean menu_bar_agent_quirk_type_has (MenuBarAgentQuirkType self, MenuBarAgentQuirkType value) {
	gboolean result = FALSE;
	result = (value & self) != 0;
	return result;
}


GType menu_bar_agent_quirk_type_get_type (void) {
	static volatile gsize menu_bar_agent_quirk_type_type_id__volatile = 0;
	if (g_once_init_enter (&menu_bar_agent_quirk_type_type_id__volatile)) {
		static const GEnumValue values[] = {{MENU_BAR_AGENT_QUIRK_TYPE_NONE, "MENU_BAR_AGENT_QUIRK_TYPE_NONE", "none"}, {MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET, "MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET", "regular-widget"}, {MENU_BAR_AGENT_QUIRK_TYPE_MATECOMPONENT_PLUG, "MENU_BAR_AGENT_QUIRK_TYPE_MATECOMPONENT_PLUG", "matecomponent-plug"}, {MENU_BAR_AGENT_QUIRK_TYPE_WX_GTK, "MENU_BAR_AGENT_QUIRK_TYPE_WX_GTK", "wx-gtk"}, {0, NULL, NULL}};
		GType menu_bar_agent_quirk_type_type_id;
		menu_bar_agent_quirk_type_type_id = g_enum_register_static ("MenuBarAgentQuirkType", values);
		g_once_init_leave (&menu_bar_agent_quirk_type_type_id__volatile, menu_bar_agent_quirk_type_type_id);
	}
	return menu_bar_agent_quirk_type_type_id__volatile;
}


static void menu_bar_agent_menubar_disposed (MenuBarAgent* self, GObject* object) {
	g_return_if_fail (self != NULL);
	menu_bar_agent_set_menubar (self, NULL);
}


static void menu_bar_agent_toplevel_disposed (MenuBarAgent* self, GObject* object) {
	g_return_if_fail (self != NULL);
	menu_bar_agent_set_toplevel (self, NULL);
}


static void menu_bar_agent_event_window_disposed (MenuBarAgent* self, GObject* object) {
	g_return_if_fail (self != NULL);
	menu_bar_agent_set_event_window (self, NULL);
}


static void _menu_bar_agent_show_local_menu_changed_g_object_notify (MatenuSettings* _sender, GParamSpec* pspec, gpointer self) {
	menu_bar_agent_show_local_menu_changed (self);
}


static void _menu_bar_agent_show_menu_icons_changed_g_object_notify (MatenuSettings* _sender, GParamSpec* pspec, gpointer self) {
	menu_bar_agent_show_menu_icons_changed (self);
}


static void _menu_bar_agent_menubar_disposed_gweak_notify (gpointer self, GObject* object) {
	menu_bar_agent_menubar_disposed (self, object);
}


static void _lambda0_ (MenuBarAgent* self) {
	g_debug ("agent.vala:82: hierarchy changed");
}


static void __lambda0__gtk_widget_hierarchy_changed (GtkMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_lambda0_ (self);
}


static void _menu_bar_agent_sync_quirks_gtk_widget_hierarchy_changed (GtkMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self) {
	menu_bar_agent_sync_quirks (self);
}


static void _menu_bar_agent_sync_toplevel_gtk_widget_hierarchy_changed (GtkMenuBar* _sender, GtkWidget* previous_toplevel, gpointer self) {
	menu_bar_agent_sync_toplevel (self);
}


MenuBarAgent* menu_bar_agent_construct (GType object_type, GtkMenuBar* menubar) {
	MenuBarAgent* self;
	MenuBarAgentFactory* _tmp0_;
	MatenuLocalSettings* _tmp1_;
	g_return_val_if_fail (menubar != NULL, NULL);
	self = (MenuBarAgent*) g_type_create_instance (object_type);
	menu_bar_agent_set_menubar (self, menubar);
	menu_bar_agent_factory_associate (_tmp0_ = menu_bar_agent_factory_get (), menubar, self);
	_menu_bar_agent_factory_unref0 (_tmp0_);
	menu_bar_agent_set_settings (self, (MatenuSettings*) (_tmp1_ = matenu_local_settings_new (NULL)));
	_g_object_unref0 (_tmp1_);
	g_signal_connect ((GObject*) self->priv->_settings, "notify::show-local-menu", (GCallback) _menu_bar_agent_show_local_menu_changed_g_object_notify, self);
	g_signal_connect ((GObject*) self->priv->_settings, "notify::show-menu-icons", (GCallback) _menu_bar_agent_show_menu_icons_changed_g_object_notify, self);
	g_object_weak_ref ((GObject*) menubar, _menu_bar_agent_menubar_disposed_gweak_notify, self);
	g_signal_connect ((GtkWidget*) menubar, "hierarchy-changed", (GCallback) __lambda0__gtk_widget_hierarchy_changed, self);
	g_signal_connect ((GtkWidget*) menubar, "hierarchy-changed", (GCallback) _menu_bar_agent_sync_quirks_gtk_widget_hierarchy_changed, self);
	g_signal_connect ((GtkWidget*) menubar, "hierarchy-changed", (GCallback) _menu_bar_agent_sync_toplevel_gtk_widget_hierarchy_changed, self);
	menu_bar_agent_sync_quirks (self);
	menu_bar_agent_sync_toplevel (self);
	menu_bar_set_children_menubar (menubar);
	menu_bar_agent_show_local_menu_changed (self);
	g_debug ("agent.vala:92: agent created");
	return self;
}


MenuBarAgent* menu_bar_agent_new (GtkMenuBar* menubar) {
	return menu_bar_agent_construct (TYPE_MENU_BAR_AGENT, menubar);
}


static void menu_bar_agent_release_menubar (MenuBarAgent* self) {
	guint _tmp0_;
	guint _tmp1_;
	g_return_if_fail (self != NULL);
	if (menu_bar_agent_get_menubar (self) == NULL) {
		return;
	}
	g_signal_parse_name ("hierarchy-changed", GTK_TYPE_WIDGET, &_tmp0_, NULL, FALSE);
	g_signal_handlers_disconnect_matched ((GtkWidget*) menu_bar_agent_get_menubar (self), G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp0_, 0, NULL, (GCallback) _menu_bar_agent_sync_toplevel_gtk_widget_hierarchy_changed, self);
	g_signal_parse_name ("hierarchy-changed", GTK_TYPE_WIDGET, &_tmp1_, NULL, FALSE);
	g_signal_handlers_disconnect_matched ((GtkWidget*) menu_bar_agent_get_menubar (self), G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _menu_bar_agent_sync_quirks_gtk_widget_hierarchy_changed, self);
	g_object_weak_unref ((GObject*) menu_bar_agent_get_menubar (self), _menu_bar_agent_menubar_disposed_gweak_notify, self);
}


static void _menu_bar_agent_sync_event_window_gtk_widget_realize (GtkWidget* _sender, gpointer self) {
	menu_bar_agent_sync_event_window (self);
}


static void _menu_bar_agent_sync_event_window_gtk_widget_unrealize (GtkWidget* _sender, gpointer self) {
	menu_bar_agent_sync_event_window (self);
}


static void _menu_bar_agent_toplevel_disposed_gweak_notify (gpointer self, GObject* object) {
	menu_bar_agent_toplevel_disposed (self, object);
}


static void menu_bar_agent_release_toplevel (MenuBarAgent* self) {
	guint _tmp0_;
	guint _tmp1_;
	g_return_if_fail (self != NULL);
	if (self->priv->_toplevel == NULL) {
		return;
	}
	g_signal_parse_name ("realize", GTK_TYPE_WIDGET, &_tmp0_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (self->priv->_toplevel, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp0_, 0, NULL, (GCallback) _menu_bar_agent_sync_event_window_gtk_widget_realize, self);
	g_signal_parse_name ("unrealize", GTK_TYPE_WIDGET, &_tmp1_, NULL, FALSE);
	g_signal_handlers_disconnect_matched (self->priv->_toplevel, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _menu_bar_agent_sync_event_window_gtk_widget_unrealize, self);
	g_object_weak_unref ((GObject*) self->priv->_toplevel, _menu_bar_agent_toplevel_disposed_gweak_notify, self);
}


static GdkFilterReturn _menu_bar_agent_event_filter_gdk_filter_func (GdkXEvent* xevent, GdkEvent* event, gpointer self) {
	GdkFilterReturn result;
	result = menu_bar_agent_event_filter (xevent, event, self);
	return result;
}


static void _menu_bar_agent_event_window_disposed_gweak_notify (gpointer self, GObject* object) {
	menu_bar_agent_event_window_disposed (self, object);
}


static void menu_bar_agent_release_event_window (MenuBarAgent* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->_event_window == NULL) {
		return;
	}
	gdk_window_remove_filter (self->priv->_event_window, _menu_bar_agent_event_filter_gdk_filter_func, self);
	g_object_weak_unref ((GObject*) self->priv->_event_window, _menu_bar_agent_event_window_disposed_gweak_notify, self);
	matenu_settings_attach_to_window (self->priv->_settings, NULL);
}


static gboolean _menu_bar_agent_send_globalmenu_message_gsource_func (gpointer self) {
	gboolean result;
	result = menu_bar_agent_send_globalmenu_message (self);
	return result;
}


void menu_bar_agent_queue_changed (MenuBarAgent* self) {
	g_return_if_fail (self != NULL);
	if (menu_bar_agent_quirk_type_has (self->quirks, MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET)) {
		return;
	}
	if (self->priv->dirty == FALSE) {
		self->priv->dirty = TRUE;
		gdk_threads_add_timeout_full (G_PRIORITY_DEFAULT, (guint) matenu_settings_get_changed_notify_timeout (self->priv->_settings), _menu_bar_agent_send_globalmenu_message_gsource_func, menu_bar_agent_ref (self), menu_bar_agent_unref);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void menu_bar_agent_sync_quirks (MenuBarAgent* self) {
	GtkWidget* toplevel;
	MenuBarAgentQuirkType old_quirks;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 (gtk_widget_get_toplevel ((GtkWidget*) menu_bar_agent_get_menubar (self)));
	old_quirks = self->quirks;
	self->quirks = MENU_BAR_AGENT_QUIRK_TYPE_NONE;
	g_debug ("agent.vala:137: toplevel is a %s", g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) toplevel)));
	if (menu_bar_agent_has_parent_type_name (self, "PanelMenuBar")) {
		self->quirks = MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET;
	}
	if (menu_bar_agent_has_parent_type_name (self, "Matenu")) {
		self->quirks = MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET;
	}
	if (menu_bar_agent_has_parent_type_name (self, "MatePanelApplet")) {
		self->quirks = MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET;
	}
	if (menu_bar_agent_has_parent_type_name (self, "GtkNotebook")) {
		self->quirks = MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET;
	}
	if (menu_bar_agent_has_parent_type_name (self, "GtkPizza")) {
		self->quirks = MENU_BAR_AGENT_QUIRK_TYPE_WX_GTK;
	}
	if (menu_bar_agent_has_parent_type_name (self, "MateComponentDockBand")) {
		self->quirks = MENU_BAR_AGENT_QUIRK_TYPE_MATECOMPONENT_PLUG;
	}
	g_debug ("agent.vala:163: quirks = %d", (gint) self->quirks);
	g_signal_emit_by_name (self, "quirks-changed", old_quirks);
	_g_object_unref0 (toplevel);
}


static void menu_bar_agent_sync_toplevel (MenuBarAgent* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	menu_bar_agent_release_toplevel (self);
	if (menu_bar_agent_get_menubar (self) == NULL) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = menu_bar_agent_quirk_type_has (self->quirks, MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET);
	}
	if (_tmp0_) {
		menu_bar_agent_set_toplevel (self, NULL);
		menu_bar_agent_sync_event_window (self);
		return;
	}
	menu_bar_agent_set_toplevel (self, gtk_widget_get_toplevel ((GtkWidget*) menu_bar_agent_get_menubar (self)));
	if (self->priv->_toplevel != NULL) {
		_tmp1_ = !GTK_WIDGET_TOPLEVEL (self->priv->_toplevel);
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		menu_bar_agent_set_toplevel (self, NULL);
		menu_bar_agent_sync_event_window (self);
		return;
	}
	g_object_weak_ref ((GObject*) self->priv->_toplevel, _menu_bar_agent_toplevel_disposed_gweak_notify, self);
	g_signal_connect (self->priv->_toplevel, "realize", (GCallback) _menu_bar_agent_sync_event_window_gtk_widget_realize, self);
	g_signal_connect (self->priv->_toplevel, "unrealize", (GCallback) _menu_bar_agent_sync_event_window_gtk_widget_unrealize, self);
	menu_bar_agent_sync_event_window (self);
}


static void menu_bar_agent_sync_event_window (MenuBarAgent* self) {
	g_return_if_fail (self != NULL);
	menu_bar_agent_release_event_window (self);
	if (self->priv->_toplevel == NULL) {
		menu_bar_agent_set_event_window (self, NULL);
		return;
	}
	menu_bar_agent_set_event_window (self, self->priv->_toplevel->window);
	matenu_settings_attach_to_window (self->priv->_settings, self->priv->_event_window);
	if (self->priv->_event_window != NULL) {
		gdk_window_add_filter (self->priv->_event_window, _menu_bar_agent_event_filter_gdk_filter_func, self);
		g_object_weak_ref ((GObject*) self->priv->_event_window, _menu_bar_agent_event_window_disposed_gweak_notify, self);
		menu_bar_agent_send_globalmenu_message (self);
	}
}


static gboolean menu_bar_agent_has_parent_type_name (MenuBarAgent* self, const char* typename_pattern) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (typename_pattern != NULL, FALSE);
	if (menu_bar_agent_get_menubar (self) == NULL) {
		result = FALSE;
		return result;
	}
	{
		GtkWidget* parent;
		parent = _g_object_ref0 ((GtkWidget*) menu_bar_agent_get_menubar (self));
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				if (!_tmp0_) {
					GtkWidget* _tmp1_;
					parent = (_tmp1_ = _g_object_ref0 ((GtkWidget*) gtk_widget_get_parent (parent)), _g_object_unref0 (parent), _tmp1_);
				}
				_tmp0_ = FALSE;
				if (!(parent != NULL)) {
					break;
				}
				if (strstr (g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) parent)), typename_pattern) != NULL) {
					result = TRUE;
					_g_object_unref0 (parent);
					return result;
				}
			}
		}
		_g_object_unref0 (parent);
	}
	result = FALSE;
	return result;
}


static void menu_bar_agent_show_menu_icons_changed (MenuBarAgent* self) {
	g_return_if_fail (self != NULL);
	g_debug ("agent.vala:218: menu icons changed!");
	menu_bar_agent_queue_changed (self);
}


static void menu_bar_agent_show_local_menu_changed (MenuBarAgent* self) {
	g_return_if_fail (self != NULL);
	gtk_widget_queue_resize ((GtkWidget*) menu_bar_agent_get_menubar (self));
	if (menu_bar_agent_quirk_type_has (self->quirks, MENU_BAR_AGENT_QUIRK_TYPE_WX_GTK)) {
		g_signal_emit_by_name ((GtkWidget*) menu_bar_agent_get_menubar (self), "style-set", gtk_widget_get_style ((GtkWidget*) menu_bar_agent_get_menubar (self)));
	}
	if (GTK_WIDGET_MAPPED ((GtkWidget*) menu_bar_agent_get_menubar (self))) {
		menu_bar_map ((GtkWidget*) menu_bar_agent_get_menubar (self));
	}
	if (menu_bar_agent_quirk_type_has (self->quirks, MENU_BAR_AGENT_QUIRK_TYPE_MATECOMPONENT_PLUG)) {
		{
			GtkWidget* parent;
			parent = _g_object_ref0 ((GtkWidget*) menu_bar_agent_get_menubar (self));
			{
				gboolean _tmp0_;
				_tmp0_ = TRUE;
				while (TRUE) {
					gboolean _tmp2_ = FALSE;
					if (!_tmp0_) {
						GtkWidget* _tmp1_;
						parent = (_tmp1_ = _g_object_ref0 ((GtkWidget*) gtk_widget_get_parent (parent)), _g_object_unref0 (parent), _tmp1_);
					}
					_tmp0_ = FALSE;
					if (!(parent != NULL)) {
						break;
					}
					if (strstr (g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) parent)), "MateComponentDockBand") == NULL) {
						continue;
					}
					if (!menu_bar_agent_quirk_type_has (self->quirks, MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET)) {
						_tmp2_ = !matenu_settings_get_show_local_menu (self->priv->_settings);
					} else {
						_tmp2_ = FALSE;
					}
					if (_tmp2_) {
						if (GTK_WIDGET_REALIZED (parent)) {
							gdk_window_hide (parent->window);
						}
					} else {
						if (GTK_WIDGET_REALIZED (parent)) {
							gdk_window_show (parent->window);
						}
					}
					break;
				}
			}
			_g_object_unref0 (parent);
		}
	}
}


static GdkFilterReturn menu_bar_agent_event_filter (GdkXEvent* xevent, GdkEvent* event, MenuBarAgent* self) {
	GdkFilterReturn result = 0;
	void* pointer;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (event != NULL, 0);
	pointer = xevent;
	result = menu_bar_agent_real_event_filter ((XEvent*) pointer, event, self);
	return result;
}


static gboolean menu_bar_agent_atom_equal (MenuBarAgent* self, GdkAtom a1, GdkAtom a2) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	if (((gint) a1) == ((gint) a2)) {
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


static GdkFilterReturn menu_bar_agent_real_event_filter (XEvent* xevent, GdkEvent* event, MenuBarAgent* self) {
	GdkFilterReturn result = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (event != NULL, 0);
	switch ((*xevent).type) {
		case PropertyNotify:
		{
			GdkAtom atom;
			gboolean _tmp0_ = FALSE;
			gboolean _tmp1_ = FALSE;
			char* path;
			GtkMenuItem* item;
			atom = gdk_x11_xatom_to_atom ((*xevent).xproperty.atom);
			if (!menu_bar_agent_atom_equal (self, menu_bar_agent_atom_select, atom)) {
				_tmp1_ = !menu_bar_agent_atom_equal (self, menu_bar_agent_atom_deselect, atom);
			} else {
				_tmp1_ = FALSE;
			}
			if (_tmp1_) {
				_tmp0_ = !menu_bar_agent_atom_equal (self, menu_bar_agent_atom_activate, atom);
			} else {
				_tmp0_ = FALSE;
			}
			if (_tmp0_) {
				break;
			}
			path = menu_bar_agent_get_by_atom (self, atom);
			item = locator_locate (menu_bar_agent_get_menubar (self), path);
			if (item == NULL) {
				g_warning ("agent.vala:272: item not found. path=%s", path);
				_g_object_unref0 (item);
				_g_free0 (path);
				break;
			}
			if (menu_bar_agent_atom_equal (self, menu_bar_agent_atom_select, atom)) {
				menu_bar_agent_select_item (self, item);
			}
			if (menu_bar_agent_atom_equal (self, menu_bar_agent_atom_deselect, atom)) {
				menu_bar_agent_deselect_item (self, item);
			}
			if (menu_bar_agent_atom_equal (self, menu_bar_agent_atom_activate, atom)) {
				menu_bar_agent_activate_item (self, item);
			}
			_g_object_unref0 (item);
			_g_free0 (path);
			break;
		}
	}
	result = GDK_FILTER_CONTINUE;
	return result;
}


static void menu_bar_agent_select_item (MenuBarAgent* self, GtkMenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	gtk_item_select ((GtkItem*) item);
	if (gtk_menu_item_get_submenu (item) != NULL) {
		gtk_widget_show ((GtkWidget*) gtk_menu_item_get_submenu (item));
	}
}


static void menu_bar_agent_deselect_item (MenuBarAgent* self, GtkMenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	gtk_item_deselect ((GtkItem*) item);
	if (gtk_menu_item_get_submenu (item) != NULL) {
		gtk_widget_hide ((GtkWidget*) gtk_menu_item_get_submenu (item));
	}
}


static void menu_bar_agent_activate_item (MenuBarAgent* self, GtkMenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	gtk_menu_item_activate (item);
}


static char* bool_to_string (gboolean self) {
	char* result = NULL;
	if (self) {
		result = g_strdup ("true");
		return result;
	} else {
		result = g_strdup ("false");
		return result;
	}
}


static gboolean menu_bar_agent_send_globalmenu_message (MenuBarAgent* self) {
	gboolean result = FALSE;
	Serializer* ser;
	char* _tmp0_;
	char* _tmp1_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_debug ("agent.vala:306: FIXME: STUB send_globalmenu_message()");
	if (menu_bar_agent_get_menubar (self) == NULL) {
		result = FALSE;
		return result;
	}
	self->priv->dirty = FALSE;
	ser = serializer_new ();
	ser->disable_pixbuf = !matenu_settings_get_show_menu_icons (self->priv->_settings);
	g_debug ("agent.vala:312: disable_pixbuf = %s", _tmp0_ = bool_to_string (ser->disable_pixbuf));
	_g_free0 (_tmp0_);
	ser->pretty_print = FALSE;
	menu_bar_agent_set_by_atom (self, gdk_atom_intern ("_NET_GLOBALMENU_MENU_CONTEXT", FALSE), _tmp1_ = serializer_to_string (ser, menu_bar_agent_get_menubar (self)));
	_g_free0 (_tmp1_);
	result = FALSE;
	_serializer_unref0 (ser);
	return result;
}


char* menu_bar_agent_get_by_atom (MenuBarAgent* self, GdkAtom atom) {
	char* result = NULL;
	char* context;
	GdkAtom actual_type;
	GdkAtom type;
	gint actual_format = 0;
	gint actual_length = 0;
	char* _tmp1_;
	char* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	context = NULL;
	type = gdk_atom_intern ("STRING", FALSE);
	gdk_property_get (self->priv->_event_window, atom, type, (gulong) 0, (gulong) G_MAXLONG, FALSE, &actual_type, &actual_format, &actual_length, &_tmp0_);
	context = (_tmp1_ = _tmp0_, _g_free0 (context), _tmp1_);
	result = context;
	return result;
}


void menu_bar_agent_set_by_atom (MenuBarAgent* self, GdkAtom atom, const char* value) {
	g_return_if_fail (self != NULL);
	if (self->priv->_event_window == NULL) {
		return;
	}
	g_debug ("agent.vala:340: set_by_atom: %s", value);
	if (value != NULL) {
		GdkAtom type;
		type = gdk_atom_intern ("STRING", FALSE);
		gdk_property_change (self->priv->_event_window, atom, type, 8, GDK_PROP_MODE_REPLACE, value, ((gint) strlen (value)) + 1);
	} else {
		gdk_property_delete (self->priv->_event_window, atom);
	}
}


MatenuSettings* menu_bar_agent_get_settings (MenuBarAgent* self) {
	MatenuSettings* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_settings;
	return result;
}


static void menu_bar_agent_set_settings (MenuBarAgent* self, MatenuSettings* value) {
	MatenuSettings* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_settings = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_settings), _tmp0_);
}


GtkMenuBar* menu_bar_agent_get_menubar (MenuBarAgent* self) {
	GtkMenuBar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_menubar;
	return result;
}


static void menu_bar_agent_set_menubar (MenuBarAgent* self, GtkMenuBar* value) {
	g_return_if_fail (self != NULL);
	self->priv->_menubar = value;
}


static GdkWindow* menu_bar_agent_get_event_window (MenuBarAgent* self) {
	GdkWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_event_window;
	return result;
}


static void menu_bar_agent_set_event_window (MenuBarAgent* self, GdkWindow* value) {
	g_return_if_fail (self != NULL);
	self->priv->_event_window = value;
}


static GtkWidget* menu_bar_agent_get_toplevel (MenuBarAgent* self) {
	GtkWidget* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_toplevel;
	return result;
}


static void menu_bar_agent_set_toplevel (MenuBarAgent* self, GtkWidget* value) {
	g_return_if_fail (self != NULL);
	self->priv->_toplevel = value;
}


static void menu_bar_agent_real_quirks_changed (MenuBarAgent* self, MenuBarAgentQuirkType old_quirks) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	if (self->quirks == old_quirks) {
		return;
	}
	if (menu_bar_agent_quirk_type_has (old_quirks, MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET)) {
		_tmp0_ = !menu_bar_agent_quirk_type_has (self->quirks, MENU_BAR_AGENT_QUIRK_TYPE_REGULAR_WIDGET);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gtk_widget_queue_resize ((GtkWidget*) menu_bar_agent_get_menubar (self));
		if (GTK_WIDGET_MAPPED ((GtkWidget*) menu_bar_agent_get_menubar (self))) {
			menu_bar_map ((GtkWidget*) menu_bar_agent_get_menubar (self));
		}
		menu_bar_agent_queue_changed (self);
	}
}


static void value_menu_bar_agent_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_menu_bar_agent_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		menu_bar_agent_unref (value->data[0].v_pointer);
	}
}


static void value_menu_bar_agent_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = menu_bar_agent_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_menu_bar_agent_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_menu_bar_agent_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		MenuBarAgent* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = menu_bar_agent_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_menu_bar_agent_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	MenuBarAgent** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags && G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = menu_bar_agent_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_menu_bar_agent (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecMenuBarAgent* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_MENU_BAR_AGENT), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_menu_bar_agent (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MENU_BAR_AGENT), NULL);
	return value->data[0].v_pointer;
}


void value_set_menu_bar_agent (GValue* value, gpointer v_object) {
	MenuBarAgent* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MENU_BAR_AGENT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MENU_BAR_AGENT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		menu_bar_agent_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		menu_bar_agent_unref (old);
	}
}


void value_take_menu_bar_agent (GValue* value, gpointer v_object) {
	MenuBarAgent* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MENU_BAR_AGENT));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MENU_BAR_AGENT));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		menu_bar_agent_unref (old);
	}
}


static void menu_bar_agent_class_init (MenuBarAgentClass * klass) {
	menu_bar_agent_parent_class = g_type_class_peek_parent (klass);
	MENU_BAR_AGENT_CLASS (klass)->finalize = menu_bar_agent_finalize;
	g_type_class_add_private (klass, sizeof (MenuBarAgentPrivate));
	MENU_BAR_AGENT_CLASS (klass)->quirks_changed = menu_bar_agent_real_quirks_changed;
	g_signal_new ("quirks_changed", TYPE_MENU_BAR_AGENT, G_SIGNAL_RUN_LAST, G_STRUCT_OFFSET (MenuBarAgentClass, quirks_changed), NULL, NULL, g_cclosure_marshal_VOID__ENUM, G_TYPE_NONE, 1, MENU_BAR_AGENT_TYPE_QUIRK_TYPE);
	menu_bar_agent_atom_select = gdk_atom_intern ("_NET_GLOBALMENU_MENU_SELECT", FALSE);
	menu_bar_agent_atom_deselect = gdk_atom_intern ("_NET_GLOBALMENU_MENU_DESELECT", FALSE);
	menu_bar_agent_atom_activate = gdk_atom_intern ("_NET_GLOBALMENU_MENU_EVENT", FALSE);
}


static void menu_bar_agent_instance_init (MenuBarAgent * self) {
	self->priv = MENU_BAR_AGENT_GET_PRIVATE (self);
	self->priv->dirty = FALSE;
	self->ref_count = 1;
}


static void menu_bar_agent_finalize (MenuBarAgent* obj) {
	MenuBarAgent * self;
	self = MENU_BAR_AGENT (obj);
	{
		g_debug ("agent.vala:96: dispose MenuBarAgent");
		menu_bar_agent_release_menubar (self);
		menu_bar_agent_release_toplevel (self);
		menu_bar_agent_release_event_window (self);
	}
	_g_object_unref0 (self->priv->_settings);
}


GType menu_bar_agent_get_type (void) {
	static volatile gsize menu_bar_agent_type_id__volatile = 0;
	if (g_once_init_enter (&menu_bar_agent_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_menu_bar_agent_init, value_menu_bar_agent_free_value, value_menu_bar_agent_copy_value, value_menu_bar_agent_peek_pointer, "p", value_menu_bar_agent_collect_value, "p", value_menu_bar_agent_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (MenuBarAgentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) menu_bar_agent_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MenuBarAgent), 0, (GInstanceInitFunc) menu_bar_agent_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType menu_bar_agent_type_id;
		menu_bar_agent_type_id = g_type_register_fundamental (g_type_fundamental_next (), "MenuBarAgent", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&menu_bar_agent_type_id__volatile, menu_bar_agent_type_id);
	}
	return menu_bar_agent_type_id__volatile;
}


gpointer menu_bar_agent_ref (gpointer instance) {
	MenuBarAgent* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void menu_bar_agent_unref (gpointer instance) {
	MenuBarAgent* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		MENU_BAR_AGENT_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}




