/* gtk-widget.c generated by valac, the Vala compiler
 * generated from gtk-widget.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>


#define TYPE_WIDGET (widget_get_type ())
#define WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WIDGET, Widget))
#define WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WIDGET, WidgetClass))
#define IS_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WIDGET))
#define IS_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WIDGET))
#define WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WIDGET, WidgetClass))

typedef struct _Widget Widget;
typedef struct _WidgetClass WidgetClass;
typedef struct _WidgetPrivate WidgetPrivate;

#define TYPE_MENU_BAR_AGENT_FACTORY (menu_bar_agent_factory_get_type ())
#define MENU_BAR_AGENT_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MENU_BAR_AGENT_FACTORY, MenuBarAgentFactory))
#define MENU_BAR_AGENT_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MENU_BAR_AGENT_FACTORY, MenuBarAgentFactoryClass))
#define IS_MENU_BAR_AGENT_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MENU_BAR_AGENT_FACTORY))
#define IS_MENU_BAR_AGENT_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MENU_BAR_AGENT_FACTORY))
#define MENU_BAR_AGENT_FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MENU_BAR_AGENT_FACTORY, MenuBarAgentFactoryClass))

typedef struct _MenuBarAgentFactory MenuBarAgentFactory;
typedef struct _MenuBarAgentFactoryClass MenuBarAgentFactoryClass;

#define TYPE_MENU_BAR_AGENT (menu_bar_agent_get_type ())
#define MENU_BAR_AGENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MENU_BAR_AGENT, MenuBarAgent))
#define MENU_BAR_AGENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MENU_BAR_AGENT, MenuBarAgentClass))
#define IS_MENU_BAR_AGENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MENU_BAR_AGENT))
#define IS_MENU_BAR_AGENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MENU_BAR_AGENT))
#define MENU_BAR_AGENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MENU_BAR_AGENT, MenuBarAgentClass))

typedef struct _MenuBarAgent MenuBarAgent;
typedef struct _MenuBarAgentClass MenuBarAgentClass;
#define _menu_bar_agent_factory_unref0(var) ((var == NULL) ? NULL : (var = (menu_bar_agent_factory_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
typedef struct _ParamSpecWidget ParamSpecWidget;

struct _Widget {
	GTypeInstance parent_instance;
	volatile int ref_count;
	WidgetPrivate * priv;
};

struct _WidgetClass {
	GTypeClass parent_class;
	void (*finalize) (Widget *self);
};

typedef void (*WidgetParentSetFunc) (GtkWidget* widget, GtkWidget* old_parent);
struct _ParamSpecWidget {
	GParamSpec parent_instance;
};


static gpointer widget_parent_class = NULL;

gpointer widget_ref (gpointer instance);
void widget_unref (gpointer instance);
GParamSpec* param_spec_widget (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_widget (GValue* value, gpointer v_object);
void value_take_widget (GValue* value, gpointer v_object);
gpointer value_get_widget (const GValue* value);
GType widget_get_type (void) G_GNUC_CONST;
enum  {
	WIDGET_DUMMY_PROPERTY
};
void superrider_superride (GType type, gint offset, void* vfunc);
void widget_parent_set (GtkWidget* widget, GtkWidget* old_parent);
Widget* widget_new (void);
Widget* widget_construct (GType object_type);
void* superrider_peek_super (GType type, gint offset);
gpointer menu_bar_agent_factory_ref (gpointer instance);
void menu_bar_agent_factory_unref (gpointer instance);
GParamSpec* param_spec_menu_bar_agent_factory (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_menu_bar_agent_factory (GValue* value, gpointer v_object);
void value_take_menu_bar_agent_factory (GValue* value, gpointer v_object);
gpointer value_get_menu_bar_agent_factory (const GValue* value);
GType menu_bar_agent_factory_get_type (void) G_GNUC_CONST;
MenuBarAgentFactory* menu_bar_agent_factory_get (void);
gpointer menu_bar_agent_ref (gpointer instance);
void menu_bar_agent_unref (gpointer instance);
GParamSpec* param_spec_menu_bar_agent (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_menu_bar_agent (GValue* value, gpointer v_object);
void value_take_menu_bar_agent (GValue* value, gpointer v_object);
gpointer value_get_menu_bar_agent (const GValue* value);
GType menu_bar_agent_get_type (void) G_GNUC_CONST;
MenuBarAgent* menu_bar_agent_factory_create (MenuBarAgentFactory* self, GtkMenuBar* menubar);
GtkMenuBar* widget_get_menubar (GtkWidget* widget);
void widget_set_menubar_r (GtkWidget* widget, GtkMenuBar* menubar);
static void widget_try_disconnect_label (GtkWidget* widget);
static void widget_try_disconnect_menuitem (GtkWidget* widget);
void menu_bar_queue_changed (GtkMenuBar* menubar);
static void widget_try_connect_label (GtkWidget* widget);
static void widget_try_connect_menuitem (GtkWidget* widget);
static void widget_set_menubar (GtkWidget* widget, GtkMenuBar* menubar);
static void widget_simple_changed (GtkWidget* widget, GParamSpec* pspec);
static void _widget_simple_changed_g_object_notify (GtkWidget* _sender, GParamSpec* pspec, gpointer self);
static void widget_recursive_changed (GtkWidget* widget, GParamSpec* pspec);
static void _widget_recursive_changed_g_object_notify (GtkWidget* _sender, GParamSpec* pspec, gpointer self);
static void widget_finalize (Widget* obj);



Widget* widget_construct (GType object_type) {
	Widget* self;
	self = (Widget*) g_type_create_instance (object_type);
	superrider_superride (GTK_TYPE_WIDGET, G_STRUCT_OFFSET(GtkWidgetClass, parent_set), (void*) widget_parent_set);
	return self;
}


Widget* widget_new (void) {
	return widget_construct (TYPE_WIDGET);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void widget_parent_set (GtkWidget* widget, GtkWidget* old_parent) {
	WidgetParentSetFunc super;
	gboolean _tmp1_ = FALSE;
	GtkContainer* parent;
	GtkMenuBar* menubar;
	super = (WidgetParentSetFunc) superrider_peek_super (GTK_TYPE_WIDGET, G_STRUCT_OFFSET(GtkWidgetClass, parent_set));
	if (super != NULL) {
		super (widget, old_parent);
	}
	if (GTK_IS_MENU_BAR (widget)) {
		MenuBarAgentFactory* factory;
		GtkWidget* _tmp0_;
		factory = menu_bar_agent_factory_get ();
		menu_bar_agent_factory_create (factory, (_tmp0_ = widget, GTK_IS_MENU_BAR (_tmp0_) ? ((GtkMenuBar*) _tmp0_) : NULL));
		g_debug ("gtk-widget.vala:25: menubar detected %p", widget);
		_menu_bar_agent_factory_unref0 (factory);
	}
	if (GTK_IS_MENU_BAR (widget)) {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = GTK_IS_MENU (widget);
	}
	if (_tmp1_) {
		return;
	}
	parent = _g_object_ref0 (gtk_widget_get_parent (widget));
	menubar = NULL;
	if (parent != NULL) {
		GtkMenuBar* _tmp2_;
		menubar = (_tmp2_ = _g_object_ref0 (widget_get_menubar ((GtkWidget*) parent)), _g_object_unref0 (menubar), _tmp2_);
	}
	widget_set_menubar_r (widget, menubar);
	_g_object_unref0 (menubar);
	_g_object_unref0 (parent);
}


GtkMenuBar* widget_get_menubar (GtkWidget* widget) {
	GtkMenuBar* result = NULL;
	GtkMenuBar* menubar;
	g_return_val_if_fail (widget != NULL, NULL);
	if (GTK_IS_MENU_BAR (widget)) {
		GtkWidget* _tmp0_;
		result = (_tmp0_ = widget, GTK_IS_MENU_BAR (_tmp0_) ? ((GtkMenuBar*) _tmp0_) : NULL);
		return result;
	}
	menubar = (GtkMenuBar*) g_object_get_data ((GObject*) widget, "globalmenu-menubar");
	result = menubar;
	return result;
}


static void widget_set_menubar (GtkWidget* widget, GtkMenuBar* menubar) {
	GtkMenuBar* old_menubar;
	g_return_if_fail (widget != NULL);
	g_assert (!GTK_IS_MENU_BAR (widget));
	old_menubar = _g_object_ref0 (widget_get_menubar (widget));
	if (old_menubar == menubar) {
		_g_object_unref0 (old_menubar);
		return;
	}
	if (old_menubar != NULL) {
		widget_try_disconnect_label (widget);
		widget_try_disconnect_menuitem (widget);
		menu_bar_queue_changed (old_menubar);
	}
	g_object_set_data_full ((GObject*) widget, "globalmenu-menubar", (void*) menubar, NULL);
	if (menubar != NULL) {
		widget_try_connect_label (widget);
		widget_try_connect_menuitem (widget);
		menu_bar_queue_changed (menubar);
	}
	_g_object_unref0 (old_menubar);
}


void widget_set_menubar_r (GtkWidget* widget, GtkMenuBar* menubar) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (widget != NULL);
	if (menubar == NULL) {
		_tmp0_ = GTK_IS_MENU_BAR (widget);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		return;
	}
	widget_set_menubar (widget, menubar);
	if (GTK_IS_CONTAINER (widget)) {
		GtkWidget* _tmp1_;
		GList* children;
		children = gtk_container_get_children ((_tmp1_ = widget, GTK_IS_CONTAINER (_tmp1_) ? ((GtkContainer*) _tmp1_) : NULL));
		{
			GList* child_collection;
			GList* child_it;
			child_collection = children;
			for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
				GtkWidget* child;
				child = (GtkWidget*) child_it->data;
				{
					widget_set_menubar_r (child, menubar);
				}
			}
		}
		_g_list_free0 (children);
	}
	if (GTK_IS_MENU_ITEM (widget)) {
		GtkWidget* _tmp2_;
		GtkMenuItem* item;
		item = _g_object_ref0 ((_tmp2_ = widget, GTK_IS_MENU_ITEM (_tmp2_) ? ((GtkMenuItem*) _tmp2_) : NULL));
		if (gtk_menu_item_get_submenu (item) != NULL) {
			widget_set_menubar_r ((GtkWidget*) gtk_menu_item_get_submenu (item), menubar);
		}
		_g_object_unref0 (item);
	}
}


static void _widget_simple_changed_g_object_notify (GtkWidget* _sender, GParamSpec* pspec, gpointer self) {
	widget_simple_changed (_sender, pspec);
}


static void widget_try_connect_label (GtkWidget* widget) {
	g_return_if_fail (widget != NULL);
	if (GTK_IS_LABEL (widget)) {
		g_signal_connect ((GObject*) widget, "notify::label", (GCallback) _widget_simple_changed_g_object_notify, NULL);
	}
}


static void _widget_recursive_changed_g_object_notify (GtkWidget* _sender, GParamSpec* pspec, gpointer self) {
	widget_recursive_changed (_sender, pspec);
}


static void widget_try_connect_menuitem (GtkWidget* widget) {
	g_return_if_fail (widget != NULL);
	if (GTK_IS_MENU_ITEM (widget)) {
		g_signal_connect ((GObject*) widget, "notify::submenu", (GCallback) _widget_recursive_changed_g_object_notify, NULL);
		g_signal_connect ((GObject*) widget, "notify::visible", (GCallback) _widget_simple_changed_g_object_notify, NULL);
		g_signal_connect ((GObject*) widget, "notify::sensitive", (GCallback) _widget_simple_changed_g_object_notify, NULL);
	}
	if (GTK_IS_CHECK_MENU_ITEM (widget)) {
		g_signal_connect ((GObject*) widget, "notify::active", (GCallback) _widget_simple_changed_g_object_notify, NULL);
		g_signal_connect ((GObject*) widget, "notify::inconsistent", (GCallback) _widget_simple_changed_g_object_notify, NULL);
		g_signal_connect ((GObject*) widget, "notify::draw-as-radio", (GCallback) _widget_simple_changed_g_object_notify, NULL);
	}
}


static void widget_try_disconnect_menuitem (GtkWidget* widget) {
	g_return_if_fail (widget != NULL);
	if (GTK_IS_MENU_ITEM (widget)) {
		guint _tmp0_;
		guint _tmp1_;
		g_signal_parse_name ("notify", G_TYPE_OBJECT, &_tmp0_, NULL, FALSE);
		g_signal_handlers_disconnect_matched ((GObject*) widget, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp0_, 0, NULL, (GCallback) _widget_simple_changed_g_object_notify, NULL);
		g_signal_parse_name ("notify", G_TYPE_OBJECT, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched ((GObject*) widget, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _widget_recursive_changed_g_object_notify, NULL);
	}
}


static void widget_try_disconnect_label (GtkWidget* widget) {
	g_return_if_fail (widget != NULL);
	if (GTK_IS_LABEL (widget)) {
		guint _tmp0_;
		g_signal_parse_name ("notify", G_TYPE_OBJECT, &_tmp0_, NULL, FALSE);
		g_signal_handlers_disconnect_matched ((GObject*) widget, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp0_, 0, NULL, (GCallback) _widget_simple_changed_g_object_notify, NULL);
	}
}


static void widget_simple_changed (GtkWidget* widget, GParamSpec* pspec) {
	GtkMenuBar* menubar;
	g_return_if_fail (widget != NULL);
	g_return_if_fail (pspec != NULL);
	menubar = _g_object_ref0 (widget_get_menubar (widget));
	g_assert (menubar != NULL);
	menu_bar_queue_changed (menubar);
	_g_object_unref0 (menubar);
}


static void widget_recursive_changed (GtkWidget* widget, GParamSpec* pspec) {
	GtkWidget* _tmp0_;
	GtkMenuItem* item;
	GtkMenu* submenu;
	GtkMenu* old_submenu;
	GtkMenuBar* menubar;
	g_return_if_fail (widget != NULL);
	g_return_if_fail (pspec != NULL);
	g_assert (GTK_IS_MENU_ITEM (widget));
	item = _g_object_ref0 ((_tmp0_ = widget, GTK_IS_MENU_ITEM (_tmp0_) ? ((GtkMenuItem*) _tmp0_) : NULL));
	submenu = _g_object_ref0 (gtk_menu_item_get_submenu (item));
	old_submenu = _g_object_ref0 ((GtkMenu*) g_object_get_data ((GObject*) item, "old_submenu"));
	menubar = _g_object_ref0 (widget_get_menubar (widget));
	if (submenu == old_submenu) {
		widget_simple_changed (widget, pspec);
		_g_object_unref0 (menubar);
		_g_object_unref0 (old_submenu);
		_g_object_unref0 (submenu);
		_g_object_unref0 (item);
		return;
	}
	if (old_submenu != NULL) {
		widget_set_menubar_r ((GtkWidget*) old_submenu, NULL);
	}
	if (submenu != NULL) {
		widget_set_menubar_r ((GtkWidget*) submenu, menubar);
	}
	g_object_set_data_full ((GObject*) widget, "old_submenu", (void*) submenu, NULL);
	widget_simple_changed (widget, pspec);
	_g_object_unref0 (menubar);
	_g_object_unref0 (old_submenu);
	_g_object_unref0 (submenu);
	_g_object_unref0 (item);
}


static void value_widget_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_widget_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		widget_unref (value->data[0].v_pointer);
	}
}


static void value_widget_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = widget_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_widget_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_widget_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		Widget* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = widget_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_widget_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	Widget** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags && G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = widget_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_widget (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecWidget* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_WIDGET), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_widget (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_WIDGET), NULL);
	return value->data[0].v_pointer;
}


void value_set_widget (GValue* value, gpointer v_object) {
	Widget* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_WIDGET));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_WIDGET));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		widget_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		widget_unref (old);
	}
}


void value_take_widget (GValue* value, gpointer v_object) {
	Widget* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_WIDGET));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_WIDGET));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		widget_unref (old);
	}
}


static void widget_class_init (WidgetClass * klass) {
	widget_parent_class = g_type_class_peek_parent (klass);
	WIDGET_CLASS (klass)->finalize = widget_finalize;
}


static void widget_instance_init (Widget * self) {
	self->ref_count = 1;
}


static void widget_finalize (Widget* obj) {
	Widget * self;
	self = WIDGET (obj);
	{
	}
}


GType widget_get_type (void) {
	static volatile gsize widget_type_id__volatile = 0;
	if (g_once_init_enter (&widget_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_widget_init, value_widget_free_value, value_widget_copy_value, value_widget_peek_pointer, "p", value_widget_collect_value, "p", value_widget_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (WidgetClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) widget_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Widget), 0, (GInstanceInitFunc) widget_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType widget_type_id;
		widget_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Widget", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&widget_type_id__volatile, widget_type_id);
	}
	return widget_type_id__volatile;
}


gpointer widget_ref (gpointer instance) {
	Widget* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void widget_unref (gpointer instance) {
	Widget* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		WIDGET_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}




