/* gtkextra-mateconfdialog.c generated by valac, the Vala compiler
 * generated from gtkextra-mateconfdialog.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <mateconf/mateconf-client.h>
#include <stdlib.h>
#include <string.h>
#include <mateconf/mateconf.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>


#define TYPE_MATECONF_DIALOG (mateconf_dialog_get_type ())
#define MATECONF_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MATECONF_DIALOG, MateConfDialog))
#define MATECONF_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MATECONF_DIALOG, MateConfDialogClass))
#define IS_MATECONF_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MATECONF_DIALOG))
#define IS_MATECONF_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MATECONF_DIALOG))
#define MATECONF_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MATECONF_DIALOG, MateConfDialogClass))

typedef struct _MateConfDialog MateConfDialog;
typedef struct _MateConfDialogClass MateConfDialogClass;
typedef struct _MateConfDialogPrivate MateConfDialogPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _mateconf_schema_free0(var) ((var == NULL) ? NULL : (var = (mateconf_schema_free (var), NULL)))
#define _mateconf_entry_unref0(var) ((var == NULL) ? NULL : (var = (mateconf_entry_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _MateConfDialog {
	GtkDialog parent_instance;
	MateConfDialogPrivate * priv;
};

struct _MateConfDialogClass {
	GtkDialogClass parent_class;
};

struct _MateConfDialogPrivate {
	MateConfClient* _default_client;
	GtkNotebook* notebook;
};


static gpointer mateconf_dialog_parent_class = NULL;

GType mateconf_dialog_get_type (void) G_GNUC_CONST;
#define MATECONF_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MATECONF_DIALOG, MateConfDialogPrivate))
enum  {
	MATECONF_DIALOG_DUMMY_PROPERTY
};
MateConfDialog* mateconf_dialog_new (const char* dialog_title);
MateConfDialog* mateconf_dialog_construct (GType object_type, const char* dialog_title);
static GtkWidget* mateconf_dialog_create_proxy_widget (MateConfDialog* self, const char* key, GError** error);
void mateconf_dialog_add_key_group (MateConfDialog* self, const char* group_name, char** keys, int keys_length1);
static MateConfSchema* mateconf_dialog_safely_get_schema (MateConfDialog* self, MateConfEntry* entry);
static void mateconf_dialog_onCheckButtonActivated (MateConfDialog* self, GtkCheckButton* widget);
static void _mateconf_dialog_onCheckButtonActivated_gtk_button_clicked (GtkCheckButton* _sender, gpointer self);
static void mateconf_dialog_onSpinButtonValueChanged (MateConfDialog* self, GtkSpinButton* widget);
static void _mateconf_dialog_onSpinButtonValueChanged_gtk_spin_button_value_changed (GtkSpinButton* _sender, gpointer self);
static void mateconf_dialog_onResetButtonPressed (MateConfDialog* self, GtkButton* widget);
static void _mateconf_dialog_onResetButtonPressed_gtk_button_clicked (GtkButton* _sender, gpointer self);
static GObject * mateconf_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void mateconf_dialog_finalize (GObject* obj);



MateConfDialog* mateconf_dialog_construct (GType object_type, const char* dialog_title) {
	MateConfDialog * self;
	g_return_val_if_fail (dialog_title != NULL, NULL);
	self = g_object_newv (object_type, 0, NULL);
	gtk_window_set_title ((GtkWindow*) self, dialog_title);
	gtk_window_set_icon_name ((GtkWindow*) self, "gtk-preferences");
	return self;
}


MateConfDialog* mateconf_dialog_new (const char* dialog_title) {
	return mateconf_dialog_construct (TYPE_MATECONF_DIALOG, dialog_title);
}


void mateconf_dialog_add_key_group (MateConfDialog* self, const char* group_name, char** keys, int keys_length1) {
	GError * _inner_error_;
	GtkAlignment* alignment;
	GtkVBox* box;
	GtkLabel* label_widget;
	g_return_if_fail (self != NULL);
	g_return_if_fail (group_name != NULL);
	_inner_error_ = NULL;
	alignment = g_object_ref_sink ((GtkAlignment*) gtk_alignment_new (0.0f, 0.0f, 1.0f, 1.0f));
	box = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 0));
	label_widget = g_object_ref_sink ((GtkLabel*) gtk_label_new (group_name));
	g_object_set (alignment, "left-padding", (guint) 10, NULL);
	{
		char** key_collection;
		int key_collection_length1;
		int key_it;
		key_collection = keys;
		key_collection_length1 = keys_length1;
		for (key_it = 0; key_it < keys_length1; key_it = key_it + 1) {
			const char* key;
			key = key_collection[key_it];
			{
				{
					GtkWidget* widget;
					widget = mateconf_dialog_create_proxy_widget (self, key, &_inner_error_);
					if (_inner_error_ != NULL) {
						goto __catch21_g_error;
					}
					gtk_box_pack_start ((GtkBox*) box, widget, FALSE, FALSE, (guint) 5);
					_g_object_unref0 (widget);
				}
				goto __finally21;
				__catch21_g_error:
				{
					GError * e;
					e = _inner_error_;
					_inner_error_ = NULL;
					{
						g_warning ("gtkextra-mateconfdialog.vala:57: %s", e->message);
						_g_error_free0 (e);
					}
				}
				__finally21:
				if (_inner_error_ != NULL) {
					_g_object_unref0 (label_widget);
					_g_object_unref0 (box);
					_g_object_unref0 (alignment);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
			}
		}
	}
	gtk_container_add ((GtkContainer*) alignment, (GtkWidget*) box);
	gtk_widget_show_all ((GtkWidget*) alignment);
	gtk_widget_show_all ((GtkWidget*) label_widget);
	gtk_notebook_append_page (self->priv->notebook, (GtkWidget*) alignment, (GtkWidget*) label_widget);
	_g_object_unref0 (label_widget);
	_g_object_unref0 (box);
	_g_object_unref0 (alignment);
}


static void _mateconf_dialog_onCheckButtonActivated_gtk_button_clicked (GtkCheckButton* _sender, gpointer self) {
	mateconf_dialog_onCheckButtonActivated (self, _sender);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _mateconf_dialog_onSpinButtonValueChanged_gtk_spin_button_value_changed (GtkSpinButton* _sender, gpointer self) {
	mateconf_dialog_onSpinButtonValueChanged (self, _sender);
}


static void _mateconf_dialog_onResetButtonPressed_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	mateconf_dialog_onResetButtonPressed (self, _sender);
}


static GtkWidget* mateconf_dialog_create_proxy_widget (MateConfDialog* self, const char* key, GError** error) {
	GtkWidget* result = NULL;
	GError * _inner_error_;
	MateConfEntry* entry;
	MateConfSchema* schema;
	const char* tooltip;
	GtkBox* row;
	GtkLabel* label;
	GtkWidget* action_widget;
	GtkWidget* render_widget;
	MateConfEntry* _tmp10_;
	GtkButton* reset;
	MateConfEntry* _tmp11_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (key != NULL, NULL);
	_inner_error_ = NULL;
	entry = mateconf_client_get_entry (self->priv->_default_client, key, NULL, TRUE, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return NULL;
	}
	schema = mateconf_dialog_safely_get_schema (self, entry);
	tooltip = mateconf_schema_get_long_desc (schema);
	row = (GtkBox*) g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 0));
	label = g_object_ref_sink ((GtkLabel*) gtk_label_new (mateconf_schema_get_short_desc (schema)));
	gtk_label_set_justify (label, GTK_JUSTIFY_LEFT);
	gtk_widget_set_tooltip_text ((GtkWidget*) label, tooltip);
	action_widget = NULL;
	render_widget = NULL;
	switch (mateconf_schema_get_type (schema)) {
		case MATECONF_VALUE_BOOL:
		{
			GtkCheckButton* checkbox;
			gboolean _tmp0_;
			GtkWidget* _tmp1_;
			GtkWidget* _tmp2_;
			checkbox = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new ());
			_tmp0_ = mateconf_client_get_bool (self->priv->_default_client, entry->key, &_inner_error_);
			if (_inner_error_ != NULL) {
				g_propagate_error (error, _inner_error_);
				_g_object_unref0 (checkbox);
				_g_object_unref0 (render_widget);
				_g_object_unref0 (action_widget);
				_g_object_unref0 (label);
				_g_object_unref0 (row);
				_mateconf_schema_free0 (schema);
				_mateconf_entry_unref0 (entry);
				return NULL;
			}
			gtk_toggle_button_set_active ((GtkToggleButton*) checkbox, _tmp0_);
			g_signal_connect_object ((GtkButton*) checkbox, "clicked", (GCallback) _mateconf_dialog_onCheckButtonActivated_gtk_button_clicked, self, 0);
			gtk_container_add ((GtkContainer*) checkbox, (GtkWidget*) label);
			render_widget = (_tmp1_ = _g_object_ref0 ((GtkWidget*) checkbox), _g_object_unref0 (render_widget), _tmp1_);
			action_widget = (_tmp2_ = _g_object_ref0 (render_widget), _g_object_unref0 (action_widget), _tmp2_);
			_g_object_unref0 (checkbox);
			break;
		}
		case MATECONF_VALUE_STRING:
		{
			GtkEntry* entrybox;
			GtkHBox* box;
			char* _tmp3_;
			char* _tmp4_;
			GtkWidget* _tmp5_;
			GtkWidget* _tmp6_;
			entrybox = g_object_ref_sink ((GtkEntry*) gtk_entry_new ());
			box = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 0));
			_tmp3_ = mateconf_client_get_string (self->priv->_default_client, entry->key, &_inner_error_);
			if (_inner_error_ != NULL) {
				g_propagate_error (error, _inner_error_);
				_g_object_unref0 (box);
				_g_object_unref0 (entrybox);
				_g_object_unref0 (render_widget);
				_g_object_unref0 (action_widget);
				_g_object_unref0 (label);
				_g_object_unref0 (row);
				_mateconf_schema_free0 (schema);
				_mateconf_entry_unref0 (entry);
				return NULL;
			}
			gtk_entry_set_text (entrybox, _tmp4_ = _tmp3_);
			_g_free0 (_tmp4_);
			gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) label, FALSE, FALSE, (guint) 2);
			gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) entrybox, FALSE, FALSE, (guint) 2);
			action_widget = (_tmp5_ = _g_object_ref0 ((GtkWidget*) entrybox), _g_object_unref0 (action_widget), _tmp5_);
			render_widget = (_tmp6_ = _g_object_ref0 ((GtkWidget*) box), _g_object_unref0 (render_widget), _tmp6_);
			_g_object_unref0 (box);
			_g_object_unref0 (entrybox);
			break;
		}
		case MATECONF_VALUE_INT:
		{
			GtkHBox* box;
			GtkSpinButton* spin;
			gint _tmp7_;
			GtkWidget* _tmp8_;
			GtkWidget* _tmp9_;
			box = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 0));
			spin = g_object_ref_sink ((GtkSpinButton*) gtk_spin_button_new_with_range ((double) (-100), (double) 200, (double) 1));
			_tmp7_ = mateconf_client_get_int (self->priv->_default_client, entry->key, &_inner_error_);
			if (_inner_error_ != NULL) {
				g_propagate_error (error, _inner_error_);
				_g_object_unref0 (spin);
				_g_object_unref0 (box);
				_g_object_unref0 (render_widget);
				_g_object_unref0 (action_widget);
				_g_object_unref0 (label);
				_g_object_unref0 (row);
				_mateconf_schema_free0 (schema);
				_mateconf_entry_unref0 (entry);
				return NULL;
			}
			gtk_spin_button_set_value (spin, (double) _tmp7_);
			g_signal_connect_object (spin, "value-changed", (GCallback) _mateconf_dialog_onSpinButtonValueChanged_gtk_spin_button_value_changed, self, 0);
			gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) label, FALSE, FALSE, (guint) 2);
			gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) spin, FALSE, FALSE, (guint) 2);
			action_widget = (_tmp8_ = _g_object_ref0 ((GtkWidget*) spin), _g_object_unref0 (action_widget), _tmp8_);
			render_widget = (_tmp9_ = _g_object_ref0 ((GtkWidget*) box), _g_object_unref0 (render_widget), _tmp9_);
			_g_object_unref0 (spin);
			_g_object_unref0 (box);
			break;
		}
		default:
		{
			result = (GtkWidget*) g_object_ref_sink ((GtkEventBox*) gtk_event_box_new ());
			_g_object_unref0 (render_widget);
			_g_object_unref0 (action_widget);
			_g_object_unref0 (label);
			_g_object_unref0 (row);
			_mateconf_schema_free0 (schema);
			_mateconf_entry_unref0 (entry);
			return result;
		}
	}
	gtk_widget_set_tooltip_text (action_widget, tooltip);
	g_object_set_data_full ((GObject*) action_widget, "mateconf-entry", (_tmp10_ = entry, (_tmp10_ == NULL) ? NULL : mateconf_entry_ref (_tmp10_), _tmp10_), mateconf_entry_unref);
	g_object_set_data_full ((GObject*) action_widget, "mateconf-schema", mateconf_schema_copy (schema), mateconf_schema_free);
	reset = g_object_ref_sink ((GtkButton*) gtk_button_new_from_stock (GTK_STOCK_CLEAR));
	gtk_widget_set_tooltip_text ((GtkWidget*) reset, _ ("Reset to the default value"));
	g_object_set_data_full ((GObject*) reset, "mateconf-entry", (_tmp11_ = entry, (_tmp11_ == NULL) ? NULL : mateconf_entry_ref (_tmp11_), _tmp11_), mateconf_entry_unref);
	g_object_set_data_full ((GObject*) reset, "mateconf-schema", mateconf_schema_copy (schema), mateconf_schema_free);
	g_object_set_data_full ((GObject*) reset, "target", _g_object_ref0 (action_widget), g_object_unref);
	g_signal_connect_object (reset, "clicked", (GCallback) _mateconf_dialog_onResetButtonPressed_gtk_button_clicked, self, 0);
	gtk_box_pack_start (row, render_widget, FALSE, FALSE, (guint) 2);
	gtk_box_pack_end (row, (GtkWidget*) reset, FALSE, FALSE, (guint) 2);
	result = (GtkWidget*) row;
	_g_object_unref0 (reset);
	_g_object_unref0 (render_widget);
	_g_object_unref0 (action_widget);
	_g_object_unref0 (label);
	_mateconf_schema_free0 (schema);
	_mateconf_entry_unref0 (entry);
	return result;
}


static void mateconf_dialog_onCheckButtonActivated (MateConfDialog* self, GtkCheckButton* widget) {
	GError * _inner_error_;
	MateConfEntry* _tmp0_;
	MateConfEntry* entry;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	_inner_error_ = NULL;
	entry = (_tmp0_ = (MateConfEntry*) g_object_get_data ((GObject*) widget, "mateconf-entry"), (_tmp0_ == NULL) ? NULL : mateconf_entry_ref (_tmp0_), _tmp0_);
	{
		mateconf_client_set_bool (self->priv->_default_client, entry->key, gtk_toggle_button_get_active ((GtkToggleButton*) widget), &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch22_g_error;
		}
	}
	goto __finally22;
	__catch22_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("gtkextra-mateconfdialog.vala:135: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally22:
	if (_inner_error_ != NULL) {
		_mateconf_entry_unref0 (entry);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_mateconf_entry_unref0 (entry);
}


static void mateconf_dialog_onSpinButtonValueChanged (MateConfDialog* self, GtkSpinButton* widget) {
	GError * _inner_error_;
	MateConfEntry* _tmp0_;
	MateConfEntry* entry;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	_inner_error_ = NULL;
	entry = (_tmp0_ = (MateConfEntry*) g_object_get_data ((GObject*) widget, "mateconf-entry"), (_tmp0_ == NULL) ? NULL : mateconf_entry_ref (_tmp0_), _tmp0_);
	{
		mateconf_client_set_int (self->priv->_default_client, entry->key, (gint) gtk_spin_button_get_value (widget), &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch23_g_error;
		}
	}
	goto __finally23;
	__catch23_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_warning ("gtkextra-mateconfdialog.vala:144: %s", e->message);
			_g_error_free0 (e);
		}
	}
	__finally23:
	if (_inner_error_ != NULL) {
		_mateconf_entry_unref0 (entry);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_mateconf_entry_unref0 (entry);
}


static MateConfSchema* mateconf_dialog_safely_get_schema (MateConfDialog* self, MateConfEntry* entry) {
	MateConfSchema* result = NULL;
	GError * _inner_error_;
	const char* schema_name;
	MateConfSchema* rt;
	MateConfSchema* _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (entry != NULL, NULL);
	_inner_error_ = NULL;
	schema_name = mateconf_entry_get_schema_name (entry);
	rt = NULL;
	if (schema_name != NULL) {
		{
			MateConfSchema* _tmp0_;
			MateConfSchema* _tmp2_;
			MateConfSchema* _tmp1_;
			_tmp0_ = mateconf_client_get_schema (self->priv->_default_client, schema_name, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch24_g_error;
			}
			rt = (_tmp2_ = mateconf_schema_copy (_tmp1_ = _tmp0_), _mateconf_schema_free0 (rt), _tmp2_);
			_mateconf_schema_free0 (_tmp1_);
			result = rt;
			return result;
		}
		goto __finally24;
		__catch24_g_error:
		{
			GError * e;
			e = _inner_error_;
			_inner_error_ = NULL;
			{
				_g_error_free0 (e);
			}
		}
		__finally24:
		if (_inner_error_ != NULL) {
			_mateconf_schema_free0 (rt);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	g_critical ("gtkextra-mateconfdialog.vala:161: schema not found for entry %s", mateconf_entry_get_key (entry));
	rt = (_tmp3_ = mateconf_schema_new (), _mateconf_schema_free0 (rt), _tmp3_);
	mateconf_schema_set_short_desc (rt, mateconf_entry_get_key (entry));
	mateconf_schema_set_long_desc (rt, "This key lacks a schema");
	mateconf_schema_set_type (rt, MATECONF_VALUE_STRING);
	result = rt;
	return result;
}


static void mateconf_dialog_onResetButtonPressed (MateConfDialog* self, GtkButton* widget) {
	MateConfSchema* schema;
	MateConfValue* default_value;
	GtkWidget* target;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	schema = (MateConfSchema*) g_object_get_data ((GObject*) widget, "mateconf-schema");
	default_value = mateconf_schema_get_default_value (schema);
	target = _g_object_ref0 ((GtkWidget*) g_object_get_data ((GObject*) widget, "target"));
	switch (mateconf_schema_get_type (schema)) {
		case MATECONF_VALUE_BOOL:
		{
			GtkWidget* _tmp0_;
			GtkCheckButton* checkbutton;
			checkbutton = _g_object_ref0 ((_tmp0_ = target, GTK_IS_CHECK_BUTTON (_tmp0_) ? ((GtkCheckButton*) _tmp0_) : NULL));
			gtk_toggle_button_set_active ((GtkToggleButton*) checkbutton, mateconf_value_get_bool (default_value));
			_g_object_unref0 (checkbutton);
			break;
		}
		case MATECONF_VALUE_STRING:
		{
			GtkWidget* _tmp1_;
			GtkEntry* entrybox;
			entrybox = _g_object_ref0 ((_tmp1_ = target, GTK_IS_ENTRY (_tmp1_) ? ((GtkEntry*) _tmp1_) : NULL));
			gtk_entry_set_text (entrybox, mateconf_value_get_string (default_value));
			_g_object_unref0 (entrybox);
			break;
		}
		case MATECONF_VALUE_INT:
		{
			GtkWidget* _tmp2_;
			GtkSpinButton* spin;
			spin = _g_object_ref0 ((_tmp2_ = target, GTK_IS_SPIN_BUTTON (_tmp2_) ? ((GtkSpinButton*) _tmp2_) : NULL));
			gtk_spin_button_set_value (spin, (double) mateconf_value_get_int (default_value));
			_g_object_unref0 (spin);
			break;
		}
	}
	_g_object_unref0 (target);
}


static GObject * mateconf_dialog_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MateConfDialog * self;
	parent_class = G_OBJECT_CLASS (mateconf_dialog_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MATECONF_DIALOG (obj);
	{
		MateConfClient* _tmp0_;
		self->priv->_default_client = (_tmp0_ = _g_object_ref0 (mateconf_client_get_default ()), _g_object_unref0 (self->priv->_default_client), _tmp0_);
		gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_CLOSE, (gint) GTK_RESPONSE_CLOSE);
		gtk_dialog_add_button ((GtkDialog*) self, GTK_STOCK_HELP, (gint) GTK_RESPONSE_HELP);
		gtk_container_add ((GtkContainer*) ((GtkDialog*) self)->vbox, (GtkWidget*) self->priv->notebook);
		gtk_widget_show ((GtkWidget*) self->priv->notebook);
	}
	return obj;
}


static void mateconf_dialog_class_init (MateConfDialogClass * klass) {
	mateconf_dialog_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MateConfDialogPrivate));
	G_OBJECT_CLASS (klass)->constructor = mateconf_dialog_constructor;
	G_OBJECT_CLASS (klass)->finalize = mateconf_dialog_finalize;
}


static void mateconf_dialog_instance_init (MateConfDialog * self) {
	self->priv = MATECONF_DIALOG_GET_PRIVATE (self);
	self->priv->notebook = g_object_ref_sink ((GtkNotebook*) gtk_notebook_new ());
}


static void mateconf_dialog_finalize (GObject* obj) {
	MateConfDialog * self;
	self = MATECONF_DIALOG (obj);
	_g_object_unref0 (self->priv->_default_client);
	_g_object_unref0 (self->priv->notebook);
	G_OBJECT_CLASS (mateconf_dialog_parent_class)->finalize (obj);
}


GType mateconf_dialog_get_type (void) {
	static volatile gsize mateconf_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&mateconf_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MateConfDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) mateconf_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MateConfDialog), 0, (GInstanceInitFunc) mateconf_dialog_instance_init, NULL };
		GType mateconf_dialog_type_id;
		mateconf_dialog_type_id = g_type_register_static (GTK_TYPE_DIALOG, "MateConfDialog", &g_define_type_info, 0);
		g_once_init_leave (&mateconf_dialog_type_id__volatile, mateconf_dialog_type_id);
	}
	return mateconf_dialog_type_id__volatile;
}




