/* menubarbox.c generated by valac, the Vala compiler
 * generated from menubarbox.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <string.h>


#define MATENU_TYPE_MENU_BAR_BOX (matenu_menu_bar_box_get_type ())
#define MATENU_MENU_BAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_BAR_BOX, MatenuMenuBarBox))
#define MATENU_MENU_BAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_BAR_BOX, MatenuMenuBarBoxClass))
#define MATENU_IS_MENU_BAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_BAR_BOX))
#define MATENU_IS_MENU_BAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_BAR_BOX))
#define MATENU_MENU_BAR_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_BAR_BOX, MatenuMenuBarBoxClass))

typedef struct _MatenuMenuBarBox MatenuMenuBarBox;
typedef struct _MatenuMenuBarBoxClass MatenuMenuBarBoxClass;
typedef struct _MatenuMenuBarBoxPrivate MatenuMenuBarBoxPrivate;

#define MATENU_MENU_BAR_BOX_TYPE_CHILD_PROP_BAG (matenu_menu_bar_box_child_prop_bag_get_type ())
typedef struct _MatenuMenuBarBoxChildPropBag MatenuMenuBarBoxChildPropBag;

#define MATENU_TYPE_GRAVITY (matenu_gravity_get_type ())

#define MATENU_TYPE_MENU_BAR (matenu_menu_bar_get_type ())
#define MATENU_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_BAR, MatenuMenuBar))
#define MATENU_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_BAR, MatenuMenuBarClass))
#define MATENU_IS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_BAR))
#define MATENU_IS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_BAR))
#define MATENU_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_BAR, MatenuMenuBarClass))

typedef struct _MatenuMenuBar MatenuMenuBar;
typedef struct _MatenuMenuBarClass MatenuMenuBarClass;
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

#define MATENU_TYPE_BACKGROUND (matenu_background_get_type ())
#define MATENU_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_BACKGROUND, MatenuBackground))
#define MATENU_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_BACKGROUND, MatenuBackgroundClass))
#define MATENU_IS_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_BACKGROUND))
#define MATENU_IS_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_BACKGROUND))
#define MATENU_BACKGROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_BACKGROUND, MatenuBackgroundClass))

typedef struct _MatenuBackground MatenuBackground;
typedef struct _MatenuBackgroundClass MatenuBackgroundClass;
typedef struct _MatenuBackgroundPrivate MatenuBackgroundPrivate;

#define MATENU_TYPE_BACKGROUND_TYPE (matenu_background_type_get_type ())
#define _matenu_background_unref0(var) ((var == NULL) ? NULL : (var = (matenu_background_unref (var), NULL)))
#define _g_param_spec_unref0(var) ((var == NULL) ? NULL : (var = (g_param_spec_unref (var), NULL)))

struct _MatenuMenuBarBox {
	GtkContainer parent_instance;
	MatenuMenuBarBoxPrivate * priv;
};

struct _MatenuMenuBarBoxClass {
	GtkContainerClass parent_class;
};

struct _MatenuMenuBarBoxChildPropBag {
	gboolean expand;
	gboolean shrink;
};

typedef enum  {
	MATENU_GRAVITY_DOWN = 0,
	MATENU_GRAVITY_UP = 1,
	MATENU_GRAVITY_LEFT = 2,
	MATENU_GRAVITY_RIGHT = 3
} MatenuGravity;

struct _MatenuMenuBarBoxPrivate {
	GHashTable* props;
	GtkPackDirection _pack_direction;
	GtkPackDirection _child_pack_direction;
	MatenuGravity _gravity;
	GList* children;
	gint* size_hints;
	gint size_hints_length1;
	gint _size_hints_size_;
};

typedef enum  {
	MATENU_BACKGROUND_TYPE_NONE = 0,
	MATENU_BACKGROUND_TYPE_COLOR = 1,
	MATENU_BACKGROUND_TYPE_PIXMAP = 2
} MatenuBackgroundType;

struct _MatenuBackground {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MatenuBackgroundPrivate * priv;
	MatenuBackgroundType type;
	GdkPixmap* pixmap;
	GdkColor color;
	gint offset_x;
	gint offset_y;
};

struct _MatenuBackgroundClass {
	GTypeClass parent_class;
	void (*finalize) (MatenuBackground *self);
};


static gpointer matenu_menu_bar_box_parent_class = NULL;

GType matenu_menu_bar_box_get_type (void) G_GNUC_CONST;
static GType matenu_menu_bar_box_child_prop_bag_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static MatenuMenuBarBoxChildPropBag* matenu_menu_bar_box_child_prop_bag_dup (const MatenuMenuBarBoxChildPropBag* self);
static void matenu_menu_bar_box_child_prop_bag_free (MatenuMenuBarBoxChildPropBag* self);
GType matenu_gravity_get_type (void) G_GNUC_CONST;
GType matenu_menu_bar_get_type (void) G_GNUC_CONST;
#define MATENU_MENU_BAR_BOX_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MATENU_TYPE_MENU_BAR_BOX, MatenuMenuBarBoxPrivate))
enum  {
	MATENU_MENU_BAR_BOX_DUMMY_PROPERTY,
	MATENU_MENU_BAR_BOX_PACK_DIRECTION,
	MATENU_MENU_BAR_BOX_CHILD_PACK_DIRECTION,
	MATENU_MENU_BAR_BOX_GRAVITY,
	MATENU_MENU_BAR_BOX_BACKGROUND
};
#define MATENU_MENU_BAR_BOX_PROP_EXPAND 1234
#define MATENU_MENU_BAR_BOX_PROP_SHRINK 1235
MatenuMenuBarBox* matenu_menu_bar_box_new (void);
MatenuMenuBarBox* matenu_menu_bar_box_construct (GType object_type);
gint* matenu_menu_bar_box_get_size_hints (MatenuMenuBarBox* self, int* result_length1);
static void matenu_menu_bar_box_real_forall_internal (GtkContainer* base, gboolean include_internals, GtkCallback callback, void* callback_target);
GtkPackDirection matenu_menu_bar_box_get_pack_direction (MatenuMenuBarBox* self);
MatenuGravity matenu_menu_bar_box_get_gravity (MatenuMenuBarBox* self);
void matenu_menu_bar_set_gravity (MatenuMenuBar* self, MatenuGravity value);
static void matenu_menu_bar_box_real_add (GtkContainer* base, GtkWidget* child);
static void matenu_menu_bar_box_real_remove (GtkContainer* base, GtkWidget* child);
static void matenu_menu_bar_box_real_size_request (GtkWidget* base, GtkRequisition* r);
static void matenu_menu_bar_box_real_size_allocate (GtkWidget* base, GdkRectangle* a);
static void matenu_menu_bar_box_real_get_child_property (GtkContainer* base, GtkWidget* child, guint id, GValue* value, GParamSpec* pspec);
static void matenu_menu_bar_box_real_set_child_property (GtkContainer* base, GtkWidget* child, guint id, GValue* value, GParamSpec* pspec);
void matenu_menu_bar_box_set_pack_direction (MatenuMenuBarBox* self, GtkPackDirection value);
GtkPackDirection matenu_menu_bar_box_get_child_pack_direction (MatenuMenuBarBox* self);
void matenu_menu_bar_box_set_child_pack_direction (MatenuMenuBarBox* self, GtkPackDirection value);
void matenu_menu_bar_box_set_gravity (MatenuMenuBarBox* self, MatenuGravity value);
gpointer matenu_background_ref (gpointer instance);
void matenu_background_unref (gpointer instance);
GParamSpec* matenu_param_spec_background (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void matenu_value_set_background (GValue* value, gpointer v_object);
void matenu_value_take_background (GValue* value, gpointer v_object);
gpointer matenu_value_get_background (const GValue* value);
GType matenu_background_get_type (void) G_GNUC_CONST;
MatenuBackground* matenu_background_clone (MatenuBackground* self);
GType matenu_background_type_get_type (void) G_GNUC_CONST;
void matenu_menu_bar_set_background (MatenuMenuBar* self, MatenuBackground* value);
void matenu_menu_bar_box_set_background (MatenuMenuBarBox* self, MatenuBackground* value);
static void _g_free_gdestroy_notify (void* data);
static GObject * matenu_menu_bar_box_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void matenu_menu_bar_box_finalize (GObject* obj);
static void matenu_menu_bar_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void matenu_menu_bar_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



MatenuMenuBarBox* matenu_menu_bar_box_construct (GType object_type) {
	MatenuMenuBarBox * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


MatenuMenuBarBox* matenu_menu_bar_box_new (void) {
	return matenu_menu_bar_box_construct (MATENU_TYPE_MENU_BAR_BOX);
}


gint* matenu_menu_bar_box_get_size_hints (MatenuMenuBarBox* self, int* result_length1) {
	gint* result = NULL;
	gint* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	result = (_tmp0_ = self->priv->size_hints, *result_length1 = self->priv->size_hints_length1, _tmp0_);
	return result;
}


static void matenu_menu_bar_box_real_forall_internal (GtkContainer* base, gboolean include_internals, GtkCallback callback, void* callback_target) {
	MatenuMenuBarBox * self;
	GList* iter;
	self = (MatenuMenuBarBox*) base;
	if (include_internals) {
	}
	iter = self->priv->children;
	while (TRUE) {
		GtkWidget* child;
		if (!(iter != NULL)) {
			break;
		}
		child = (GtkWidget*) ((MatenuMenuBar*) iter->data);
		iter = iter->next;
		callback (child, callback_target);
	}
}


static void matenu_menu_bar_box_real_add (GtkContainer* base, GtkWidget* child) {
	MatenuMenuBarBox * self;
	self = (MatenuMenuBarBox*) base;
	g_return_if_fail (child != NULL);
	if (MATENU_IS_MENU_BAR (child)) {
		GtkWidget* _tmp0_;
		GtkWidget* _tmp1_;
		GtkWidget* _tmp2_;
		self->priv->children = g_list_append (self->priv->children, (_tmp0_ = child, MATENU_IS_MENU_BAR (_tmp0_) ? ((MatenuMenuBar*) _tmp0_) : NULL));
		gtk_widget_set_parent (child, (GtkWidget*) self);
		g_hash_table_insert (self->priv->props, child, (MatenuMenuBarBoxChildPropBag*) g_malloc0 ((gsize) sizeof (MatenuMenuBarBoxChildPropBag)));
		gtk_menu_bar_set_pack_direction ((GtkMenuBar*) (_tmp1_ = child, MATENU_IS_MENU_BAR (_tmp1_) ? ((MatenuMenuBar*) _tmp1_) : NULL), matenu_menu_bar_box_get_pack_direction (self));
		matenu_menu_bar_set_gravity ((_tmp2_ = child, MATENU_IS_MENU_BAR (_tmp2_) ? ((MatenuMenuBar*) _tmp2_) : NULL), matenu_menu_bar_box_get_gravity (self));
	}
}


static void matenu_menu_bar_box_real_remove (GtkContainer* base, GtkWidget* child) {
	MatenuMenuBarBox * self;
	self = (MatenuMenuBarBox*) base;
	g_return_if_fail (child != NULL);
	if (MATENU_IS_MENU_BAR (child)) {
		GtkWidget* _tmp0_;
		self->priv->children = g_list_remove_all (self->priv->children, (_tmp0_ = child, MATENU_IS_MENU_BAR (_tmp0_) ? ((MatenuMenuBar*) _tmp0_) : NULL));
		gtk_widget_unparent (child);
		g_hash_table_remove (self->priv->props, child);
	}
}


static void matenu_menu_bar_box_real_size_request (GtkWidget* base, GtkRequisition* r) {
	MatenuMenuBarBox * self;
	GtkRequisition cr = {0};
	GList* hints;
	gint* _tmp3_;
	gint _tmp2_;
	gint i;
	self = (MatenuMenuBarBox*) base;
	(*r).width = 0;
	(*r).height = 0;
	hints = NULL;
	{
		GList* menubar_collection;
		GList* menubar_it;
		menubar_collection = self->priv->children;
		for (menubar_it = menubar_collection; menubar_it != NULL; menubar_it = menubar_it->next) {
			MatenuMenuBar* menubar;
			menubar = (MatenuMenuBar*) menubar_it->data;
			{
				gboolean shrink;
				if (!gtk_widget_get_visible ((GtkWidget*) menubar)) {
					continue;
				}
				gtk_widget_size_request ((GtkWidget*) menubar, &cr);
				shrink = FALSE;
				gtk_container_child_get ((GtkContainer*) self, (GtkWidget*) menubar, "shrink", &shrink, NULL);
				switch (matenu_menu_bar_box_get_pack_direction (self)) {
					case GTK_PACK_DIRECTION_LTR:
					case GTK_PACK_DIRECTION_RTL:
					{
						gint _tmp0_ = 0;
						if ((*r).height > cr.height) {
							_tmp0_ = (*r).height;
						} else {
							_tmp0_ = cr.height;
						}
						(*r).height = _tmp0_;
						hints = g_list_prepend (hints, GINT_TO_POINTER ((*r).width + 2));
						(*r).width = (*r).width + cr.width;
						hints = g_list_prepend (hints, GINT_TO_POINTER ((*r).width + 1));
						break;
					}
					case GTK_PACK_DIRECTION_BTT:
					case GTK_PACK_DIRECTION_TTB:
					{
						gint _tmp1_ = 0;
						if ((*r).width > cr.width) {
							_tmp1_ = (*r).width;
						} else {
							_tmp1_ = cr.width;
						}
						(*r).width = _tmp1_;
						hints = g_list_prepend (hints, GINT_TO_POINTER ((*r).height + 2));
						(*r).height = (*r).height + cr.height;
						hints = g_list_prepend (hints, GINT_TO_POINTER ((*r).height + 1));
						break;
					}
				}
			}
		}
	}
	self->priv->size_hints = (_tmp3_ = g_new0 (gint, _tmp2_ = g_list_length (hints)), self->priv->size_hints = (g_free (self->priv->size_hints), NULL), self->priv->size_hints_length1 = _tmp2_, self->priv->_size_hints_size_ = self->priv->size_hints_length1, _tmp3_);
	i = 0;
	{
		GList* val_collection;
		GList* val_it;
		val_collection = hints;
		for (val_it = val_collection; val_it != NULL; val_it = val_it->next) {
			gint val;
			val = GPOINTER_TO_INT (val_it->data);
			{
				self->priv->size_hints[i] = val;
				i++;
			}
		}
	}
	_g_list_free0 (hints);
}


static void matenu_menu_bar_box_real_size_allocate (GtkWidget* base, GdkRectangle* a) {
	MatenuMenuBarBox * self;
	GtkRequisition cr = {0};
	GtkAllocation _tmp0_ = {0};
	GtkAllocation ca;
	gint x;
	gint y;
	gint rev_x;
	gint rev_y;
	gint num_of_shrinks;
	gint non_shrink_a;
	self = (MatenuMenuBarBox*) base;
	((GtkWidget*) self)->allocation = (GtkAllocation) (*a);
	ca = (_tmp0_.x = 0, _tmp0_.y = 0, _tmp0_.width = 0, _tmp0_.height = 0, _tmp0_);
	x = 0;
	y = 0;
	rev_x = (*a).width;
	rev_y = (*a).height;
	num_of_shrinks = 0;
	non_shrink_a = 0;
	{
		GList* menubar_collection;
		GList* menubar_it;
		menubar_collection = self->priv->children;
		for (menubar_it = menubar_collection; menubar_it != NULL; menubar_it = menubar_it->next) {
			MatenuMenuBar* menubar;
			menubar = (MatenuMenuBar*) menubar_it->data;
			{
				gboolean shrink;
				if (!gtk_widget_get_visible ((GtkWidget*) menubar)) {
					continue;
				}
				shrink = FALSE;
				gtk_container_child_get ((GtkContainer*) self, (GtkWidget*) menubar, "shrink", &shrink, NULL, NULL);
				if (shrink) {
					num_of_shrinks++;
				} else {
					gtk_widget_get_child_requisition ((GtkWidget*) menubar, &cr);
					switch (matenu_menu_bar_box_get_pack_direction (self)) {
						case GTK_PACK_DIRECTION_LTR:
						case GTK_PACK_DIRECTION_RTL:
						{
							non_shrink_a = non_shrink_a + cr.width;
							break;
						}
						case GTK_PACK_DIRECTION_BTT:
						case GTK_PACK_DIRECTION_TTB:
						{
							non_shrink_a = non_shrink_a + cr.height;
							break;
						}
					}
				}
			}
		}
	}
	{
		GList* menubar_collection;
		GList* menubar_it;
		menubar_collection = self->priv->children;
		for (menubar_it = menubar_collection; menubar_it != NULL; menubar_it = menubar_it->next) {
			MatenuMenuBar* menubar;
			menubar = (MatenuMenuBar*) menubar_it->data;
			{
				gboolean shrink;
				GdkRectangle _tmp1_;
				shrink = FALSE;
				if (!gtk_widget_get_visible ((GtkWidget*) menubar)) {
					continue;
				}
				gtk_widget_get_child_requisition ((GtkWidget*) menubar, &cr);
				gtk_container_child_get ((GtkContainer*) self, (GtkWidget*) menubar, "shrink", &shrink, NULL, NULL);
				switch (matenu_menu_bar_box_get_pack_direction (self)) {
					case GTK_PACK_DIRECTION_LTR:
					{
						if (shrink) {
							ca.width = ((*a).width - non_shrink_a) / num_of_shrinks;
							if (ca.width < 0) {
								ca.width = 0;
							}
						} else {
							ca.width = cr.width;
						}
						ca.height = (*a).height;
						ca.x = x;
						ca.y = y;
						x = x + ca.width;
						break;
					}
					case GTK_PACK_DIRECTION_RTL:
					{
						if (shrink) {
							ca.width = ((*a).width - non_shrink_a) / num_of_shrinks;
							if (ca.width < 0) {
								ca.width = 0;
							}
						} else {
							ca.width = cr.width;
						}
						ca.x = rev_x - ca.width;
						ca.y = y;
						ca.height = (*a).height;
						rev_x = rev_x - ca.width;
						x = x + ca.width;
						break;
					}
					case GTK_PACK_DIRECTION_TTB:
					{
						ca.width = (*a).width;
						if (shrink) {
							ca.height = ((*a).height - non_shrink_a) / num_of_shrinks;
							if (ca.height < 0) {
								ca.height = 0;
							}
						} else {
							ca.height = cr.height;
						}
						ca.x = x;
						ca.y = y;
						y = y + ca.height;
						break;
					}
					case GTK_PACK_DIRECTION_BTT:
					{
						ca.width = (*a).width;
						if (shrink) {
							ca.height = ((*a).height - non_shrink_a) / num_of_shrinks;
							if (ca.height < 0) {
								ca.height = 0;
							}
						} else {
							ca.height = cr.height;
						}
						ca.x = x;
						ca.y = rev_y - ca.height;
						rev_y = rev_y - ca.height;
						y = y + ca.height;
						break;
					}
				}
				gtk_widget_size_allocate ((GtkWidget*) menubar, (_tmp1_ = (GdkRectangle) ca, &_tmp1_));
			}
		}
	}
	GTK_WIDGET_CLASS (matenu_menu_bar_box_parent_class)->size_allocate ((GtkWidget*) GTK_CONTAINER (self), a);
}


static void matenu_menu_bar_box_real_get_child_property (GtkContainer* base, GtkWidget* child, guint id, GValue* value, GParamSpec* pspec) {
	MatenuMenuBarBox * self;
	self = (MatenuMenuBarBox*) base;
	g_return_if_fail (child != NULL);
	g_return_if_fail (pspec != NULL);
	switch (id) {
		case MATENU_MENU_BAR_BOX_PROP_EXPAND:
		{
			MatenuMenuBarBoxChildPropBag* prop;
			prop = g_hash_table_lookup (self->priv->props, child);
			g_value_set_boolean (value, (*prop).expand);
			break;
		}
		case MATENU_MENU_BAR_BOX_PROP_SHRINK:
		{
			MatenuMenuBarBoxChildPropBag* prop;
			prop = g_hash_table_lookup (self->priv->props, child);
			g_value_set_boolean (value, (*prop).shrink);
			break;
		}
	}
}


static void matenu_menu_bar_box_real_set_child_property (GtkContainer* base, GtkWidget* child, guint id, GValue* value, GParamSpec* pspec) {
	MatenuMenuBarBox * self;
	self = (MatenuMenuBarBox*) base;
	g_return_if_fail (child != NULL);
	g_return_if_fail (pspec != NULL);
	switch (id) {
		case MATENU_MENU_BAR_BOX_PROP_EXPAND:
		{
			gboolean expand;
			MatenuMenuBarBoxChildPropBag* prop;
			expand = g_value_get_boolean (value);
			prop = g_hash_table_lookup (self->priv->props, child);
			if ((*prop).expand != expand) {
				(*prop).expand = expand;
				gtk_widget_queue_resize ((GtkWidget*) self);
			}
			break;
		}
		case MATENU_MENU_BAR_BOX_PROP_SHRINK:
		{
			gboolean shrink;
			MatenuMenuBarBoxChildPropBag* prop;
			shrink = g_value_get_boolean (value);
			prop = g_hash_table_lookup (self->priv->props, child);
			if ((*prop).shrink != shrink) {
				(*prop).shrink = shrink;
				gtk_widget_queue_resize ((GtkWidget*) self);
			}
			break;
		}
	}
}


GtkPackDirection matenu_menu_bar_box_get_pack_direction (MatenuMenuBarBox* self) {
	GtkPackDirection result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_pack_direction;
	return result;
}


void matenu_menu_bar_box_set_pack_direction (MatenuMenuBarBox* self, GtkPackDirection value) {
	g_return_if_fail (self != NULL);
	{
		GList* menubar_collection;
		GList* menubar_it;
		menubar_collection = self->priv->children;
		for (menubar_it = menubar_collection; menubar_it != NULL; menubar_it = menubar_it->next) {
			MatenuMenuBar* menubar;
			menubar = (MatenuMenuBar*) menubar_it->data;
			{
				gtk_menu_bar_set_child_pack_direction ((GtkMenuBar*) menubar, value);
			}
		}
	}
	if (self->priv->_pack_direction == value) {
		return;
	}
	self->priv->_pack_direction = value;
	gtk_widget_queue_resize ((GtkWidget*) self);
	g_object_notify ((GObject *) self, "pack-direction");
}


GtkPackDirection matenu_menu_bar_box_get_child_pack_direction (MatenuMenuBarBox* self) {
	GtkPackDirection result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_child_pack_direction;
	return result;
}


void matenu_menu_bar_box_set_child_pack_direction (MatenuMenuBarBox* self, GtkPackDirection value) {
	g_return_if_fail (self != NULL);
	{
		GList* menubar_collection;
		GList* menubar_it;
		menubar_collection = self->priv->children;
		for (menubar_it = menubar_collection; menubar_it != NULL; menubar_it = menubar_it->next) {
			MatenuMenuBar* menubar;
			menubar = (MatenuMenuBar*) menubar_it->data;
			{
				gtk_menu_bar_set_pack_direction ((GtkMenuBar*) menubar, value);
			}
		}
	}
	if (self->priv->_child_pack_direction == value) {
		return;
	}
	self->priv->_child_pack_direction = value;
	gtk_widget_queue_resize ((GtkWidget*) self);
	g_object_notify ((GObject *) self, "child-pack-direction");
}


MatenuGravity matenu_menu_bar_box_get_gravity (MatenuMenuBarBox* self) {
	MatenuGravity result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_gravity;
	return result;
}


void matenu_menu_bar_box_set_gravity (MatenuMenuBarBox* self, MatenuGravity value) {
	g_return_if_fail (self != NULL);
	if (self->priv->_gravity == value) {
		return;
	}
	self->priv->_gravity = value;
	{
		GList* menubar_collection;
		GList* menubar_it;
		menubar_collection = self->priv->children;
		for (menubar_it = menubar_collection; menubar_it != NULL; menubar_it = menubar_it->next) {
			MatenuMenuBar* menubar;
			menubar = (MatenuMenuBar*) menubar_it->data;
			{
				matenu_menu_bar_set_gravity (menubar, value);
			}
		}
	}
	gtk_widget_queue_draw ((GtkWidget*) self);
	g_object_notify ((GObject *) self, "gravity");
}


void matenu_menu_bar_box_set_background (MatenuMenuBarBox* self, MatenuBackground* value) {
	MatenuBackground* bg;
	g_return_if_fail (self != NULL);
	bg = matenu_background_clone (value);
	{
		GList* menubar_collection;
		GList* menubar_it;
		menubar_collection = self->priv->children;
		for (menubar_it = menubar_collection; menubar_it != NULL; menubar_it = menubar_it->next) {
			MatenuMenuBar* menubar;
			menubar = (MatenuMenuBar*) menubar_it->data;
			{
				bg->offset_x = ((GtkWidget*) menubar)->allocation.x - ((GtkWidget*) self)->allocation.x;
				bg->offset_y = ((GtkWidget*) menubar)->allocation.y - ((GtkWidget*) self)->allocation.y;
				matenu_menu_bar_set_background (menubar, bg);
			}
		}
	}
	_matenu_background_unref0 (bg);
	g_object_notify ((GObject *) self, "background");
}


static void _g_free_gdestroy_notify (void* data) {
	g_free (data);
}


static GObject * matenu_menu_bar_box_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MatenuMenuBarBox * self;
	parent_class = G_OBJECT_CLASS (matenu_menu_bar_box_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MATENU_MENU_BAR_BOX (obj);
	{
		GHashTable* _tmp0_;
		GTK_WIDGET_SET_FLAGS ((GtkWidget*) self, GTK_NO_WINDOW);
		self->priv->props = (_tmp0_ = g_hash_table_new_full (g_direct_hash, g_direct_equal, NULL, _g_free_gdestroy_notify), _g_hash_table_unref0 (self->priv->props), _tmp0_);
	}
	return obj;
}


static MatenuMenuBarBoxChildPropBag* matenu_menu_bar_box_child_prop_bag_dup (const MatenuMenuBarBoxChildPropBag* self) {
	MatenuMenuBarBoxChildPropBag* dup;
	dup = g_new0 (MatenuMenuBarBoxChildPropBag, 1);
	memcpy (dup, self, sizeof (MatenuMenuBarBoxChildPropBag));
	return dup;
}


static void matenu_menu_bar_box_child_prop_bag_free (MatenuMenuBarBoxChildPropBag* self) {
	g_free (self);
}


static GType matenu_menu_bar_box_child_prop_bag_get_type (void) {
	static volatile gsize matenu_menu_bar_box_child_prop_bag_type_id__volatile = 0;
	if (g_once_init_enter (&matenu_menu_bar_box_child_prop_bag_type_id__volatile)) {
		GType matenu_menu_bar_box_child_prop_bag_type_id;
		matenu_menu_bar_box_child_prop_bag_type_id = g_boxed_type_register_static ("MatenuMenuBarBoxChildPropBag", (GBoxedCopyFunc) matenu_menu_bar_box_child_prop_bag_dup, (GBoxedFreeFunc) matenu_menu_bar_box_child_prop_bag_free);
		g_once_init_leave (&matenu_menu_bar_box_child_prop_bag_type_id__volatile, matenu_menu_bar_box_child_prop_bag_type_id);
	}
	return matenu_menu_bar_box_child_prop_bag_type_id__volatile;
}


static void matenu_menu_bar_box_class_init (MatenuMenuBarBoxClass * klass) {
	matenu_menu_bar_box_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MatenuMenuBarBoxPrivate));
	GTK_CONTAINER_CLASS (klass)->forall = matenu_menu_bar_box_real_forall_internal;
	GTK_CONTAINER_CLASS (klass)->add = matenu_menu_bar_box_real_add;
	GTK_CONTAINER_CLASS (klass)->remove = matenu_menu_bar_box_real_remove;
	GTK_WIDGET_CLASS (klass)->size_request = matenu_menu_bar_box_real_size_request;
	GTK_WIDGET_CLASS (klass)->size_allocate = matenu_menu_bar_box_real_size_allocate;
	GTK_CONTAINER_CLASS (klass)->get_child_property = matenu_menu_bar_box_real_get_child_property;
	GTK_CONTAINER_CLASS (klass)->set_child_property = matenu_menu_bar_box_real_set_child_property;
	G_OBJECT_CLASS (klass)->get_property = matenu_menu_bar_box_get_property;
	G_OBJECT_CLASS (klass)->set_property = matenu_menu_bar_box_set_property;
	G_OBJECT_CLASS (klass)->constructor = matenu_menu_bar_box_constructor;
	G_OBJECT_CLASS (klass)->finalize = matenu_menu_bar_box_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_BAR_BOX_PACK_DIRECTION, g_param_spec_enum ("pack-direction", "pack-direction", "pack-direction", GTK_TYPE_PACK_DIRECTION, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_BAR_BOX_CHILD_PACK_DIRECTION, g_param_spec_enum ("child-pack-direction", "child-pack-direction", "child-pack-direction", GTK_TYPE_PACK_DIRECTION, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_BAR_BOX_GRAVITY, g_param_spec_enum ("gravity", "gravity", "gravity", MATENU_TYPE_GRAVITY, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_BAR_BOX_BACKGROUND, matenu_param_spec_background ("background", "background", "background", MATENU_TYPE_BACKGROUND, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE));
	{
		GParamSpecBoolean* _tmp1_;
		GParamSpecBoolean* _tmp2_;
		gtk_container_class_install_child_property (GTK_CONTAINER_CLASS (klass), (guint) MATENU_MENU_BAR_BOX_PROP_EXPAND, (GParamSpec*) (_tmp1_ = g_param_spec_boolean ("expand", "Expand", "the child will expand if set to true", FALSE, G_PARAM_READABLE | G_PARAM_WRITABLE)));
		_g_param_spec_unref0 (_tmp1_);
		gtk_container_class_install_child_property (GTK_CONTAINER_CLASS (klass), (guint) MATENU_MENU_BAR_BOX_PROP_SHRINK, (GParamSpec*) (_tmp2_ = g_param_spec_boolean ("shrink", "shrink", "the child will shrink if set to true", FALSE, G_PARAM_READABLE | G_PARAM_WRITABLE)));
		_g_param_spec_unref0 (_tmp2_);
	}
}


static void matenu_menu_bar_box_instance_init (MatenuMenuBarBox * self) {
	self->priv = MATENU_MENU_BAR_BOX_GET_PRIVATE (self);
}


static void matenu_menu_bar_box_finalize (GObject* obj) {
	MatenuMenuBarBox * self;
	self = MATENU_MENU_BAR_BOX (obj);
	_g_hash_table_unref0 (self->priv->props);
	_g_list_free0 (self->priv->children);
	self->priv->size_hints = (g_free (self->priv->size_hints), NULL);
	G_OBJECT_CLASS (matenu_menu_bar_box_parent_class)->finalize (obj);
}


GType matenu_menu_bar_box_get_type (void) {
	static volatile gsize matenu_menu_bar_box_type_id__volatile = 0;
	if (g_once_init_enter (&matenu_menu_bar_box_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MatenuMenuBarBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) matenu_menu_bar_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MatenuMenuBarBox), 0, (GInstanceInitFunc) matenu_menu_bar_box_instance_init, NULL };
		GType matenu_menu_bar_box_type_id;
		matenu_menu_bar_box_type_id = g_type_register_static (GTK_TYPE_CONTAINER, "MatenuMenuBarBox", &g_define_type_info, 0);
		g_once_init_leave (&matenu_menu_bar_box_type_id__volatile, matenu_menu_bar_box_type_id);
	}
	return matenu_menu_bar_box_type_id__volatile;
}


static void matenu_menu_bar_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MatenuMenuBarBox * self;
	self = MATENU_MENU_BAR_BOX (object);
	switch (property_id) {
		case MATENU_MENU_BAR_BOX_PACK_DIRECTION:
		g_value_set_enum (value, matenu_menu_bar_box_get_pack_direction (self));
		break;
		case MATENU_MENU_BAR_BOX_CHILD_PACK_DIRECTION:
		g_value_set_enum (value, matenu_menu_bar_box_get_child_pack_direction (self));
		break;
		case MATENU_MENU_BAR_BOX_GRAVITY:
		g_value_set_enum (value, matenu_menu_bar_box_get_gravity (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void matenu_menu_bar_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MatenuMenuBarBox * self;
	self = MATENU_MENU_BAR_BOX (object);
	switch (property_id) {
		case MATENU_MENU_BAR_BOX_PACK_DIRECTION:
		matenu_menu_bar_box_set_pack_direction (self, g_value_get_enum (value));
		break;
		case MATENU_MENU_BAR_BOX_CHILD_PACK_DIRECTION:
		matenu_menu_bar_box_set_child_pack_direction (self, g_value_get_enum (value));
		break;
		case MATENU_MENU_BAR_BOX_GRAVITY:
		matenu_menu_bar_box_set_gravity (self, g_value_get_enum (value));
		break;
		case MATENU_MENU_BAR_BOX_BACKGROUND:
		matenu_menu_bar_box_set_background (self, matenu_value_get_background (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




