/* menuitem.c generated by valac, the Vala compiler
 * generated from menuitem.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <pango/pango.h>
#include <gdk-pixbuf/gdk-pixdata.h>
#include <glib/gi18n-lib.h>


#define MATENU_TYPE_ITEM (matenu_item_get_type ())
#define MATENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_ITEM, MatenuItem))
#define MATENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_ITEM))
#define MATENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_ITEM, MatenuItemIface))

typedef struct _MatenuItem MatenuItem;
typedef struct _MatenuItemIface MatenuItemIface;

#define MATENU_TYPE_SHELL (matenu_shell_get_type ())
#define MATENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_SHELL, MatenuShell))
#define MATENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_SHELL))
#define MATENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_SHELL, MatenuShellIface))

typedef struct _MatenuShell MatenuShell;
typedef struct _MatenuShellIface MatenuShellIface;

#define MATENU_TYPE_ITEM_TYPE (matenu_item_type_get_type ())

#define MATENU_TYPE_ITEM_STATE (matenu_item_state_get_type ())

#define MATENU_TYPE_MENU_ITEM (matenu_menu_item_get_type ())
#define MATENU_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_ITEM, MatenuMenuItem))
#define MATENU_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_ITEM, MatenuMenuItemClass))
#define MATENU_IS_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_ITEM))
#define MATENU_IS_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_ITEM))
#define MATENU_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_ITEM, MatenuMenuItemClass))

typedef struct _MatenuMenuItem MatenuMenuItem;
typedef struct _MatenuMenuItemClass MatenuMenuItemClass;
typedef struct _MatenuMenuItemPrivate MatenuMenuItemPrivate;

#define MATENU_TYPE_MENU (matenu_menu_get_type ())
#define MATENU_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU, MatenuMenu))
#define MATENU_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU, MatenuMenuClass))
#define MATENU_IS_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU))
#define MATENU_IS_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU))
#define MATENU_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU, MatenuMenuClass))

typedef struct _MatenuMenu MatenuMenu;
typedef struct _MatenuMenuClass MatenuMenuClass;

#define MATENU_TYPE_GRAVITY (matenu_gravity_get_type ())

#define MATENU_TYPE_MENU_LABEL (matenu_menu_label_get_type ())
#define MATENU_MENU_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_LABEL, MatenuMenuLabel))
#define MATENU_MENU_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_LABEL, MatenuMenuLabelClass))
#define MATENU_IS_MENU_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_LABEL))
#define MATENU_IS_MENU_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_LABEL))
#define MATENU_MENU_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_LABEL, MatenuMenuLabelClass))

typedef struct _MatenuMenuLabel MatenuMenuLabel;
typedef struct _MatenuMenuLabelClass MatenuMenuLabelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define MATENU_TYPE_MENU_BAR (matenu_menu_bar_get_type ())
#define MATENU_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_BAR, MatenuMenuBar))
#define MATENU_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_BAR, MatenuMenuBarClass))
#define MATENU_IS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_BAR))
#define MATENU_IS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_BAR))
#define MATENU_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_BAR, MatenuMenuBarClass))

typedef struct _MatenuMenuBar MatenuMenuBar;
typedef struct _MatenuMenuBarClass MatenuMenuBarClass;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _pango_font_description_free0(var) ((var == NULL) ? NULL : (var = (pango_font_description_free (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

#define MATENU_TYPE_ADAPTER (matenu_adapter_get_type ())
#define MATENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_ADAPTER, MatenuAdapter))
#define MATENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_ADAPTER, MatenuAdapterClass))
#define MATENU_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_ADAPTER))
#define MATENU_IS_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_ADAPTER))
#define MATENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_ADAPTER, MatenuAdapterClass))

typedef struct _MatenuAdapter MatenuAdapter;
typedef struct _MatenuAdapterClass MatenuAdapterClass;
#define _g_param_spec_unref0(var) ((var == NULL) ? NULL : (var = (g_param_spec_unref (var), NULL)))

struct _MatenuShellIface {
	GTypeInterface parent_iface;
	MatenuItem* (*get_item) (MatenuShell* self, gint position);
	MatenuItem* (*get_item_by_id) (MatenuShell* self, const char* id);
	gint (*get_item_position) (MatenuShell* self, MatenuItem* item);
	MatenuItem* (*get_owner) (MatenuShell* self);
	gint (*get_length) (MatenuShell* self);
	void (*set_length) (MatenuShell* self, gint value);
};

typedef enum  {
	MATENU_ITEM_TYPE_NORMAL = 0,
	MATENU_ITEM_TYPE_CHECK = 1,
	MATENU_ITEM_TYPE_RADIO = 2,
	MATENU_ITEM_TYPE_IMAGE = 3,
	MATENU_ITEM_TYPE_SEPARATOR = 4,
	MATENU_ITEM_TYPE_ARROW = 5,
	MATENU_ITEM_TYPE_ICON = 6
} MatenuItemType;

typedef enum  {
	MATENU_ITEM_STATE_UNTOGGLED = 0,
	MATENU_ITEM_STATE_TOGGLED = 1,
	MATENU_ITEM_STATE_TRISTATE = 2
} MatenuItemState;

struct _MatenuItemIface {
	GTypeInterface parent_iface;
	MatenuShell* (*get_shell) (MatenuItem* self);
	MatenuShell* (*get_sub_shell) (MatenuItem* self);
	gboolean (*get_has_sub_shell) (MatenuItem* self);
	void (*set_has_sub_shell) (MatenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (MatenuItem* self);
	void (*set_client_side_sub_shell) (MatenuItem* self, gboolean value);
	const char* (*get_item_id) (MatenuItem* self);
	void (*set_item_id) (MatenuItem* self, const char* value);
	MatenuItemType (*get_item_type) (MatenuItem* self);
	void (*set_item_type) (MatenuItem* self, MatenuItemType value);
	gboolean (*get_item_use_underline) (MatenuItem* self);
	void (*set_item_use_underline) (MatenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (MatenuItem* self);
	void (*set_item_sensitive) (MatenuItem* self, gboolean value);
	gboolean (*get_item_visible) (MatenuItem* self);
	void (*set_item_visible) (MatenuItem* self, gboolean value);
	MatenuItemState (*get_item_state) (MatenuItem* self);
	void (*set_item_state) (MatenuItem* self, MatenuItemState value);
	const char* (*get_item_label) (MatenuItem* self);
	void (*set_item_label) (MatenuItem* self, const char* value);
	const char* (*get_item_icon) (MatenuItem* self);
	void (*set_item_icon) (MatenuItem* self, const char* value);
	const char* (*get_item_accel_text) (MatenuItem* self);
	void (*set_item_accel_text) (MatenuItem* self, const char* value);
	const char* (*get_item_font) (MatenuItem* self);
	void (*set_item_font) (MatenuItem* self, const char* value);
};

struct _MatenuMenuItem {
	GtkMenuItem parent_instance;
	MatenuMenuItemPrivate * priv;
	MatenuMenu* _submenu_cache;
};

struct _MatenuMenuItemClass {
	GtkMenuItemClass parent_class;
};

typedef enum  {
	MATENU_GRAVITY_DOWN = 0,
	MATENU_GRAVITY_UP = 1,
	MATENU_GRAVITY_LEFT = 2,
	MATENU_GRAVITY_RIGHT = 3
} MatenuGravity;

struct _MatenuMenuItemPrivate {
	gint _max_width_chars;
	gboolean _has_sub_shell;
	gboolean _client_side_sub_shell;
	gboolean _item_visible;
	gboolean _show_underline;
	gboolean disposed;
	gboolean _truncated;
	char* _font;
	char* _label;
	char* _icon;
	char* _accel_text;
	char* _id;
	MatenuGravity _gravity;
	MatenuItemType _item_type;
	MatenuItemState _item_state;
	gboolean _use_underline;
	GtkImage* _cached_image_widget;
	GtkArrow* _cached_arrow_widget;
	MatenuMenuLabel* _cached_label_widget;
	GtkImage* _image_widget;
	GtkImage* _icon_widget;
};


static gint matenu_menu_item_icon_width;
static gint matenu_menu_item_icon_width = 0;
static gint matenu_menu_item_icon_height;
static gint matenu_menu_item_icon_height = 0;
static gpointer matenu_menu_item_parent_class = NULL;
static MatenuItemIface* matenu_menu_item_matenu_item_parent_iface = NULL;

GType matenu_shell_get_type (void) G_GNUC_CONST;
GType matenu_item_type_get_type (void) G_GNUC_CONST;
GType matenu_item_state_get_type (void) G_GNUC_CONST;
GType matenu_item_get_type (void) G_GNUC_CONST;
GType matenu_menu_item_get_type (void) G_GNUC_CONST;
GType matenu_menu_get_type (void) G_GNUC_CONST;
GType matenu_gravity_get_type (void) G_GNUC_CONST;
GType matenu_menu_label_get_type (void) G_GNUC_CONST;
#define MATENU_MENU_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MATENU_TYPE_MENU_ITEM, MatenuMenuItemPrivate))
enum  {
	MATENU_MENU_ITEM_DUMMY_PROPERTY,
	MATENU_MENU_ITEM_MAX_WIDTH_CHARS,
	MATENU_MENU_ITEM_SHELL,
	MATENU_MENU_ITEM_SUB_SHELL,
	MATENU_MENU_ITEM_HAS_SUB_SHELL,
	MATENU_MENU_ITEM_CLIENT_SIDE_SUB_SHELL,
	MATENU_MENU_ITEM_ITEM_ID,
	MATENU_MENU_ITEM_ITEM_LABEL,
	MATENU_MENU_ITEM_ITEM_ICON,
	MATENU_MENU_ITEM_ITEM_ACCEL_TEXT,
	MATENU_MENU_ITEM_ITEM_FONT,
	MATENU_MENU_ITEM_ITEM_TYPE,
	MATENU_MENU_ITEM_ITEM_USE_UNDERLINE,
	MATENU_MENU_ITEM_ITEM_STATE,
	MATENU_MENU_ITEM_ITEM_VISIBLE,
	MATENU_MENU_ITEM_ITEM_SENSITIVE,
	MATENU_MENU_ITEM_GRAVITY,
	MATENU_MENU_ITEM_SHOW_UNDERLINE,
	MATENU_MENU_ITEM_TRUNCATED,
	MATENU_MENU_ITEM_IMAGE
};
MatenuMenu* matenu_menu_new (void);
MatenuMenu* matenu_menu_construct (GType object_type);
MatenuMenuItem* matenu_menu_item_new (void);
MatenuMenuItem* matenu_menu_item_construct (GType object_type);
static void matenu_menu_item_real_dispose (GObject* base);
static void matenu_menu_item_maybe_connect_cached_submenu (MatenuMenuItem* self);
static gboolean matenu_menu_item_get__show_image (MatenuMenuItem* self);
GtkImage* matenu_menu_item_get_image (MatenuMenuItem* self);
static GtkPackDirection matenu_menu_item_get_pack_direction (MatenuMenuItem* self);
static void matenu_menu_item_real_toggle_size_request (GtkMenuItem* base, void* requisition);
GtkShadowType matenu_menu_item_item_state_to_shadow_type (MatenuItemState state);
static gboolean matenu_menu_item_real_expose_event (GtkWidget* base, GdkEventExpose* event);
static void matenu_menu_item_real_forall_internal (GtkContainer* base, gboolean include_internals, GtkCallback callback, void* callback_target);
MatenuShell* matenu_item_get_topmost_shell (MatenuItem* self);
GType matenu_menu_bar_get_type (void) G_GNUC_CONST;
void matenu_menu_bar_emit_activate (MatenuMenuBar* self, MatenuMenuItem* item);
char* matenu_item_get_item_path (MatenuItem* self);
static void matenu_menu_item_real_activate (GtkMenuItem* base);
void matenu_menu_bar_emit_select (MatenuMenuBar* self, MatenuMenuItem* item);
static void matenu_menu_item_real_select (GtkItem* base);
void matenu_menu_bar_emit_deselect (MatenuMenuBar* self, MatenuMenuItem* item);
static void matenu_menu_item_real_deselect (GtkItem* base);
static void matenu_menu_item_update_show_image (MatenuMenuItem* self);
static void matenu_menu_item_show_image_notify_r (GtkWidget* widget, GtkSettings* settings);
static void matenu_menu_item_show_image_notify (MatenuMenuItem* self, GtkSettings* settings, GParamSpec* pspec);
static void _matenu_menu_item_show_image_notify_g_object_notify (GtkSettings* _sender, GParamSpec* pspec, gpointer self);
static void matenu_menu_item_real_screen_changed (GtkWidget* base, GdkScreen* previous_screen);
static void matenu_menu_item_real_size_request (GtkWidget* base, GtkRequisition* req);
static void matenu_menu_item_real_size_allocate (GtkWidget* base, GdkRectangle* a);
static void matenu_menu_item_update_font (MatenuMenuItem* self);
static char* matenu_menu_item_remove_underlines (MatenuMenuItem* self, const char* s);
gboolean matenu_item_type_has_label (MatenuItemType type);
static MatenuMenuLabel* matenu_menu_item_get_label_widget (MatenuMenuItem* self);
void matenu_menu_label_set_label (MatenuMenuLabel* self, const char* value);
void matenu_menu_label_set_accel (MatenuMenuLabel* self, const char* value);
void matenu_menu_label_set_max_width_chars (MatenuMenuLabel* self, gint value);
static void matenu_menu_item_update_label_text (MatenuMenuItem* self);
void matenu_menu_label_set_use_underline (MatenuMenuLabel* self, gboolean value);
static void matenu_menu_item_update_label_underline (MatenuMenuItem* self);
static void matenu_menu_item_update_image (MatenuMenuItem* self);
static void matenu_menu_item_real_parent_set (GtkWidget* base, GtkWidget* old_parent);
MatenuGravity matenu_menu_item_get_gravity (MatenuMenuItem* self);
void matenu_menu_label_set_gravity (MatenuMenuLabel* self, MatenuGravity value);
static void matenu_menu_item_create_labels (MatenuMenuItem* self);
static void matenu_menu_item_remove_child (MatenuMenuItem* self);
static void matenu_menu_item_update_arrow_type (MatenuMenuItem* self);
static void matenu_menu_item_create_arrow (MatenuMenuItem* self);
GtkArrowType matenu_gravity_to_arrow_type (MatenuGravity g);
gint matenu_menu_item_get_max_width_chars (MatenuMenuItem* self);
void matenu_menu_item_set_max_width_chars (MatenuMenuItem* self, gint value);
GType matenu_adapter_get_type (void) G_GNUC_CONST;
MatenuAdapter* matenu_adapter_get_adapter (GtkMenuShell* gtk_shell);
void matenu_menu_item_set_gravity (MatenuMenuItem* self, MatenuGravity value);
gboolean matenu_menu_item_get_show_underline (MatenuMenuItem* self);
void matenu_menu_item_set_show_underline (MatenuMenuItem* self, gboolean value);
gboolean matenu_menu_item_get_truncated (MatenuMenuItem* self);
void matenu_menu_item_set_truncated (MatenuMenuItem* self, gboolean value);
MatenuMenuLabel* matenu_menu_label_new (void);
MatenuMenuLabel* matenu_menu_label_construct (GType object_type);
static GObject * matenu_menu_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void matenu_menu_item_finalize (GObject* obj);
MatenuShell* matenu_item_get_shell (MatenuItem* self);
MatenuShell* matenu_item_get_sub_shell (MatenuItem* self);
gboolean matenu_item_get_has_sub_shell (MatenuItem* self);
gboolean matenu_item_get_client_side_sub_shell (MatenuItem* self);
const char* matenu_item_get_item_id (MatenuItem* self);
const char* matenu_item_get_item_label (MatenuItem* self);
const char* matenu_item_get_item_icon (MatenuItem* self);
const char* matenu_item_get_item_accel_text (MatenuItem* self);
const char* matenu_item_get_item_font (MatenuItem* self);
MatenuItemType matenu_item_get_item_type (MatenuItem* self);
gboolean matenu_item_get_item_use_underline (MatenuItem* self);
MatenuItemState matenu_item_get_item_state (MatenuItem* self);
gboolean matenu_item_get_item_visible (MatenuItem* self);
gboolean matenu_item_get_item_sensitive (MatenuItem* self);
static void matenu_menu_item_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
void matenu_item_set_has_sub_shell (MatenuItem* self, gboolean value);
void matenu_item_set_client_side_sub_shell (MatenuItem* self, gboolean value);
void matenu_item_set_item_id (MatenuItem* self, const char* value);
void matenu_item_set_item_label (MatenuItem* self, const char* value);
void matenu_item_set_item_icon (MatenuItem* self, const char* value);
void matenu_item_set_item_accel_text (MatenuItem* self, const char* value);
void matenu_item_set_item_font (MatenuItem* self, const char* value);
void matenu_item_set_item_type (MatenuItem* self, MatenuItemType value);
void matenu_item_set_item_use_underline (MatenuItem* self, gboolean value);
void matenu_item_set_item_state (MatenuItem* self, MatenuItemState value);
void matenu_item_set_item_visible (MatenuItem* self, gboolean value);
void matenu_item_set_item_sensitive (MatenuItem* self, gboolean value);
static void matenu_menu_item_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static int _vala_strcmp0 (const char * str1, const char * str2);



MatenuMenuItem* matenu_menu_item_construct (GType object_type) {
	MatenuMenuItem * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


MatenuMenuItem* matenu_menu_item_new (void) {
	return matenu_menu_item_construct (MATENU_TYPE_MENU_ITEM);
}


static void matenu_menu_item_real_dispose (GObject* base) {
	MatenuMenuItem * self;
	self = (MatenuMenuItem*) base;
	if (!self->priv->disposed) {
		self->priv->disposed = TRUE;
		if (self->priv->_image_widget != NULL) {
			GtkImage* _tmp0_;
			gtk_widget_unparent ((GtkWidget*) self->priv->_image_widget);
			self->priv->_image_widget = (_tmp0_ = NULL, _g_object_unref0 (self->priv->_image_widget), _tmp0_);
		}
		gtk_object_destroy ((GtkObject*) self->_submenu_cache);
	}
	G_OBJECT_CLASS (matenu_menu_item_parent_class)->dispose ((GObject*) GTK_MENU_ITEM (self));
}


static void matenu_menu_item_maybe_connect_cached_submenu (MatenuMenuItem* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	if (self->priv->_has_sub_shell) {
		_tmp0_ = !self->priv->_client_side_sub_shell;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		if (gtk_menu_item_get_submenu ((GtkMenuItem*) self) != GTK_MENU (self->_submenu_cache)) {
			gtk_menu_item_set_submenu ((GtkMenuItem*) self, (GtkMenu*) self->_submenu_cache);
		}
	} else {
		if (gtk_menu_item_get_submenu ((GtkMenuItem*) self) != NULL) {
			gtk_menu_popdown (gtk_menu_item_get_submenu ((GtkMenuItem*) self));
		}
		gtk_menu_item_set_submenu ((GtkMenuItem*) self, NULL);
	}
}


static void matenu_menu_item_real_toggle_size_request (GtkMenuItem* base, void* requisition) {
	MatenuMenuItem * self;
	gint toggle_spacing;
	gint indicator_size;
	self = (MatenuMenuItem*) base;
	toggle_spacing = 0;
	indicator_size = 0;
	gtk_widget_style_get ((GtkWidget*) self, "toggle-spacing", &toggle_spacing, "indicator-size", &indicator_size, NULL, NULL);
	switch (self->priv->_item_type) {
		case MATENU_ITEM_TYPE_CHECK:
		case MATENU_ITEM_TYPE_RADIO:
		{
			*((gint*) requisition) = indicator_size + toggle_spacing;
			break;
		}
		case MATENU_ITEM_TYPE_IMAGE:
		{
			gboolean _tmp0_ = FALSE;
			if (!matenu_menu_item_get__show_image (self)) {
				*((gint*) requisition) = 0;
				break;
			}
			if (matenu_menu_item_get_image (self) != NULL) {
				_tmp0_ = self->priv->_icon != NULL;
			} else {
				_tmp0_ = FALSE;
			}
			if (_tmp0_) {
				GtkRequisition req = {0};
				gboolean _tmp1_ = FALSE;
				gboolean _tmp2_ = FALSE;
				gtk_widget_size_request ((GtkWidget*) matenu_menu_item_get_image (self), &req);
				if (matenu_menu_item_get_pack_direction (self) == GTK_PACK_DIRECTION_LTR) {
					_tmp1_ = TRUE;
				} else {
					_tmp1_ = matenu_menu_item_get_pack_direction (self) == GTK_PACK_DIRECTION_RTL;
				}
				if (_tmp1_) {
					*((gint*) requisition) = req.width + toggle_spacing;
				}
				if (matenu_menu_item_get_pack_direction (self) == GTK_PACK_DIRECTION_TTB) {
					_tmp2_ = TRUE;
				} else {
					_tmp2_ = matenu_menu_item_get_pack_direction (self) == GTK_PACK_DIRECTION_BTT;
				}
				if (_tmp2_) {
					*((gint*) requisition) = req.height + toggle_spacing;
				}
			} else {
				*((gint*) requisition) = 0;
			}
			break;
		}
		default:
		{
			*((gint*) requisition) = 0;
			break;
		}
	}
}


static gboolean matenu_menu_item_real_expose_event (GtkWidget* base, GdkEventExpose* event) {
	MatenuMenuItem * self;
	gboolean result = FALSE;
	gint toggle_spacing;
	gint indicator_size;
	gint horizontal_padding;
	GtkShadowType shadow_type;
	gint x;
	gint y;
	gint xoffset;
	gint yoffset;
	gint spacing;
	self = (MatenuMenuItem*) base;
	GTK_WIDGET_CLASS (matenu_menu_item_parent_class)->expose_event ((GtkWidget*) GTK_MENU_ITEM (self), event);
	toggle_spacing = 0;
	indicator_size = 0;
	horizontal_padding = 0;
	gtk_widget_style_get ((GtkWidget*) self, "toggle-spacing", &toggle_spacing, "indicator-size", &indicator_size, "horizontal-padding", &horizontal_padding, NULL, NULL);
	shadow_type = matenu_menu_item_item_state_to_shadow_type (self->priv->_item_state);
	x = 0;
	y = 0;
	xoffset = (((GtkMenuItem*) self)->toggle_size - indicator_size) / 2;
	yoffset = (((GtkWidget*) self)->allocation.height - indicator_size) / 2;
	spacing = toggle_spacing / 2;
	switch (gtk_widget_get_direction ((GtkWidget*) self)) {
		case GTK_TEXT_DIR_LTR:
		{
			x = (((GtkWidget*) self)->allocation.x + xoffset) + spacing;
			y = ((GtkWidget*) self)->allocation.y + yoffset;
			break;
		}
		case GTK_TEXT_DIR_RTL:
		{
			x = (((((GtkWidget*) self)->allocation.x + ((GtkWidget*) self)->allocation.width) - ((GtkMenuItem*) self)->toggle_size) - xoffset) - spacing;
			y = ((GtkWidget*) self)->allocation.y + yoffset;
			break;
		}
	}
	switch (self->priv->_item_type) {
		case MATENU_ITEM_TYPE_CHECK:
		{
			gtk_paint_check (gtk_widget_get_style ((GtkWidget*) self), ((GtkWidget*) self)->window, (GtkStateType) ((GtkWidget*) self)->state, shadow_type, &(*event).area, (GtkWidget*) self, "check", x, y, indicator_size, indicator_size);
			break;
		}
		case MATENU_ITEM_TYPE_RADIO:
		{
			gtk_paint_option (gtk_widget_get_style ((GtkWidget*) self), ((GtkWidget*) self)->window, (GtkStateType) ((GtkWidget*) self)->state, shadow_type, &(*event).area, (GtkWidget*) self, "option", x, y, indicator_size, indicator_size);
			break;
		}
	}
	result = FALSE;
	return result;
}


static void matenu_menu_item_real_forall_internal (GtkContainer* base, gboolean include_internals, GtkCallback callback, void* callback_target) {
	MatenuMenuItem * self;
	self = (MatenuMenuItem*) base;
	if (include_internals) {
		gboolean _tmp0_ = FALSE;
		if (self->priv->_item_type == MATENU_ITEM_TYPE_IMAGE) {
			_tmp0_ = self->priv->_image_widget != NULL;
		} else {
			_tmp0_ = FALSE;
		}
		if (_tmp0_) {
			callback ((GtkWidget*) self->priv->_image_widget, callback_target);
		}
	}
	GTK_CONTAINER_CLASS (matenu_menu_item_parent_class)->forall ((GtkContainer*) GTK_MENU_ITEM (self), include_internals, callback, callback_target);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void matenu_menu_item_real_activate (GtkMenuItem* base) {
	MatenuMenuItem * self;
	self = (MatenuMenuItem*) base;
	if (MATENU_IS_MENU_BAR (matenu_item_get_topmost_shell ((MatenuItem*) self))) {
		MatenuShell* _tmp0_;
		MatenuMenuBar* menubar;
		menubar = _g_object_ref0 ((_tmp0_ = matenu_item_get_topmost_shell ((MatenuItem*) self), MATENU_IS_MENU_BAR (_tmp0_) ? ((MatenuMenuBar*) _tmp0_) : NULL));
		matenu_menu_bar_emit_activate (menubar, self);
		_g_object_unref0 (menubar);
	} else {
		char* _tmp1_;
		g_debug ("menuitem.vala:504: activate %s, %p", _tmp1_ = matenu_item_get_item_path ((MatenuItem*) self), matenu_item_get_topmost_shell ((MatenuItem*) self));
		_g_free0 (_tmp1_);
		g_signal_emit_by_name (matenu_item_get_topmost_shell ((MatenuItem*) self), "activate", (MatenuItem*) self);
	}
}


static void matenu_menu_item_real_select (GtkItem* base) {
	MatenuMenuItem * self;
	self = (MatenuMenuItem*) base;
	if (MATENU_IS_MENU_BAR (matenu_item_get_topmost_shell ((MatenuItem*) self))) {
		MatenuShell* _tmp0_;
		MatenuMenuBar* menubar;
		menubar = _g_object_ref0 ((_tmp0_ = matenu_item_get_topmost_shell ((MatenuItem*) self), MATENU_IS_MENU_BAR (_tmp0_) ? ((MatenuMenuBar*) _tmp0_) : NULL));
		matenu_menu_bar_emit_select (menubar, self);
		_g_object_unref0 (menubar);
	} else {
		g_signal_emit_by_name (matenu_item_get_topmost_shell ((MatenuItem*) self), "select", (MatenuItem*) self);
	}
	GTK_ITEM_CLASS (matenu_menu_item_parent_class)->select ((GtkItem*) GTK_MENU_ITEM (self));
}


static void matenu_menu_item_real_deselect (GtkItem* base) {
	MatenuMenuItem * self;
	self = (MatenuMenuItem*) base;
	if (MATENU_IS_MENU_BAR (matenu_item_get_topmost_shell ((MatenuItem*) self))) {
		MatenuShell* _tmp0_;
		MatenuMenuBar* menubar;
		menubar = _g_object_ref0 ((_tmp0_ = matenu_item_get_topmost_shell ((MatenuItem*) self), MATENU_IS_MENU_BAR (_tmp0_) ? ((MatenuMenuBar*) _tmp0_) : NULL));
		matenu_menu_bar_emit_deselect (menubar, self);
		_g_object_unref0 (menubar);
	} else {
		g_signal_emit_by_name (matenu_item_get_topmost_shell ((MatenuItem*) self), "deselect", (MatenuItem*) self);
	}
	GTK_ITEM_CLASS (matenu_menu_item_parent_class)->deselect ((GtkItem*) GTK_MENU_ITEM (self));
}


static void matenu_menu_item_update_show_image (MatenuMenuItem* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->_image_widget != NULL) {
		gtk_widget_set_visible ((GtkWidget*) self->priv->_image_widget, matenu_menu_item_get__show_image (self));
	}
	gtk_widget_queue_resize ((GtkWidget*) self);
}


static void matenu_menu_item_show_image_notify_r (GtkWidget* widget, GtkSettings* settings) {
	g_return_if_fail (widget != NULL);
	g_return_if_fail (settings != NULL);
	if (MATENU_IS_MENU_ITEM (widget)) {
		GtkWidget* _tmp0_;
		MatenuMenuItem* item;
		item = _g_object_ref0 ((_tmp0_ = widget, MATENU_IS_MENU_ITEM (_tmp0_) ? ((MatenuMenuItem*) _tmp0_) : NULL));
		matenu_menu_item_update_show_image (item);
		_g_object_unref0 (item);
	} else {
		if (GTK_IS_CONTAINER (widget)) {
			GtkWidget* _tmp1_;
			GList* children;
			children = gtk_container_get_children ((_tmp1_ = widget, GTK_IS_CONTAINER (_tmp1_) ? ((GtkContainer*) _tmp1_) : NULL));
			{
				GList* child_collection;
				GList* child_it;
				child_collection = children;
				for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
					GtkWidget* child;
					child = _g_object_ref0 ((GtkWidget*) child_it->data);
					{
						matenu_menu_item_show_image_notify_r (child, settings);
						_g_object_unref0 (child);
					}
				}
			}
			_g_list_free0 (children);
		}
	}
}


static void matenu_menu_item_show_image_notify (MatenuMenuItem* self, GtkSettings* settings, GParamSpec* pspec) {
	GList* toplevels;
	g_return_if_fail (self != NULL);
	g_return_if_fail (settings != NULL);
	g_return_if_fail (pspec != NULL);
	toplevels = gtk_window_list_toplevels ();
	{
		GList* c_collection;
		GList* c_it;
		c_collection = toplevels;
		for (c_it = c_collection; c_it != NULL; c_it = c_it->next) {
			GtkContainer* c;
			c = _g_object_ref0 ((GtkContainer*) ((GtkWindow*) c_it->data));
			{
				matenu_menu_item_show_image_notify_r ((GtkWidget*) c, settings);
				_g_object_unref0 (c);
			}
		}
	}
	_g_list_free0 (toplevels);
}


static void _matenu_menu_item_show_image_notify_g_object_notify (GtkSettings* _sender, GParamSpec* pspec, gpointer self) {
	matenu_menu_item_show_image_notify (self, _sender, pspec);
}


static void matenu_menu_item_real_screen_changed (GtkWidget* base, GdkScreen* previous_screen) {
	MatenuMenuItem * self;
	GtkSettings* settings;
	self = (MatenuMenuItem*) base;
	if (!gtk_widget_has_screen ((GtkWidget*) self)) {
		return;
	}
	settings = _g_object_ref0 (gtk_widget_get_settings ((GtkWidget*) self));
	if (((GtkSettings*) g_object_get_data ((GObject*) settings, "matenu-menu-item-connection")) == NULL) {
		g_signal_connect_object ((GObject*) settings, "notify::gtk-menu-images", (GCallback) _matenu_menu_item_show_image_notify_g_object_notify, self, 0);
		g_object_set_data_full ((GObject*) settings, "matenu-menu-item-connection", _g_object_ref0 (settings), g_object_unref);
	}
	matenu_menu_item_update_show_image (self);
	_g_object_unref0 (settings);
}


static void matenu_menu_item_real_size_request (GtkWidget* base, GtkRequisition* req) {
	MatenuMenuItem * self;
	self = (MatenuMenuItem*) base;
	if (self->priv->_item_type == MATENU_ITEM_TYPE_IMAGE) {
		GtkRequisition image_req = {0};
		gtk_widget_size_request ((GtkWidget*) self->priv->_image_widget, &image_req);
	}
	if (self->priv->_item_type == MATENU_ITEM_TYPE_ICON) {
		gint horizontal_padding;
		horizontal_padding = 0;
		gtk_widget_style_get ((GtkWidget*) self, "horizontal-padding", &horizontal_padding, NULL, NULL);
		gtk_widget_size_request ((GtkWidget*) self->priv->_icon_widget, req);
		(*req).width = (*req).width + ((((gint) gtk_container_get_border_width ((GtkContainer*) self)) * 2) + (horizontal_padding * 2));
		(*req).height = (*req).height + (((gint) gtk_container_get_border_width ((GtkContainer*) self)) * 2);
	} else {
		GTK_WIDGET_CLASS (matenu_menu_item_parent_class)->size_request ((GtkWidget*) GTK_MENU_ITEM (self), req);
	}
}


static void matenu_menu_item_real_size_allocate (GtkWidget* base, GdkRectangle* a) {
	MatenuMenuItem * self;
	GdkRectangle _tmp0_ = {0};
	GdkRectangle ca;
	self = (MatenuMenuItem*) base;
	ca = (_tmp0_.x = 0, _tmp0_.y = 0, _tmp0_.width = 0, _tmp0_.height = 0, _tmp0_);
	if (self->priv->_item_type == MATENU_ITEM_TYPE_ICON) {
		gint horizontal_padding;
		horizontal_padding = 0;
		gtk_widget_style_get ((GtkWidget*) self, "horizontal-padding", &horizontal_padding, NULL, NULL);
		ca.x = ((*a).x + ((gint) gtk_container_get_border_width ((GtkContainer*) self))) + horizontal_padding;
		ca.y = (*a).y + ((gint) gtk_container_get_border_width ((GtkContainer*) self));
		ca.width = ((*a).width - (((gint) gtk_container_get_border_width ((GtkContainer*) self)) * 2)) - horizontal_padding;
		ca.height = (*a).height - (((gint) gtk_container_get_border_width ((GtkContainer*) self)) * 2);
		gtk_widget_size_allocate ((GtkWidget*) self->priv->_icon_widget, &ca);
		if ((GTK_WIDGET_FLAGS ((GtkWidget*) self) & GTK_REALIZED) != 0) {
			gdk_window_move_resize (((GtkMenuItem*) self)->event_window, ((GtkWidget*) self)->allocation.x, ((GtkWidget*) self)->allocation.y, ((GtkWidget*) self)->allocation.width, ((GtkWidget*) self)->allocation.height);
		}
		((GtkWidget*) self)->allocation = (GtkAllocation) (*a);
	} else {
		GTK_WIDGET_CLASS (matenu_menu_item_parent_class)->size_allocate ((GtkWidget*) GTK_MENU_ITEM (self), a);
	}
	if (self->priv->_item_type == MATENU_ITEM_TYPE_IMAGE) {
		gint toggle_spacing;
		GtkRequisition icon_req = {0};
		toggle_spacing = 0;
		gtk_widget_get_child_requisition ((GtkWidget*) self->priv->_image_widget, &icon_req);
		gtk_widget_style_get ((GtkWidget*) self, "toggle-spacing", &toggle_spacing, NULL, NULL);
		ca.width = icon_req.width;
		ca.height = icon_req.height;
		switch (matenu_menu_item_get_pack_direction (self)) {
			case GTK_PACK_DIRECTION_LTR:
			case GTK_PACK_DIRECTION_RTL:
			{
				gint xoffset;
				gint yoffset;
				gboolean _tmp1_ = FALSE;
				xoffset = ((((GtkMenuItem*) self)->toggle_size - icon_req.width) + toggle_spacing) / 2;
				yoffset = ((*a).height - icon_req.height) / 2;
				ca.y = (*a).y + yoffset;
				if (gtk_widget_get_direction ((GtkWidget*) self) == GTK_TEXT_DIR_LTR) {
					_tmp1_ = matenu_menu_item_get_pack_direction (self) == GTK_PACK_DIRECTION_LTR;
				} else {
					_tmp1_ = FALSE;
				}
				if (_tmp1_) {
					ca.x = (*a).x + xoffset;
				} else {
					ca.x = (((*a).x + (*a).width) - ca.width) - xoffset;
				}
				break;
			}
			case GTK_PACK_DIRECTION_TTB:
			case GTK_PACK_DIRECTION_BTT:
			{
				gint yoffset;
				gint xoffset;
				gboolean _tmp2_ = FALSE;
				yoffset = ((((GtkMenuItem*) self)->toggle_size - icon_req.height) + toggle_spacing) / 2;
				xoffset = ((*a).width - icon_req.width) / 2;
				ca.x = (*a).x + xoffset;
				if (gtk_widget_get_direction ((GtkWidget*) self) == GTK_TEXT_DIR_LTR) {
					_tmp2_ = matenu_menu_item_get_pack_direction (self) == GTK_PACK_DIRECTION_TTB;
				} else {
					_tmp2_ = FALSE;
				}
				if (_tmp2_) {
					ca.y = (*a).y + yoffset;
				} else {
					ca.y = (((*a).y + (*a).height) - ca.height) - yoffset;
				}
				break;
			}
		}
		gtk_widget_size_allocate ((GtkWidget*) self->priv->_image_widget, &ca);
	}
}


static void matenu_menu_item_update_font (MatenuMenuItem* self) {
	PangoFontDescription* desc;
	GtkWidget* bin_child;
	g_return_if_fail (self != NULL);
	desc = NULL;
	if (self->priv->_font != NULL) {
		PangoFontDescription* _tmp0_;
		desc = (_tmp0_ = pango_font_description_from_string (self->priv->_font), _pango_font_description_free0 (desc), _tmp0_);
	} else {
		PangoFontDescription* _tmp1_;
		desc = (_tmp1_ = NULL, _pango_font_description_free0 (desc), _tmp1_);
	}
	bin_child = _g_object_ref0 (gtk_bin_get_child ((GtkBin*) self));
	if (bin_child != NULL) {
		gtk_widget_modify_font (bin_child, desc);
	}
	_g_object_unref0 (bin_child);
	_pango_font_description_free0 (desc);
}


static char* matenu_menu_item_remove_underlines (MatenuMenuItem* self, const char* s) {
	char* result = NULL;
	GString* sb;
	const char* p;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (s != NULL, NULL);
	sb = g_string_new ("");
	p = NULL;
	{
		gboolean _tmp0_;
		p = s;
		_tmp0_ = TRUE;
		while (TRUE) {
			gunichar c;
			if (!_tmp0_) {
				p = g_utf8_next_char (p);
			}
			_tmp0_ = FALSE;
			if (!(g_utf8_get_char (p) != 0)) {
				break;
			}
			c = g_utf8_get_char (p);
			if (c != '_') {
				g_string_append_unichar (sb, c);
			}
		}
	}
	result = g_strdup (sb->str);
	_g_string_free0 (sb);
	return result;
}


static void matenu_menu_item_update_label_text (MatenuMenuItem* self) {
	char* text;
	MatenuMenuLabel* label;
	g_return_if_fail (self != NULL);
	if (!matenu_item_type_has_label (self->priv->_item_type)) {
		return;
	}
	text = NULL;
	if (self->priv->_label == NULL) {
		char* _tmp0_;
		text = (_tmp0_ = matenu_item_get_item_path ((MatenuItem*) self), _g_free0 (text), _tmp0_);
	} else {
		if (!self->priv->_show_underline) {
			char* _tmp1_;
			text = (_tmp1_ = matenu_menu_item_remove_underlines (self, self->priv->_label), _g_free0 (text), _tmp1_);
		} else {
			char* _tmp2_;
			text = (_tmp2_ = g_strdup (self->priv->_label), _g_free0 (text), _tmp2_);
		}
	}
	label = _g_object_ref0 (matenu_menu_item_get_label_widget (self));
	;
	g_assert (label != NULL);
	matenu_menu_label_set_label (label, text);
	matenu_menu_label_set_accel (label, self->priv->_accel_text);
	matenu_menu_label_set_max_width_chars (label, self->priv->_max_width_chars);
	_g_object_unref0 (label);
	_g_free0 (text);
}


static void matenu_menu_item_update_label_underline (MatenuMenuItem* self) {
	MatenuMenuLabel* label;
	g_return_if_fail (self != NULL);
	if (!matenu_item_type_has_label (self->priv->_item_type)) {
		return;
	}
	label = _g_object_ref0 (matenu_menu_item_get_label_widget (self));
	;
	g_assert (label != NULL);
	matenu_menu_label_set_use_underline (label, self->priv->_use_underline);
	_g_object_unref0 (label);
}


static void matenu_menu_item_update_image (MatenuMenuItem* self) {
	GError * _inner_error_;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	if (self->priv->_item_type != MATENU_ITEM_TYPE_IMAGE) {
		_tmp0_ = self->priv->_item_type != MATENU_ITEM_TYPE_ICON;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		return;
	}
	if (self->priv->_icon != NULL) {
		_tmp1_ = g_str_has_prefix (self->priv->_icon, "theme:");
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		const char* icon_name;
		icon_name = g_utf8_offset_to_pointer (self->priv->_icon, (glong) 6);
		gtk_image_set_from_icon_name (matenu_menu_item_get_image (self), icon_name, GTK_ICON_SIZE_MENU);
	} else {
		gboolean _tmp2_ = FALSE;
		if (self->priv->_icon != NULL) {
			_tmp2_ = g_str_has_prefix (self->priv->_icon, "file:");
		} else {
			_tmp2_ = FALSE;
		}
		if (_tmp2_) {
			const char* filename;
			filename = g_utf8_offset_to_pointer (self->priv->_icon, (glong) 5);
			gtk_image_set_from_file (matenu_menu_item_get_image (self), filename);
		} else {
			gboolean _tmp3_ = FALSE;
			if (self->priv->_icon != NULL) {
				_tmp3_ = g_str_has_prefix (self->priv->_icon, "pixbuf:");
			} else {
				_tmp3_ = FALSE;
			}
			if (_tmp3_) {
				const char* b64data;
				guchar* _tmp5_;
				gint _data_size_;
				gint data_length1;
				size_t _tmp4_;
				guchar* data;
				GdkPixdata _tmp6_ = {0};
				GdkPixdata pixdata;
				GdkPixbuf* pixbuf;
				b64data = g_utf8_offset_to_pointer (self->priv->_icon, (glong) 7);
				data = (_tmp5_ = g_base64_decode (b64data, &_tmp4_), data_length1 = _tmp4_, _data_size_ = data_length1, _tmp5_);
				pixdata = (_tmp6_.magic = (guint32) 0, _tmp6_);
				gdk_pixdata_deserialize (&pixdata, data_length1, data, &_inner_error_);
				if (_inner_error_ != NULL) {
					data = (g_free (data), NULL);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				pixbuf = gdk_pixbuf_from_pixdata (&pixdata, TRUE, &_inner_error_);
				if (_inner_error_ != NULL) {
					data = (g_free (data), NULL);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				gtk_image_set_from_pixbuf (matenu_menu_item_get_image (self), pixbuf);
				_g_object_unref0 (pixbuf);
				data = (g_free (data), NULL);
			} else {
				gboolean _tmp7_ = FALSE;
				if (self->priv->_icon != NULL) {
					_tmp7_ = g_str_has_prefix (self->priv->_icon, "custom:");
				} else {
					_tmp7_ = FALSE;
				}
				if (_tmp7_) {
				} else {
					gtk_image_set_from_stock (matenu_menu_item_get_image (self), self->priv->_icon, GTK_ICON_SIZE_MENU);
				}
			}
		}
	}
}


static void matenu_menu_item_real_parent_set (GtkWidget* base, GtkWidget* old_parent) {
	MatenuMenuItem * self;
	self = (MatenuMenuItem*) base;
	if (gtk_widget_get_parent ((GtkWidget*) self) != NULL) {
		matenu_menu_item_update_label_text (self);
	}
}


static void matenu_menu_item_create_labels (MatenuMenuItem* self) {
	g_return_if_fail (self != NULL);
	g_assert (matenu_item_type_has_label (self->priv->_item_type));
	gtk_widget_set_visible ((GtkWidget*) self->priv->_cached_label_widget, TRUE);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->_cached_label_widget, TRUE);
	matenu_menu_label_set_gravity (self->priv->_cached_label_widget, matenu_menu_item_get_gravity (self));
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->_cached_label_widget);
	matenu_menu_item_update_font (self);
	matenu_menu_item_update_label_underline (self);
}


static MatenuMenuLabel* matenu_menu_item_get_label_widget (MatenuMenuItem* self) {
	MatenuMenuLabel* result = NULL;
	GtkWidget* _tmp0_;
	MatenuMenuLabel* label;
	g_return_val_if_fail (self != NULL, NULL);
	label = (_tmp0_ = gtk_bin_get_child ((GtkBin*) self), MATENU_IS_MENU_LABEL (_tmp0_) ? ((MatenuMenuLabel*) _tmp0_) : NULL);
	result = label;
	return result;
}


static void matenu_menu_item_remove_child (MatenuMenuItem* self) {
	GtkWidget* child;
	g_return_if_fail (self != NULL);
	child = _g_object_ref0 (gtk_bin_get_child ((GtkBin*) self));
	if (child != NULL) {
		gtk_container_remove ((GtkContainer*) self, child);
	}
	_g_object_unref0 (child);
}


static void matenu_menu_item_create_arrow (MatenuMenuItem* self) {
	g_return_if_fail (self != NULL);
	g_assert (self->priv->_item_type == MATENU_ITEM_TYPE_ARROW);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->_cached_arrow_widget);
	gtk_widget_set_visible ((GtkWidget*) self->priv->_cached_arrow_widget, TRUE);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->_cached_arrow_widget, TRUE);
	matenu_menu_item_update_arrow_type (self);
}


static void matenu_menu_item_update_arrow_type (MatenuMenuItem* self) {
	GtkWidget* _tmp0_;
	g_return_if_fail (self != NULL);
	if (self->priv->_item_type != MATENU_ITEM_TYPE_ARROW) {
		return;
	}
	gtk_arrow_set ((_tmp0_ = gtk_bin_get_child ((GtkBin*) self), GTK_IS_ARROW (_tmp0_) ? ((GtkArrow*) _tmp0_) : NULL), matenu_gravity_to_arrow_type (self->priv->_gravity), GTK_SHADOW_NONE);
}


GtkShadowType matenu_menu_item_item_state_to_shadow_type (MatenuItemState state) {
	GtkShadowType result = 0;
	switch (state) {
		case MATENU_ITEM_STATE_TOGGLED:
		{
			result = GTK_SHADOW_IN;
			return result;
		}
		case MATENU_ITEM_STATE_UNTOGGLED:
		{
			result = GTK_SHADOW_OUT;
			return result;
		}
		default:
		{
			result = GTK_SHADOW_ETCHED_IN;
			return result;
		}
	}
}


gint matenu_menu_item_get_max_width_chars (MatenuMenuItem* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_max_width_chars;
	return result;
}


void matenu_menu_item_set_max_width_chars (MatenuMenuItem* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->_max_width_chars = value;
	matenu_menu_item_update_label_text (self);
	g_object_notify ((GObject *) self, "max-width-chars");
}


static MatenuShell* matenu_menu_item_real_get_shell (MatenuItem* base) {
	MatenuShell* result;
	MatenuMenuItem* self;
	GtkContainer* _tmp0_;
	MatenuShell* rt;
	self = (MatenuMenuItem*) base;
	rt = (MatenuShell*) matenu_adapter_get_adapter ((_tmp0_ = gtk_widget_get_parent ((GtkWidget*) self), GTK_IS_MENU_SHELL (_tmp0_) ? ((GtkMenuShell*) _tmp0_) : NULL));
	if (rt != NULL) {
		result = rt;
		return result;
	} else {
		GtkContainer* _tmp1_;
		result = (_tmp1_ = gtk_widget_get_parent ((GtkWidget*) self), MATENU_IS_SHELL (_tmp1_) ? ((MatenuShell*) _tmp1_) : NULL);
		return result;
	}
}


static MatenuShell* matenu_menu_item_real_get_sub_shell (MatenuItem* base) {
	MatenuShell* result;
	MatenuMenuItem* self;
	MatenuMenu* _tmp0_;
	self = (MatenuMenuItem*) base;
	result = (_tmp0_ = self->_submenu_cache, MATENU_IS_SHELL (_tmp0_) ? ((MatenuShell*) _tmp0_) : NULL);
	return result;
}


static gboolean matenu_menu_item_real_get_has_sub_shell (MatenuItem* base) {
	gboolean result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_has_sub_shell;
	return result;
}


static void matenu_menu_item_real_set_has_sub_shell (MatenuItem* base, gboolean value) {
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	self->priv->_has_sub_shell = value;
	matenu_menu_item_maybe_connect_cached_submenu (self);
	g_object_notify ((GObject *) self, "has-sub-shell");
}


static gboolean matenu_menu_item_real_get_client_side_sub_shell (MatenuItem* base) {
	gboolean result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_client_side_sub_shell;
	return result;
}


static void matenu_menu_item_real_set_client_side_sub_shell (MatenuItem* base, gboolean value) {
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	self->priv->_client_side_sub_shell = value;
	matenu_menu_item_maybe_connect_cached_submenu (self);
	g_object_notify ((GObject *) self, "client-side-sub-shell");
}


static const char* matenu_menu_item_real_get_item_id (MatenuItem* base) {
	const char* result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_id;
	return result;
}


static void matenu_menu_item_real_set_item_id (MatenuItem* base, const char* value) {
	MatenuMenuItem* self;
	char* _tmp0_;
	self = (MatenuMenuItem*) base;
	if (_vala_strcmp0 (self->priv->_id, value) == 0) {
		return;
	}
	self->priv->_id = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_id), _tmp0_);
	if (self->priv->_label == NULL) {
		matenu_menu_item_update_label_text (self);
	}
	g_object_notify ((GObject *) self, "item-id");
}


static const char* matenu_menu_item_real_get_item_label (MatenuItem* base) {
	const char* result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_label;
	return result;
}


static void matenu_menu_item_real_set_item_label (MatenuItem* base, const char* value) {
	MatenuMenuItem* self;
	char* _tmp0_;
	self = (MatenuMenuItem*) base;
	if (_vala_strcmp0 (self->priv->_label, value) == 0) {
		return;
	}
	self->priv->_label = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_label), _tmp0_);
	matenu_menu_item_update_label_text (self);
	g_object_notify ((GObject *) self, "item-label");
}


static const char* matenu_menu_item_real_get_item_icon (MatenuItem* base) {
	const char* result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_icon;
	return result;
}


static void matenu_menu_item_real_set_item_icon (MatenuItem* base, const char* value) {
	MatenuMenuItem* self;
	char* _tmp0_;
	self = (MatenuMenuItem*) base;
	if (_vala_strcmp0 (self->priv->_icon, value) == 0) {
		return;
	}
	self->priv->_icon = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_icon), _tmp0_);
	matenu_menu_item_update_image (self);
	g_object_notify ((GObject *) self, "item-icon");
}


static const char* matenu_menu_item_real_get_item_accel_text (MatenuItem* base) {
	const char* result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_accel_text;
	return result;
}


static void matenu_menu_item_real_set_item_accel_text (MatenuItem* base, const char* value) {
	MatenuMenuItem* self;
	char* _tmp0_;
	self = (MatenuMenuItem*) base;
	if (_vala_strcmp0 (self->priv->_accel_text, value) == 0) {
		return;
	}
	self->priv->_accel_text = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_accel_text), _tmp0_);
	matenu_menu_item_update_label_text (self);
	g_object_notify ((GObject *) self, "item-accel-text");
}


static const char* matenu_menu_item_real_get_item_font (MatenuItem* base) {
	const char* result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_font;
	return result;
}


static void matenu_menu_item_real_set_item_font (MatenuItem* base, const char* value) {
	MatenuMenuItem* self;
	char* _tmp0_;
	self = (MatenuMenuItem*) base;
	if (_vala_strcmp0 (self->priv->_font, value) == 0) {
		return;
	}
	self->priv->_font = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_font), _tmp0_);
	matenu_menu_item_update_font (self);
	g_object_notify ((GObject *) self, "item-font");
}


static MatenuItemType matenu_menu_item_real_get_item_type (MatenuItem* base) {
	MatenuItemType result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_item_type;
	return result;
}


static void matenu_menu_item_real_set_item_type (MatenuItem* base, MatenuItemType value) {
	MatenuMenuItem* self;
	MatenuItemType old_type;
	self = (MatenuMenuItem*) base;
	if (value == self->priv->_item_type) {
		return;
	}
	old_type = self->priv->_item_type;
	self->priv->_item_type = value;
	switch (self->priv->_item_type) {
		case MATENU_ITEM_TYPE_SEPARATOR:
		{
			matenu_menu_item_remove_child (self);
			break;
		}
		case MATENU_ITEM_TYPE_NORMAL:
		case MATENU_ITEM_TYPE_IMAGE:
		case MATENU_ITEM_TYPE_CHECK:
		case MATENU_ITEM_TYPE_RADIO:
		{
			gboolean _tmp0_ = FALSE;
			gboolean _tmp1_ = FALSE;
			gboolean _tmp2_ = FALSE;
			if (old_type != MATENU_ITEM_TYPE_NORMAL) {
				_tmp2_ = old_type != MATENU_ITEM_TYPE_IMAGE;
			} else {
				_tmp2_ = FALSE;
			}
			if (_tmp2_) {
				_tmp1_ = old_type != MATENU_ITEM_TYPE_RADIO;
			} else {
				_tmp1_ = FALSE;
			}
			if (_tmp1_) {
				_tmp0_ = old_type != MATENU_ITEM_TYPE_CHECK;
			} else {
				_tmp0_ = FALSE;
			}
			if (_tmp0_) {
				matenu_menu_item_remove_child (self);
				matenu_menu_item_create_labels (self);
				matenu_menu_item_update_label_text (self);
			}
			break;
		}
		case MATENU_ITEM_TYPE_ARROW:
		{
			if (old_type != MATENU_ITEM_TYPE_ARROW) {
				matenu_menu_item_remove_child (self);
				matenu_menu_item_create_arrow (self);
				matenu_menu_item_update_arrow_type (self);
			}
			break;
		}
		case MATENU_ITEM_TYPE_ICON:
		{
			if (old_type != MATENU_ITEM_TYPE_ICON) {
				GtkImage* _tmp3_;
				matenu_menu_item_remove_child (self);
				self->priv->_icon_widget = (_tmp3_ = g_object_ref_sink ((GtkImage*) gtk_image_new ()), _g_object_unref0 (self->priv->_icon_widget), _tmp3_);
				gtk_widget_set_visible ((GtkWidget*) self->priv->_icon_widget, TRUE);
				gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->_icon_widget);
				matenu_menu_item_update_image (self);
			}
			break;
		}
	}
	if (self->priv->_item_type == MATENU_ITEM_TYPE_IMAGE) {
		GtkImage* _tmp4_;
		self->priv->_image_widget = (_tmp4_ = _g_object_ref0 (self->priv->_cached_image_widget), _g_object_unref0 (self->priv->_image_widget), _tmp4_);
		gtk_widget_set_sensitive ((GtkWidget*) self->priv->_image_widget, FALSE);
		gtk_widget_set_sensitive ((GtkWidget*) self->priv->_image_widget, TRUE);
		gtk_widget_set_parent ((GtkWidget*) self->priv->_image_widget, (GtkWidget*) self);
		gtk_widget_set_visible ((GtkWidget*) self->priv->_image_widget, matenu_menu_item_get__show_image (self));
		matenu_menu_item_update_image (self);
	} else {
		if (self->priv->_image_widget != NULL) {
			GtkImage* _tmp5_;
			gtk_widget_unparent ((GtkWidget*) self->priv->_image_widget);
			self->priv->_image_widget = (_tmp5_ = NULL, _g_object_unref0 (self->priv->_image_widget), _tmp5_);
		}
	}
	gtk_widget_queue_resize ((GtkWidget*) self);
	g_object_notify ((GObject *) self, "item-type");
}


static gboolean matenu_menu_item_real_get_item_use_underline (MatenuItem* base) {
	gboolean result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_use_underline;
	return result;
}


static void matenu_menu_item_real_set_item_use_underline (MatenuItem* base, gboolean value) {
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	if (self->priv->_use_underline == value) {
		return;
	}
	self->priv->_use_underline = value;
	matenu_menu_item_update_label_underline (self);
	g_object_notify ((GObject *) self, "item-use-underline");
}


static MatenuItemState matenu_menu_item_real_get_item_state (MatenuItem* base) {
	MatenuItemState result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_item_state;
	return result;
}


static void matenu_menu_item_real_set_item_state (MatenuItem* base, MatenuItemState value) {
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	if (value == self->priv->_item_state) {
		return;
	}
	self->priv->_item_state = value;
	gtk_widget_queue_draw ((GtkWidget*) self);
	g_object_notify ((GObject *) self, "item-state");
}


static gboolean matenu_menu_item_real_get_item_visible (MatenuItem* base) {
	gboolean result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = self->priv->_item_visible;
	return result;
}


static void matenu_menu_item_real_set_item_visible (MatenuItem* base, gboolean value) {
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	self->priv->_item_visible = value;
	gtk_widget_set_visible ((GtkWidget*) self, value);
	g_object_notify ((GObject *) self, "item-visible");
}


static gboolean matenu_menu_item_real_get_item_sensitive (MatenuItem* base) {
	gboolean result;
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	result = gtk_widget_get_sensitive ((GtkWidget*) self);
	return result;
}


static void matenu_menu_item_real_set_item_sensitive (MatenuItem* base, gboolean value) {
	MatenuMenuItem* self;
	self = (MatenuMenuItem*) base;
	gtk_widget_set_sensitive ((GtkWidget*) self, value);
	g_object_notify ((GObject *) self, "item-sensitive");
}


MatenuGravity matenu_menu_item_get_gravity (MatenuMenuItem* self) {
	MatenuGravity result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_gravity;
	return result;
}


void matenu_menu_item_set_gravity (MatenuMenuItem* self, MatenuGravity value) {
	g_return_if_fail (self != NULL);
	if (self->priv->_gravity == value) {
		return;
	}
	self->priv->_gravity = value;
	if (matenu_item_type_has_label (self->priv->_item_type)) {
		matenu_menu_label_set_gravity (matenu_menu_item_get_label_widget (self), value);
	}
	matenu_menu_item_update_arrow_type (self);
	g_object_notify ((GObject *) self, "gravity");
}


gboolean matenu_menu_item_get_show_underline (MatenuMenuItem* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_show_underline;
	return result;
}


void matenu_menu_item_set_show_underline (MatenuMenuItem* self, gboolean value) {
	g_return_if_fail (self != NULL);
	if (self->priv->_show_underline != value) {
		self->priv->_show_underline = value;
		matenu_menu_item_update_label_text (self);
	}
	g_object_notify ((GObject *) self, "show-underline");
}


gboolean matenu_menu_item_get_truncated (MatenuMenuItem* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_truncated;
	return result;
}


void matenu_menu_item_set_truncated (MatenuMenuItem* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	self->priv->_truncated = value;
	if (self->priv->_item_visible) {
		_tmp0_ = !matenu_menu_item_get_truncated (self);
	} else {
		_tmp0_ = FALSE;
	}
	gtk_widget_set_visible ((GtkWidget*) self, _tmp0_);
	g_object_notify ((GObject *) self, "truncated");
}


static gboolean matenu_menu_item_get__show_image (MatenuMenuItem* self) {
	gboolean result;
	gboolean rt;
	g_return_val_if_fail (self != NULL, FALSE);
	rt = FALSE;
	g_object_get ((GObject*) gtk_widget_get_settings ((GtkWidget*) self), "gtk-menu-images", &rt, NULL, NULL);
	result = rt;
	return result;
}


GtkImage* matenu_menu_item_get_image (MatenuMenuItem* self) {
	GtkImage* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->priv->_item_type == MATENU_ITEM_TYPE_IMAGE) {
		result = self->priv->_image_widget;
		return result;
	}
	if (self->priv->_item_type == MATENU_ITEM_TYPE_ICON) {
		result = self->priv->_icon_widget;
		return result;
	}
	result = NULL;
	return result;
}


static GtkPackDirection matenu_menu_item_get_pack_direction (MatenuMenuItem* self) {
	GtkPackDirection result;
	g_return_val_if_fail (self != NULL, 0);
	if (GTK_IS_MENU_BAR (gtk_widget_get_parent ((GtkWidget*) self))) {
		GtkContainer* _tmp0_;
		result = gtk_menu_bar_get_child_pack_direction ((_tmp0_ = gtk_widget_get_parent ((GtkWidget*) self), GTK_IS_MENU_BAR (_tmp0_) ? ((GtkMenuBar*) _tmp0_) : NULL));
		return result;
	}
	result = GTK_PACK_DIRECTION_LTR;
	return result;
}


static GObject * matenu_menu_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MatenuMenuItem * self;
	parent_class = G_OBJECT_CLASS (matenu_menu_item_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MATENU_MENU_ITEM (obj);
	{
		MatenuMenuLabel* _tmp0_;
		GtkImage* _tmp1_;
		GtkArrow* _tmp2_;
		self->priv->disposed = FALSE;
		gtk_widget_set_no_show_all ((GtkWidget*) self, TRUE);
		self->priv->_item_type = MATENU_ITEM_TYPE_NORMAL;
		self->priv->_cached_label_widget = (_tmp0_ = g_object_ref_sink (matenu_menu_label_new ()), _g_object_unref0 (self->priv->_cached_label_widget), _tmp0_);
		self->priv->_cached_image_widget = (_tmp1_ = g_object_ref_sink ((GtkImage*) gtk_image_new ()), _g_object_unref0 (self->priv->_cached_image_widget), _tmp1_);
		self->priv->_cached_arrow_widget = (_tmp2_ = g_object_ref_sink ((GtkArrow*) gtk_arrow_new (matenu_gravity_to_arrow_type (self->priv->_gravity), GTK_SHADOW_NONE)), _g_object_unref0 (self->priv->_cached_arrow_widget), _tmp2_);
		self->priv->_use_underline = TRUE;
		matenu_menu_item_create_labels (self);
	}
	return obj;
}


static void matenu_menu_item_class_init (MatenuMenuItemClass * klass) {
	matenu_menu_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MatenuMenuItemPrivate));
	G_OBJECT_CLASS (klass)->dispose = matenu_menu_item_real_dispose;
	GTK_MENU_ITEM_CLASS (klass)->toggle_size_request = matenu_menu_item_real_toggle_size_request;
	GTK_WIDGET_CLASS (klass)->expose_event = matenu_menu_item_real_expose_event;
	GTK_CONTAINER_CLASS (klass)->forall = matenu_menu_item_real_forall_internal;
	GTK_MENU_ITEM_CLASS (klass)->activate = matenu_menu_item_real_activate;
	GTK_ITEM_CLASS (klass)->select = matenu_menu_item_real_select;
	GTK_ITEM_CLASS (klass)->deselect = matenu_menu_item_real_deselect;
	GTK_WIDGET_CLASS (klass)->screen_changed = matenu_menu_item_real_screen_changed;
	GTK_WIDGET_CLASS (klass)->size_request = matenu_menu_item_real_size_request;
	GTK_WIDGET_CLASS (klass)->size_allocate = matenu_menu_item_real_size_allocate;
	GTK_WIDGET_CLASS (klass)->parent_set = matenu_menu_item_real_parent_set;
	G_OBJECT_CLASS (klass)->get_property = matenu_menu_item_get_property;
	G_OBJECT_CLASS (klass)->set_property = matenu_menu_item_set_property;
	G_OBJECT_CLASS (klass)->constructor = matenu_menu_item_constructor;
	G_OBJECT_CLASS (klass)->finalize = matenu_menu_item_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_MAX_WIDTH_CHARS, g_param_spec_int ("max-width-chars", "max-width-chars", "max-width-chars", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_SHELL, "shell");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_SUB_SHELL, "sub-shell");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_HAS_SUB_SHELL, "has-sub-shell");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_CLIENT_SIDE_SUB_SHELL, "client-side-sub-shell");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_ID, "item-id");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_LABEL, "item-label");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_ICON, "item-icon");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_ACCEL_TEXT, "item-accel-text");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_FONT, "item-font");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_TYPE, "item-type");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_USE_UNDERLINE, "item-use-underline");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_STATE, "item-state");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_VISIBLE, "item-visible");
	g_object_class_override_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_ITEM_SENSITIVE, "item-sensitive");
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_GRAVITY, g_param_spec_enum ("gravity", "gravity", "gravity", MATENU_TYPE_GRAVITY, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_SHOW_UNDERLINE, g_param_spec_boolean ("show-underline", "show-underline", "show-underline", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_TRUNCATED, g_param_spec_boolean ("truncated", "truncated", "truncated", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_MENU_ITEM_IMAGE, g_param_spec_object ("image", "image", "image", GTK_TYPE_IMAGE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	{
		GParamSpecInt* _tmp3_;
		GtkImageMenuItem* item;
		gtk_widget_class_install_style_property (GTK_WIDGET_CLASS (klass), (GParamSpec*) (_tmp3_ = g_param_spec_int ("indicator-size", _ ("Indicator Size"), _ ("Size of check or radio indicator"), 0, G_MAXINT, 13, G_PARAM_READABLE)));
		_g_param_spec_unref0 (_tmp3_);
		gtk_icon_size_lookup (GTK_ICON_SIZE_MENU, &matenu_menu_item_icon_width, &matenu_menu_item_icon_height);
		item = g_object_ref_sink ((GtkImageMenuItem*) gtk_image_menu_item_new ());
		_g_object_unref0 (item);
	}
}


static void matenu_menu_item_matenu_item_interface_init (MatenuItemIface * iface) {
	matenu_menu_item_matenu_item_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_shell = matenu_menu_item_real_get_shell;
	iface->get_sub_shell = matenu_menu_item_real_get_sub_shell;
	iface->get_has_sub_shell = matenu_menu_item_real_get_has_sub_shell;
	iface->set_has_sub_shell = matenu_menu_item_real_set_has_sub_shell;
	iface->get_client_side_sub_shell = matenu_menu_item_real_get_client_side_sub_shell;
	iface->set_client_side_sub_shell = matenu_menu_item_real_set_client_side_sub_shell;
	iface->get_item_id = matenu_menu_item_real_get_item_id;
	iface->set_item_id = matenu_menu_item_real_set_item_id;
	iface->get_item_label = matenu_menu_item_real_get_item_label;
	iface->set_item_label = matenu_menu_item_real_set_item_label;
	iface->get_item_icon = matenu_menu_item_real_get_item_icon;
	iface->set_item_icon = matenu_menu_item_real_set_item_icon;
	iface->get_item_accel_text = matenu_menu_item_real_get_item_accel_text;
	iface->set_item_accel_text = matenu_menu_item_real_set_item_accel_text;
	iface->get_item_font = matenu_menu_item_real_get_item_font;
	iface->set_item_font = matenu_menu_item_real_set_item_font;
	iface->get_item_type = matenu_menu_item_real_get_item_type;
	iface->set_item_type = matenu_menu_item_real_set_item_type;
	iface->get_item_use_underline = matenu_menu_item_real_get_item_use_underline;
	iface->set_item_use_underline = matenu_menu_item_real_set_item_use_underline;
	iface->get_item_state = matenu_menu_item_real_get_item_state;
	iface->set_item_state = matenu_menu_item_real_set_item_state;
	iface->get_item_visible = matenu_menu_item_real_get_item_visible;
	iface->set_item_visible = matenu_menu_item_real_set_item_visible;
	iface->get_item_sensitive = matenu_menu_item_real_get_item_sensitive;
	iface->set_item_sensitive = matenu_menu_item_real_set_item_sensitive;
}


static void matenu_menu_item_instance_init (MatenuMenuItem * self) {
	self->priv = MATENU_MENU_ITEM_GET_PRIVATE (self);
	self->priv->_max_width_chars = 30;
	self->_submenu_cache = g_object_ref_sink (matenu_menu_new ());
	self->priv->_has_sub_shell = FALSE;
	self->priv->_client_side_sub_shell = FALSE;
	self->priv->_show_underline = TRUE;
	self->priv->_use_underline = FALSE;
}


static void matenu_menu_item_finalize (GObject* obj) {
	MatenuMenuItem * self;
	self = MATENU_MENU_ITEM (obj);
	_g_object_unref0 (self->_submenu_cache);
	_g_free0 (self->priv->_font);
	_g_free0 (self->priv->_label);
	_g_free0 (self->priv->_icon);
	_g_free0 (self->priv->_accel_text);
	_g_free0 (self->priv->_id);
	_g_object_unref0 (self->priv->_cached_image_widget);
	_g_object_unref0 (self->priv->_cached_arrow_widget);
	_g_object_unref0 (self->priv->_cached_label_widget);
	_g_object_unref0 (self->priv->_image_widget);
	_g_object_unref0 (self->priv->_icon_widget);
	G_OBJECT_CLASS (matenu_menu_item_parent_class)->finalize (obj);
}


GType matenu_menu_item_get_type (void) {
	static volatile gsize matenu_menu_item_type_id__volatile = 0;
	if (g_once_init_enter (&matenu_menu_item_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MatenuMenuItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) matenu_menu_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MatenuMenuItem), 0, (GInstanceInitFunc) matenu_menu_item_instance_init, NULL };
		static const GInterfaceInfo matenu_item_info = { (GInterfaceInitFunc) matenu_menu_item_matenu_item_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType matenu_menu_item_type_id;
		matenu_menu_item_type_id = g_type_register_static (GTK_TYPE_MENU_ITEM, "MatenuMenuItem", &g_define_type_info, 0);
		g_type_add_interface_static (matenu_menu_item_type_id, MATENU_TYPE_ITEM, &matenu_item_info);
		g_once_init_leave (&matenu_menu_item_type_id__volatile, matenu_menu_item_type_id);
	}
	return matenu_menu_item_type_id__volatile;
}


static void matenu_menu_item_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MatenuMenuItem * self;
	self = MATENU_MENU_ITEM (object);
	switch (property_id) {
		case MATENU_MENU_ITEM_MAX_WIDTH_CHARS:
		g_value_set_int (value, matenu_menu_item_get_max_width_chars (self));
		break;
		case MATENU_MENU_ITEM_SHELL:
		g_value_set_object (value, matenu_item_get_shell ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_SUB_SHELL:
		g_value_set_object (value, matenu_item_get_sub_shell ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_HAS_SUB_SHELL:
		g_value_set_boolean (value, matenu_item_get_has_sub_shell ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_CLIENT_SIDE_SUB_SHELL:
		g_value_set_boolean (value, matenu_item_get_client_side_sub_shell ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_ID:
		g_value_set_string (value, matenu_item_get_item_id ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_LABEL:
		g_value_set_string (value, matenu_item_get_item_label ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_ICON:
		g_value_set_string (value, matenu_item_get_item_icon ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_ACCEL_TEXT:
		g_value_set_string (value, matenu_item_get_item_accel_text ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_FONT:
		g_value_set_string (value, matenu_item_get_item_font ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_TYPE:
		g_value_set_enum (value, matenu_item_get_item_type ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_USE_UNDERLINE:
		g_value_set_boolean (value, matenu_item_get_item_use_underline ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_STATE:
		g_value_set_enum (value, matenu_item_get_item_state ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_VISIBLE:
		g_value_set_boolean (value, matenu_item_get_item_visible ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_ITEM_SENSITIVE:
		g_value_set_boolean (value, matenu_item_get_item_sensitive ((MatenuItem*) self));
		break;
		case MATENU_MENU_ITEM_GRAVITY:
		g_value_set_enum (value, matenu_menu_item_get_gravity (self));
		break;
		case MATENU_MENU_ITEM_SHOW_UNDERLINE:
		g_value_set_boolean (value, matenu_menu_item_get_show_underline (self));
		break;
		case MATENU_MENU_ITEM_TRUNCATED:
		g_value_set_boolean (value, matenu_menu_item_get_truncated (self));
		break;
		case MATENU_MENU_ITEM_IMAGE:
		g_value_set_object (value, matenu_menu_item_get_image (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void matenu_menu_item_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MatenuMenuItem * self;
	self = MATENU_MENU_ITEM (object);
	switch (property_id) {
		case MATENU_MENU_ITEM_MAX_WIDTH_CHARS:
		matenu_menu_item_set_max_width_chars (self, g_value_get_int (value));
		break;
		case MATENU_MENU_ITEM_HAS_SUB_SHELL:
		matenu_item_set_has_sub_shell ((MatenuItem*) self, g_value_get_boolean (value));
		break;
		case MATENU_MENU_ITEM_CLIENT_SIDE_SUB_SHELL:
		matenu_item_set_client_side_sub_shell ((MatenuItem*) self, g_value_get_boolean (value));
		break;
		case MATENU_MENU_ITEM_ITEM_ID:
		matenu_item_set_item_id ((MatenuItem*) self, g_value_get_string (value));
		break;
		case MATENU_MENU_ITEM_ITEM_LABEL:
		matenu_item_set_item_label ((MatenuItem*) self, g_value_get_string (value));
		break;
		case MATENU_MENU_ITEM_ITEM_ICON:
		matenu_item_set_item_icon ((MatenuItem*) self, g_value_get_string (value));
		break;
		case MATENU_MENU_ITEM_ITEM_ACCEL_TEXT:
		matenu_item_set_item_accel_text ((MatenuItem*) self, g_value_get_string (value));
		break;
		case MATENU_MENU_ITEM_ITEM_FONT:
		matenu_item_set_item_font ((MatenuItem*) self, g_value_get_string (value));
		break;
		case MATENU_MENU_ITEM_ITEM_TYPE:
		matenu_item_set_item_type ((MatenuItem*) self, g_value_get_enum (value));
		break;
		case MATENU_MENU_ITEM_ITEM_USE_UNDERLINE:
		matenu_item_set_item_use_underline ((MatenuItem*) self, g_value_get_boolean (value));
		break;
		case MATENU_MENU_ITEM_ITEM_STATE:
		matenu_item_set_item_state ((MatenuItem*) self, g_value_get_enum (value));
		break;
		case MATENU_MENU_ITEM_ITEM_VISIBLE:
		matenu_item_set_item_visible ((MatenuItem*) self, g_value_get_boolean (value));
		break;
		case MATENU_MENU_ITEM_ITEM_SENSITIVE:
		matenu_item_set_item_sensitive ((MatenuItem*) self, g_value_get_boolean (value));
		break;
		case MATENU_MENU_ITEM_GRAVITY:
		matenu_menu_item_set_gravity (self, g_value_get_enum (value));
		break;
		case MATENU_MENU_ITEM_SHOW_UNDERLINE:
		matenu_menu_item_set_show_underline (self, g_value_get_boolean (value));
		break;
		case MATENU_MENU_ITEM_TRUNCATED:
		matenu_menu_item_set_truncated (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




