/* enums.c generated by valac, the Vala compiler
 * generated from enums.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gtk/gtk.h>


#define MATENU_TYPE_BACKGROUND_TYPE (matenu_background_type_get_type ())

#define MATENU_TYPE_GRAVITY (matenu_gravity_get_type ())

typedef enum  {
	MATENU_BACKGROUND_TYPE_NONE = 0,
	MATENU_BACKGROUND_TYPE_COLOR = 1,
	MATENU_BACKGROUND_TYPE_PIXMAP = 2
} MatenuBackgroundType;

typedef enum  {
	MATENU_GRAVITY_DOWN = 0,
	MATENU_GRAVITY_UP = 1,
	MATENU_GRAVITY_LEFT = 2,
	MATENU_GRAVITY_RIGHT = 3
} MatenuGravity;



#define MATENU_NET_GLOBALMENU_MENU_CONTEXT "_NET_GLOBALMENU_MENU_CONTEXT"
#define MATENU_NET_GLOBALMENU_MENU_EVENT "_NET_GLOBALMENU_MENU_EVENT"
#define MATENU_NET_GLOBALMENU_MENU_SELECT "_NET_GLOBALMENU_MENU_SELECT"
#define MATENU_NET_GLOBALMENU_MENU_DESELECT "_NET_GLOBALMENU_MENU_DESELECT"
GType matenu_background_type_get_type (void) G_GNUC_CONST;
GType matenu_gravity_get_type (void) G_GNUC_CONST;
double matenu_gravity_to_text_angle (MatenuGravity g);
GtkArrowType matenu_gravity_to_arrow_type (MatenuGravity g);



GType matenu_background_type_get_type (void) {
	static volatile gsize matenu_background_type_type_id__volatile = 0;
	if (g_once_init_enter (&matenu_background_type_type_id__volatile)) {
		static const GEnumValue values[] = {{MATENU_BACKGROUND_TYPE_NONE, "MATENU_BACKGROUND_TYPE_NONE", "none"}, {MATENU_BACKGROUND_TYPE_COLOR, "MATENU_BACKGROUND_TYPE_COLOR", "color"}, {MATENU_BACKGROUND_TYPE_PIXMAP, "MATENU_BACKGROUND_TYPE_PIXMAP", "pixmap"}, {0, NULL, NULL}};
		GType matenu_background_type_type_id;
		matenu_background_type_type_id = g_enum_register_static ("MatenuBackgroundType", values);
		g_once_init_leave (&matenu_background_type_type_id__volatile, matenu_background_type_type_id);
	}
	return matenu_background_type_type_id__volatile;
}


GType matenu_gravity_get_type (void) {
	static volatile gsize matenu_gravity_type_id__volatile = 0;
	if (g_once_init_enter (&matenu_gravity_type_id__volatile)) {
		static const GEnumValue values[] = {{MATENU_GRAVITY_DOWN, "MATENU_GRAVITY_DOWN", "down"}, {MATENU_GRAVITY_UP, "MATENU_GRAVITY_UP", "up"}, {MATENU_GRAVITY_LEFT, "MATENU_GRAVITY_LEFT", "left"}, {MATENU_GRAVITY_RIGHT, "MATENU_GRAVITY_RIGHT", "right"}, {0, NULL, NULL}};
		GType matenu_gravity_type_id;
		matenu_gravity_type_id = g_enum_register_static ("MatenuGravity", values);
		g_once_init_leave (&matenu_gravity_type_id__volatile, matenu_gravity_type_id);
	}
	return matenu_gravity_type_id__volatile;
}


double matenu_gravity_to_text_angle (MatenuGravity g) {
	double result = 0.0;
	switch (g) {
		case MATENU_GRAVITY_UP:
		{
			result = (double) 180;
			return result;
		}
		case MATENU_GRAVITY_LEFT:
		{
			result = (double) 270;
			return result;
		}
		case MATENU_GRAVITY_RIGHT:
		{
			result = (double) 90;
			return result;
		}
		default:
		{
			result = (double) 0;
			return result;
		}
	}
}


GtkArrowType matenu_gravity_to_arrow_type (MatenuGravity g) {
	GtkArrowType result = 0;
	switch (g) {
		case MATENU_GRAVITY_UP:
		{
			result = GTK_ARROW_UP;
			return result;
		}
		case MATENU_GRAVITY_LEFT:
		{
			result = GTK_ARROW_LEFT;
			return result;
		}
		case MATENU_GRAVITY_RIGHT:
		{
			result = GTK_ARROW_RIGHT;
			return result;
		}
		default:
		{
			result = GTK_ARROW_DOWN;
			return result;
		}
	}
}




