/* globalmenuitem.c generated by valac, the Vala compiler
 * generated from globalmenuitem.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>


#define MATENU_TYPE_GLOBAL_MENU_ITEM (matenu_global_menu_item_get_type ())
#define MATENU_GLOBAL_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_GLOBAL_MENU_ITEM, MatenuGlobalMenuItem))
#define MATENU_GLOBAL_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_GLOBAL_MENU_ITEM, MatenuGlobalMenuItemClass))
#define MATENU_IS_GLOBAL_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_GLOBAL_MENU_ITEM))
#define MATENU_IS_GLOBAL_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_GLOBAL_MENU_ITEM))
#define MATENU_GLOBAL_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_GLOBAL_MENU_ITEM, MatenuGlobalMenuItemClass))

typedef struct _MatenuGlobalMenuItem MatenuGlobalMenuItem;
typedef struct _MatenuGlobalMenuItemClass MatenuGlobalMenuItemClass;
typedef struct _MatenuGlobalMenuItemPrivate MatenuGlobalMenuItemPrivate;

#define MATENU_TYPE_MONITOR (matenu_monitor_get_type ())
#define MATENU_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MONITOR, MatenuMonitor))
#define MATENU_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MONITOR, MatenuMonitorClass))
#define MATENU_IS_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MONITOR))
#define MATENU_IS_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MONITOR))
#define MATENU_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MONITOR, MatenuMonitorClass))

typedef struct _MatenuMonitor MatenuMonitor;
typedef struct _MatenuMonitorClass MatenuMonitorClass;

#define MATENU_TYPE_MENU (matenu_menu_get_type ())
#define MATENU_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU, MatenuMenu))
#define MATENU_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU, MatenuMenuClass))
#define MATENU_IS_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU))
#define MATENU_IS_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU))
#define MATENU_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU, MatenuMenuClass))

typedef struct _MatenuMenu MatenuMenu;
typedef struct _MatenuMenuClass MatenuMenuClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define MATENU_TYPE_WINDOW (matenu_window_get_type ())
#define MATENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_WINDOW, MatenuWindow))
#define MATENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_WINDOW, MatenuWindowClass))
#define MATENU_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_WINDOW))
#define MATENU_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_WINDOW))
#define MATENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_WINDOW, MatenuWindowClass))

typedef struct _MatenuWindow MatenuWindow;
typedef struct _MatenuWindowClass MatenuWindowClass;

#define MATENU_TYPE_ITEM (matenu_item_get_type ())
#define MATENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_ITEM, MatenuItem))
#define MATENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_ITEM))
#define MATENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_ITEM, MatenuItemIface))

typedef struct _MatenuItem MatenuItem;
typedef struct _MatenuItemIface MatenuItemIface;

#define MATENU_TYPE_SHELL (matenu_shell_get_type ())
#define MATENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_SHELL, MatenuShell))
#define MATENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_SHELL))
#define MATENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_SHELL, MatenuShellIface))

typedef struct _MatenuShell MatenuShell;
typedef struct _MatenuShellIface MatenuShellIface;

#define MATENU_TYPE_ITEM_TYPE (matenu_item_type_get_type ())

#define MATENU_TYPE_ITEM_STATE (matenu_item_state_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

struct _MatenuGlobalMenuItem {
	GtkMenuItem parent_instance;
	MatenuGlobalMenuItemPrivate * priv;
};

struct _MatenuGlobalMenuItemClass {
	GtkMenuItemClass parent_class;
};

struct _MatenuGlobalMenuItemPrivate {
	MatenuMonitor* active_window_monitor;
	MatenuMenu* main_shell;
};

struct _MatenuShellIface {
	GTypeInterface parent_iface;
	MatenuItem* (*get_item) (MatenuShell* self, gint position);
	MatenuItem* (*get_item_by_id) (MatenuShell* self, const char* id);
	gint (*get_item_position) (MatenuShell* self, MatenuItem* item);
	MatenuItem* (*get_owner) (MatenuShell* self);
	gint (*get_length) (MatenuShell* self);
	void (*set_length) (MatenuShell* self, gint value);
};

typedef enum  {
	MATENU_ITEM_TYPE_NORMAL = 0,
	MATENU_ITEM_TYPE_CHECK = 1,
	MATENU_ITEM_TYPE_RADIO = 2,
	MATENU_ITEM_TYPE_IMAGE = 3,
	MATENU_ITEM_TYPE_SEPARATOR = 4,
	MATENU_ITEM_TYPE_ARROW = 5,
	MATENU_ITEM_TYPE_ICON = 6
} MatenuItemType;

typedef enum  {
	MATENU_ITEM_STATE_UNTOGGLED = 0,
	MATENU_ITEM_STATE_TOGGLED = 1,
	MATENU_ITEM_STATE_TRISTATE = 2
} MatenuItemState;

struct _MatenuItemIface {
	GTypeInterface parent_iface;
	MatenuShell* (*get_shell) (MatenuItem* self);
	MatenuShell* (*get_sub_shell) (MatenuItem* self);
	gboolean (*get_has_sub_shell) (MatenuItem* self);
	void (*set_has_sub_shell) (MatenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (MatenuItem* self);
	void (*set_client_side_sub_shell) (MatenuItem* self, gboolean value);
	const char* (*get_item_id) (MatenuItem* self);
	void (*set_item_id) (MatenuItem* self, const char* value);
	MatenuItemType (*get_item_type) (MatenuItem* self);
	void (*set_item_type) (MatenuItem* self, MatenuItemType value);
	gboolean (*get_item_use_underline) (MatenuItem* self);
	void (*set_item_use_underline) (MatenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (MatenuItem* self);
	void (*set_item_sensitive) (MatenuItem* self, gboolean value);
	gboolean (*get_item_visible) (MatenuItem* self);
	void (*set_item_visible) (MatenuItem* self, gboolean value);
	MatenuItemState (*get_item_state) (MatenuItem* self);
	void (*set_item_state) (MatenuItem* self, MatenuItemState value);
	const char* (*get_item_label) (MatenuItem* self);
	void (*set_item_label) (MatenuItem* self, const char* value);
	const char* (*get_item_icon) (MatenuItem* self);
	void (*set_item_icon) (MatenuItem* self, const char* value);
	const char* (*get_item_accel_text) (MatenuItem* self);
	void (*set_item_accel_text) (MatenuItem* self, const char* value);
	const char* (*get_item_font) (MatenuItem* self);
	void (*set_item_font) (MatenuItem* self, const char* value);
};


static gpointer matenu_global_menu_item_parent_class = NULL;

GType matenu_global_menu_item_get_type (void) G_GNUC_CONST;
GType matenu_monitor_get_type (void) G_GNUC_CONST;
GType matenu_menu_get_type (void) G_GNUC_CONST;
#define MATENU_GLOBAL_MENU_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MATENU_TYPE_GLOBAL_MENU_ITEM, MatenuGlobalMenuItemPrivate))
enum  {
	MATENU_GLOBAL_MENU_ITEM_DUMMY_PROPERTY,
	MATENU_GLOBAL_MENU_ITEM_PER_MONITOR_MODE,
	MATENU_GLOBAL_MENU_ITEM_ACTIVE_WINDOW
};
GType matenu_window_get_type (void) G_GNUC_CONST;
static void matenu_global_menu_item_emit_active_window_changed (MatenuGlobalMenuItem* self, MatenuWindow* prev_window);
MatenuWindow* matenu_global_menu_item_get_active_window (MatenuGlobalMenuItem* self);
void matenu_window_emit_menu_event (MatenuWindow* self, const char* path);
GType matenu_shell_get_type (void) G_GNUC_CONST;
GType matenu_item_type_get_type (void) G_GNUC_CONST;
GType matenu_item_state_get_type (void) G_GNUC_CONST;
GType matenu_item_get_type (void) G_GNUC_CONST;
char* matenu_item_get_item_path (MatenuItem* self);
static void matenu_global_menu_item_item_activated (MatenuGlobalMenuItem* self, MatenuItem* item);
void matenu_window_emit_menu_select (MatenuWindow* self, const char* path, const char* pos);
static void matenu_global_menu_item_item_selected (MatenuGlobalMenuItem* self, MatenuItem* item);
void matenu_window_emit_menu_deselect (MatenuWindow* self, const char* path);
static void matenu_global_menu_item_item_deselected (MatenuGlobalMenuItem* self, MatenuItem* item);
static gboolean matenu_global_menu_item_sync_monitor_num (MatenuGlobalMenuItem* self);
static gboolean _matenu_global_menu_item_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self);
static void _matenu_global_menu_item_hierarchy_changed (MatenuGlobalMenuItem* self, GtkWidget* old_toplevel);
void matenu_monitor_set_monitor_num (MatenuMonitor* self, gint value);
MatenuGlobalMenuItem* matenu_global_menu_item_new (void);
MatenuGlobalMenuItem* matenu_global_menu_item_construct (GType object_type);
gboolean matenu_monitor_get_per_monitor_mode (MatenuMonitor* self);
gboolean matenu_global_menu_item_get_per_monitor_mode (MatenuGlobalMenuItem* self);
void matenu_monitor_set_per_monitor_mode (MatenuMonitor* self, gboolean value);
void matenu_global_menu_item_set_per_monitor_mode (MatenuGlobalMenuItem* self, gboolean value);
MatenuWindow* matenu_monitor_get_active_window (MatenuMonitor* self);
MatenuMonitor* matenu_monitor_new (GdkScreen* screen);
MatenuMonitor* matenu_monitor_construct (GType object_type, GdkScreen* screen);
void matenu_monitor_set_managed_shell (MatenuMonitor* self, MatenuShell* value);
static void _matenu_global_menu_item_emit_active_window_changed_matenu_monitor_active_window_changed (MatenuMonitor* _sender, MatenuWindow* prev_window, gpointer self);
MatenuMenu* matenu_menu_new (void);
MatenuMenu* matenu_menu_construct (GType object_type);
void matenu_menu_set_is_topmost (MatenuMenu* self, gboolean value);
static void _matenu_global_menu_item_item_activated_matenu_shell_activate (MatenuMenu* _sender, MatenuItem* item, gpointer self);
static void _matenu_global_menu_item_item_selected_matenu_shell_select (MatenuMenu* _sender, MatenuItem* item, gpointer self);
static void _matenu_global_menu_item_item_deselected_matenu_shell_deselect (MatenuMenu* _sender, MatenuItem* item, gpointer self);
static void __matenu_global_menu_item_hierarchy_changed_gtk_widget_hierarchy_changed (MatenuGlobalMenuItem* _sender, GtkWidget* previous_toplevel, gpointer self);
void matenu_monitor_rebuild_shell (MatenuMonitor* self, MatenuShell* shell);
static void _lambda2_ (MatenuGlobalMenuItem* self);
static void __lambda2__gtk_menu_item_activate (MatenuGlobalMenuItem* _sender, gpointer self);
static GObject * matenu_global_menu_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void matenu_global_menu_item_finalize (GObject* obj);
static void matenu_global_menu_item_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void matenu_global_menu_item_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



static void matenu_global_menu_item_emit_active_window_changed (MatenuGlobalMenuItem* self, MatenuWindow* prev_window) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "active-window-changed", prev_window);
}


static void matenu_global_menu_item_item_activated (MatenuGlobalMenuItem* self, MatenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (matenu_global_menu_item_get_active_window (self) != NULL) {
		char* _tmp0_;
		matenu_window_emit_menu_event (matenu_global_menu_item_get_active_window (self), _tmp0_ = matenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static void matenu_global_menu_item_item_selected (MatenuGlobalMenuItem* self, MatenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (matenu_global_menu_item_get_active_window (self) != NULL) {
		char* _tmp0_;
		matenu_window_emit_menu_select (matenu_global_menu_item_get_active_window (self), _tmp0_ = matenu_item_get_item_path (item), NULL);
		_g_free0 (_tmp0_);
	}
}


static void matenu_global_menu_item_item_deselected (MatenuGlobalMenuItem* self, MatenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (matenu_global_menu_item_get_active_window (self) != NULL) {
		char* _tmp0_;
		matenu_window_emit_menu_deselect (matenu_global_menu_item_get_active_window (self), _tmp0_ = matenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean _matenu_global_menu_item_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self) {
	gboolean result;
	result = matenu_global_menu_item_sync_monitor_num (self);
	return result;
}


static void _matenu_global_menu_item_hierarchy_changed (MatenuGlobalMenuItem* self, GtkWidget* old_toplevel) {
	GtkWidget* _tmp0_;
	GtkPlug* toplevel;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 ((_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self), GTK_IS_PLUG (_tmp0_) ? ((GtkPlug*) _tmp0_) : NULL));
	if (toplevel != NULL) {
		g_signal_connect_object ((GtkWidget*) toplevel, "configure-event", (GCallback) _matenu_global_menu_item_sync_monitor_num_gtk_widget_configure_event, self, 0);
	}
	if (old_toplevel != NULL) {
		guint _tmp1_;
		g_signal_parse_name ("configure-event", GTK_TYPE_WIDGET, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (old_toplevel, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _matenu_global_menu_item_sync_monitor_num_gtk_widget_configure_event, self);
	}
	_g_object_unref0 (toplevel);
}


static gboolean matenu_global_menu_item_sync_monitor_num (MatenuGlobalMenuItem* self) {
	gboolean result = FALSE;
	GdkScreen* screen;
	g_return_val_if_fail (self != NULL, FALSE);
	screen = _g_object_ref0 (gtk_widget_get_screen ((GtkWidget*) self));
	if (GTK_WIDGET_REALIZED ((GtkWidget*) self)) {
		matenu_monitor_set_monitor_num (self->priv->active_window_monitor, gdk_screen_get_monitor_at_window (screen, ((GtkWidget*) self)->window));
	} else {
		matenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
	}
	result = FALSE;
	_g_object_unref0 (screen);
	return result;
}


MatenuGlobalMenuItem* matenu_global_menu_item_construct (GType object_type) {
	MatenuGlobalMenuItem * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


MatenuGlobalMenuItem* matenu_global_menu_item_new (void) {
	return matenu_global_menu_item_construct (MATENU_TYPE_GLOBAL_MENU_ITEM);
}


gboolean matenu_global_menu_item_get_per_monitor_mode (MatenuGlobalMenuItem* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = matenu_monitor_get_per_monitor_mode (self->priv->active_window_monitor);
	return result;
}


void matenu_global_menu_item_set_per_monitor_mode (MatenuGlobalMenuItem* self, gboolean value) {
	g_return_if_fail (self != NULL);
	matenu_monitor_set_per_monitor_mode (self->priv->active_window_monitor, value);
	g_object_notify ((GObject *) self, "per-monitor-mode");
}


MatenuWindow* matenu_global_menu_item_get_active_window (MatenuGlobalMenuItem* self) {
	MatenuWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = matenu_monitor_get_active_window (self->priv->active_window_monitor);
	return result;
}


static void _matenu_global_menu_item_emit_active_window_changed_matenu_monitor_active_window_changed (MatenuMonitor* _sender, MatenuWindow* prev_window, gpointer self) {
	matenu_global_menu_item_emit_active_window_changed (self, prev_window);
}


static void _matenu_global_menu_item_item_activated_matenu_shell_activate (MatenuMenu* _sender, MatenuItem* item, gpointer self) {
	matenu_global_menu_item_item_activated (self, item);
}


static void _matenu_global_menu_item_item_selected_matenu_shell_select (MatenuMenu* _sender, MatenuItem* item, gpointer self) {
	matenu_global_menu_item_item_selected (self, item);
}


static void _matenu_global_menu_item_item_deselected_matenu_shell_deselect (MatenuMenu* _sender, MatenuItem* item, gpointer self) {
	matenu_global_menu_item_item_deselected (self, item);
}


static void __matenu_global_menu_item_hierarchy_changed_gtk_widget_hierarchy_changed (MatenuGlobalMenuItem* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_matenu_global_menu_item_hierarchy_changed (self, previous_toplevel);
}


static void _lambda2_ (MatenuGlobalMenuItem* self) {
	matenu_monitor_rebuild_shell (self->priv->active_window_monitor, (MatenuShell*) self->priv->main_shell);
}


static void __lambda2__gtk_menu_item_activate (MatenuGlobalMenuItem* _sender, gpointer self) {
	_lambda2_ (self);
}


static GObject * matenu_global_menu_item_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MatenuGlobalMenuItem * self;
	parent_class = G_OBJECT_CLASS (matenu_global_menu_item_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MATENU_GLOBAL_MENU_ITEM (obj);
	{
		MatenuMonitor* _tmp0_;
		MatenuMenu* _tmp1_;
		gtk_menu_item_set_label ((GtkMenuItem*) self, _ ("Menu"));
		self->priv->active_window_monitor = (_tmp0_ = matenu_monitor_new (gtk_widget_get_screen ((GtkWidget*) self)), _g_object_unref0 (self->priv->active_window_monitor), _tmp0_);
		matenu_monitor_set_managed_shell (self->priv->active_window_monitor, NULL);
		matenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-changed", (GCallback) _matenu_global_menu_item_emit_active_window_changed_matenu_monitor_active_window_changed, self, 0);
		self->priv->main_shell = (_tmp1_ = g_object_ref_sink (matenu_menu_new ()), _g_object_unref0 (self->priv->main_shell), _tmp1_);
		gtk_menu_item_set_submenu ((GtkMenuItem*) self, (GtkMenu*) self->priv->main_shell);
		matenu_menu_set_is_topmost (self->priv->main_shell, TRUE);
		g_signal_connect_object ((MatenuShell*) self->priv->main_shell, "activate", (GCallback) _matenu_global_menu_item_item_activated_matenu_shell_activate, self, 0);
		g_signal_connect_object ((MatenuShell*) self->priv->main_shell, "select", (GCallback) _matenu_global_menu_item_item_selected_matenu_shell_select, self, 0);
		g_signal_connect_object ((MatenuShell*) self->priv->main_shell, "deselect", (GCallback) _matenu_global_menu_item_item_deselected_matenu_shell_deselect, self, 0);
		g_signal_connect_object ((GtkWidget*) self, "hierarchy-changed", (GCallback) __matenu_global_menu_item_hierarchy_changed_gtk_widget_hierarchy_changed, self, 0);
		g_signal_connect_object ((GtkMenuItem*) self, "activate", (GCallback) __lambda2__gtk_menu_item_activate, self, 0);
	}
	return obj;
}


static void matenu_global_menu_item_class_init (MatenuGlobalMenuItemClass * klass) {
	matenu_global_menu_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MatenuGlobalMenuItemPrivate));
	G_OBJECT_CLASS (klass)->get_property = matenu_global_menu_item_get_property;
	G_OBJECT_CLASS (klass)->set_property = matenu_global_menu_item_set_property;
	G_OBJECT_CLASS (klass)->constructor = matenu_global_menu_item_constructor;
	G_OBJECT_CLASS (klass)->finalize = matenu_global_menu_item_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_GLOBAL_MENU_ITEM_PER_MONITOR_MODE, g_param_spec_boolean ("per-monitor-mode", "per-monitor-mode", "per-monitor-mode", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_GLOBAL_MENU_ITEM_ACTIVE_WINDOW, g_param_spec_object ("active-window", "active-window", "active-window", MATENU_TYPE_WINDOW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("active_window_changed", MATENU_TYPE_GLOBAL_MENU_ITEM, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, MATENU_TYPE_WINDOW);
}


static void matenu_global_menu_item_instance_init (MatenuGlobalMenuItem * self) {
	self->priv = MATENU_GLOBAL_MENU_ITEM_GET_PRIVATE (self);
	self->priv->main_shell = NULL;
}


static void matenu_global_menu_item_finalize (GObject* obj) {
	MatenuGlobalMenuItem * self;
	self = MATENU_GLOBAL_MENU_ITEM (obj);
	_g_object_unref0 (self->priv->active_window_monitor);
	_g_object_unref0 (self->priv->main_shell);
	G_OBJECT_CLASS (matenu_global_menu_item_parent_class)->finalize (obj);
}


GType matenu_global_menu_item_get_type (void) {
	static volatile gsize matenu_global_menu_item_type_id__volatile = 0;
	if (g_once_init_enter (&matenu_global_menu_item_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MatenuGlobalMenuItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) matenu_global_menu_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MatenuGlobalMenuItem), 0, (GInstanceInitFunc) matenu_global_menu_item_instance_init, NULL };
		GType matenu_global_menu_item_type_id;
		matenu_global_menu_item_type_id = g_type_register_static (GTK_TYPE_MENU_ITEM, "MatenuGlobalMenuItem", &g_define_type_info, 0);
		g_once_init_leave (&matenu_global_menu_item_type_id__volatile, matenu_global_menu_item_type_id);
	}
	return matenu_global_menu_item_type_id__volatile;
}


static void matenu_global_menu_item_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MatenuGlobalMenuItem * self;
	self = MATENU_GLOBAL_MENU_ITEM (object);
	switch (property_id) {
		case MATENU_GLOBAL_MENU_ITEM_PER_MONITOR_MODE:
		g_value_set_boolean (value, matenu_global_menu_item_get_per_monitor_mode (self));
		break;
		case MATENU_GLOBAL_MENU_ITEM_ACTIVE_WINDOW:
		g_value_set_object (value, matenu_global_menu_item_get_active_window (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void matenu_global_menu_item_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MatenuGlobalMenuItem * self;
	self = MATENU_GLOBAL_MENU_ITEM (object);
	switch (property_id) {
		case MATENU_GLOBAL_MENU_ITEM_PER_MONITOR_MODE:
		matenu_global_menu_item_set_per_monitor_mode (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




