/* globalmenu-server.h generated by valac, the Vala compiler, do not modify */


#ifndef __GLOBALMENU_SERVER_H__
#define __GLOBALMENU_SERVER_H__

#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>

G_BEGIN_DECLS


#define MATENU_TYPE_SHELL (matenu_shell_get_type ())
#define MATENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_SHELL, MatenuShell))
#define MATENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_SHELL))
#define MATENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_SHELL, MatenuShellIface))

typedef struct _MatenuShell MatenuShell;
typedef struct _MatenuShellIface MatenuShellIface;

#define MATENU_TYPE_ITEM (matenu_item_get_type ())
#define MATENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_ITEM, MatenuItem))
#define MATENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_ITEM))
#define MATENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_ITEM, MatenuItemIface))

typedef struct _MatenuItem MatenuItem;
typedef struct _MatenuItemIface MatenuItemIface;

#define MATENU_TYPE_ITEM_TYPE (matenu_item_type_get_type ())

#define MATENU_TYPE_ITEM_STATE (matenu_item_state_get_type ())

#define MATENU_TYPE_MENU_BAR (matenu_menu_bar_get_type ())
#define MATENU_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_BAR, MatenuMenuBar))
#define MATENU_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_BAR, MatenuMenuBarClass))
#define MATENU_IS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_BAR))
#define MATENU_IS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_BAR))
#define MATENU_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_BAR, MatenuMenuBarClass))

typedef struct _MatenuMenuBar MatenuMenuBar;
typedef struct _MatenuMenuBarClass MatenuMenuBarClass;
typedef struct _MatenuMenuBarPrivate MatenuMenuBarPrivate;

#define MATENU_TYPE_GLOBAL_MENU_BAR (matenu_global_menu_bar_get_type ())
#define MATENU_GLOBAL_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_GLOBAL_MENU_BAR, MatenuGlobalMenuBar))
#define MATENU_GLOBAL_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_GLOBAL_MENU_BAR, MatenuGlobalMenuBarClass))
#define MATENU_IS_GLOBAL_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_GLOBAL_MENU_BAR))
#define MATENU_IS_GLOBAL_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_GLOBAL_MENU_BAR))
#define MATENU_GLOBAL_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_GLOBAL_MENU_BAR, MatenuGlobalMenuBarClass))

typedef struct _MatenuGlobalMenuBar MatenuGlobalMenuBar;
typedef struct _MatenuGlobalMenuBarClass MatenuGlobalMenuBarClass;
typedef struct _MatenuGlobalMenuBarPrivate MatenuGlobalMenuBarPrivate;

#define MATENU_TYPE_WINDOW (matenu_window_get_type ())
#define MATENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_WINDOW, MatenuWindow))
#define MATENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_WINDOW, MatenuWindowClass))
#define MATENU_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_WINDOW))
#define MATENU_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_WINDOW))
#define MATENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_WINDOW, MatenuWindowClass))

typedef struct _MatenuWindow MatenuWindow;
typedef struct _MatenuWindowClass MatenuWindowClass;

#define MATENU_TYPE_GLOBAL_MENU_ITEM (matenu_global_menu_item_get_type ())
#define MATENU_GLOBAL_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_GLOBAL_MENU_ITEM, MatenuGlobalMenuItem))
#define MATENU_GLOBAL_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_GLOBAL_MENU_ITEM, MatenuGlobalMenuItemClass))
#define MATENU_IS_GLOBAL_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_GLOBAL_MENU_ITEM))
#define MATENU_IS_GLOBAL_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_GLOBAL_MENU_ITEM))
#define MATENU_GLOBAL_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_GLOBAL_MENU_ITEM, MatenuGlobalMenuItemClass))

typedef struct _MatenuGlobalMenuItem MatenuGlobalMenuItem;
typedef struct _MatenuGlobalMenuItemClass MatenuGlobalMenuItemClass;
typedef struct _MatenuGlobalMenuItemPrivate MatenuGlobalMenuItemPrivate;

#define MATENU_TYPE_ADAPTER (matenu_adapter_get_type ())
#define MATENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_ADAPTER, MatenuAdapter))
#define MATENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_ADAPTER, MatenuAdapterClass))
#define MATENU_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_ADAPTER))
#define MATENU_IS_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_ADAPTER))
#define MATENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_ADAPTER, MatenuAdapterClass))

typedef struct _MatenuAdapter MatenuAdapter;
typedef struct _MatenuAdapterClass MatenuAdapterClass;
typedef struct _MatenuAdapterPrivate MatenuAdapterPrivate;

#define MATENU_TYPE_GLOBAL_MENU_ADAPTER (matenu_global_menu_adapter_get_type ())
#define MATENU_GLOBAL_MENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_GLOBAL_MENU_ADAPTER, MatenuGlobalMenuAdapter))
#define MATENU_GLOBAL_MENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_GLOBAL_MENU_ADAPTER, MatenuGlobalMenuAdapterClass))
#define MATENU_IS_GLOBAL_MENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_GLOBAL_MENU_ADAPTER))
#define MATENU_IS_GLOBAL_MENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_GLOBAL_MENU_ADAPTER))
#define MATENU_GLOBAL_MENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_GLOBAL_MENU_ADAPTER, MatenuGlobalMenuAdapterClass))

typedef struct _MatenuGlobalMenuAdapter MatenuGlobalMenuAdapter;
typedef struct _MatenuGlobalMenuAdapterClass MatenuGlobalMenuAdapterClass;
typedef struct _MatenuGlobalMenuAdapterPrivate MatenuGlobalMenuAdapterPrivate;

#define MATENU_TYPE_BACKGROUND_TYPE (matenu_background_type_get_type ())

#define MATENU_TYPE_GRAVITY (matenu_gravity_get_type ())
typedef struct _MatenuWindowPrivate MatenuWindowPrivate;

#define MATENU_TYPE_PARSER (matenu_parser_get_type ())
#define MATENU_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_PARSER, MatenuParser))
#define MATENU_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_PARSER, MatenuParserClass))
#define MATENU_IS_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_PARSER))
#define MATENU_IS_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_PARSER))
#define MATENU_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_PARSER, MatenuParserClass))

typedef struct _MatenuParser MatenuParser;
typedef struct _MatenuParserClass MatenuParserClass;
typedef struct _MatenuParserPrivate MatenuParserPrivate;

#define MATENU_TYPE_SERIALIZER (matenu_serializer_get_type ())
#define MATENU_SERIALIZER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_SERIALIZER, MatenuSerializer))
#define MATENU_SERIALIZER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_SERIALIZER, MatenuSerializerClass))
#define MATENU_IS_SERIALIZER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_SERIALIZER))
#define MATENU_IS_SERIALIZER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_SERIALIZER))
#define MATENU_SERIALIZER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_SERIALIZER, MatenuSerializerClass))

typedef struct _MatenuSerializer MatenuSerializer;
typedef struct _MatenuSerializerClass MatenuSerializerClass;
typedef struct _MatenuSerializerPrivate MatenuSerializerPrivate;

#define MATENU_TYPE_MENU (matenu_menu_get_type ())
#define MATENU_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU, MatenuMenu))
#define MATENU_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU, MatenuMenuClass))
#define MATENU_IS_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU))
#define MATENU_IS_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU))
#define MATENU_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU, MatenuMenuClass))

typedef struct _MatenuMenu MatenuMenu;
typedef struct _MatenuMenuClass MatenuMenuClass;
typedef struct _MatenuMenuPrivate MatenuMenuPrivate;

#define MATENU_TYPE_BACKGROUND (matenu_background_get_type ())
#define MATENU_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_BACKGROUND, MatenuBackground))
#define MATENU_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_BACKGROUND, MatenuBackgroundClass))
#define MATENU_IS_BACKGROUND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_BACKGROUND))
#define MATENU_IS_BACKGROUND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_BACKGROUND))
#define MATENU_BACKGROUND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_BACKGROUND, MatenuBackgroundClass))

typedef struct _MatenuBackground MatenuBackground;
typedef struct _MatenuBackgroundClass MatenuBackgroundClass;
typedef struct _MatenuBackgroundPrivate MatenuBackgroundPrivate;

#define MATENU_TYPE_MENU_ITEM (matenu_menu_item_get_type ())
#define MATENU_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_ITEM, MatenuMenuItem))
#define MATENU_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_ITEM, MatenuMenuItemClass))
#define MATENU_IS_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_ITEM))
#define MATENU_IS_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_ITEM))
#define MATENU_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_ITEM, MatenuMenuItemClass))

typedef struct _MatenuMenuItem MatenuMenuItem;
typedef struct _MatenuMenuItemClass MatenuMenuItemClass;
typedef struct _MatenuMenuItemPrivate MatenuMenuItemPrivate;

#define MATENU_TYPE_MENU_BAR_BOX (matenu_menu_bar_box_get_type ())
#define MATENU_MENU_BAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_BAR_BOX, MatenuMenuBarBox))
#define MATENU_MENU_BAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_BAR_BOX, MatenuMenuBarBoxClass))
#define MATENU_IS_MENU_BAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_BAR_BOX))
#define MATENU_IS_MENU_BAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_BAR_BOX))
#define MATENU_MENU_BAR_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_BAR_BOX, MatenuMenuBarBoxClass))

typedef struct _MatenuMenuBarBox MatenuMenuBarBox;
typedef struct _MatenuMenuBarBoxClass MatenuMenuBarBoxClass;
typedef struct _MatenuMenuBarBoxPrivate MatenuMenuBarBoxPrivate;

#define MATENU_TYPE_MENU_LABEL (matenu_menu_label_get_type ())
#define MATENU_MENU_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MENU_LABEL, MatenuMenuLabel))
#define MATENU_MENU_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MENU_LABEL, MatenuMenuLabelClass))
#define MATENU_IS_MENU_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MENU_LABEL))
#define MATENU_IS_MENU_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MENU_LABEL))
#define MATENU_MENU_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MENU_LABEL, MatenuMenuLabelClass))

typedef struct _MatenuMenuLabel MatenuMenuLabel;
typedef struct _MatenuMenuLabelClass MatenuMenuLabelClass;
typedef struct _MatenuMenuLabelPrivate MatenuMenuLabelPrivate;

typedef enum  {
	MATENU_ITEM_TYPE_NORMAL = 0,
	MATENU_ITEM_TYPE_CHECK = 1,
	MATENU_ITEM_TYPE_RADIO = 2,
	MATENU_ITEM_TYPE_IMAGE = 3,
	MATENU_ITEM_TYPE_SEPARATOR = 4,
	MATENU_ITEM_TYPE_ARROW = 5,
	MATENU_ITEM_TYPE_ICON = 6
} MatenuItemType;

typedef enum  {
	MATENU_ITEM_STATE_UNTOGGLED = 0,
	MATENU_ITEM_STATE_TOGGLED = 1,
	MATENU_ITEM_STATE_TRISTATE = 2
} MatenuItemState;

struct _MatenuItemIface {
	GTypeInterface parent_iface;
	MatenuShell* (*get_shell) (MatenuItem* self);
	MatenuShell* (*get_sub_shell) (MatenuItem* self);
	gboolean (*get_has_sub_shell) (MatenuItem* self);
	void (*set_has_sub_shell) (MatenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (MatenuItem* self);
	void (*set_client_side_sub_shell) (MatenuItem* self, gboolean value);
	const char* (*get_item_id) (MatenuItem* self);
	void (*set_item_id) (MatenuItem* self, const char* value);
	MatenuItemType (*get_item_type) (MatenuItem* self);
	void (*set_item_type) (MatenuItem* self, MatenuItemType value);
	gboolean (*get_item_use_underline) (MatenuItem* self);
	void (*set_item_use_underline) (MatenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (MatenuItem* self);
	void (*set_item_sensitive) (MatenuItem* self, gboolean value);
	gboolean (*get_item_visible) (MatenuItem* self);
	void (*set_item_visible) (MatenuItem* self, gboolean value);
	MatenuItemState (*get_item_state) (MatenuItem* self);
	void (*set_item_state) (MatenuItem* self, MatenuItemState value);
	const char* (*get_item_label) (MatenuItem* self);
	void (*set_item_label) (MatenuItem* self, const char* value);
	const char* (*get_item_icon) (MatenuItem* self);
	void (*set_item_icon) (MatenuItem* self, const char* value);
	const char* (*get_item_accel_text) (MatenuItem* self);
	void (*set_item_accel_text) (MatenuItem* self, const char* value);
	const char* (*get_item_font) (MatenuItem* self);
	void (*set_item_font) (MatenuItem* self, const char* value);
};

struct _MatenuShellIface {
	GTypeInterface parent_iface;
	MatenuItem* (*get_item) (MatenuShell* self, gint position);
	MatenuItem* (*get_item_by_id) (MatenuShell* self, const char* id);
	gint (*get_item_position) (MatenuShell* self, MatenuItem* item);
	MatenuItem* (*get_owner) (MatenuShell* self);
	gint (*get_length) (MatenuShell* self);
	void (*set_length) (MatenuShell* self, gint value);
};

struct _MatenuMenuBar {
	GtkMenuBar parent_instance;
	MatenuMenuBarPrivate * priv;
};

struct _MatenuMenuBarClass {
	GtkMenuBarClass parent_class;
};

struct _MatenuGlobalMenuBar {
	MatenuMenuBar parent_instance;
	MatenuGlobalMenuBarPrivate * priv;
	gboolean _grab_menu_key;
};

struct _MatenuGlobalMenuBarClass {
	MatenuMenuBarClass parent_class;
};

struct _MatenuGlobalMenuItem {
	GtkMenuItem parent_instance;
	MatenuGlobalMenuItemPrivate * priv;
};

struct _MatenuGlobalMenuItemClass {
	GtkMenuItemClass parent_class;
};

struct _MatenuAdapter {
	GObject parent_instance;
	MatenuAdapterPrivate * priv;
};

struct _MatenuAdapterClass {
	GObjectClass parent_class;
};

struct _MatenuGlobalMenuAdapter {
	MatenuAdapter parent_instance;
	MatenuGlobalMenuAdapterPrivate * priv;
};

struct _MatenuGlobalMenuAdapterClass {
	MatenuAdapterClass parent_class;
};

typedef enum  {
	MATENU_BACKGROUND_TYPE_NONE = 0,
	MATENU_BACKGROUND_TYPE_COLOR = 1,
	MATENU_BACKGROUND_TYPE_PIXMAP = 2
} MatenuBackgroundType;

typedef enum  {
	MATENU_GRAVITY_DOWN = 0,
	MATENU_GRAVITY_UP = 1,
	MATENU_GRAVITY_LEFT = 2,
	MATENU_GRAVITY_RIGHT = 3
} MatenuGravity;

struct _MatenuWindow {
	GObject parent_instance;
	MatenuWindowPrivate * priv;
};

struct _MatenuWindowClass {
	GObjectClass parent_class;
	void (*property_notify_event) (MatenuWindow* self, const char* prop);
};

struct _MatenuParser {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MatenuParserPrivate * priv;
};

struct _MatenuParserClass {
	GTypeClass parent_class;
	void (*finalize) (MatenuParser *self);
};

struct _MatenuSerializer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MatenuSerializerPrivate * priv;
};

struct _MatenuSerializerClass {
	GTypeClass parent_class;
	void (*finalize) (MatenuSerializer *self);
};

struct _MatenuMenu {
	GtkMenu parent_instance;
	MatenuMenuPrivate * priv;
};

struct _MatenuMenuClass {
	GtkMenuClass parent_class;
};

struct _MatenuBackground {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MatenuBackgroundPrivate * priv;
	MatenuBackgroundType type;
	GdkPixmap* pixmap;
	GdkColor color;
	gint offset_x;
	gint offset_y;
};

struct _MatenuBackgroundClass {
	GTypeClass parent_class;
	void (*finalize) (MatenuBackground *self);
};

struct _MatenuMenuItem {
	GtkMenuItem parent_instance;
	MatenuMenuItemPrivate * priv;
	MatenuMenu* _submenu_cache;
};

struct _MatenuMenuItemClass {
	GtkMenuItemClass parent_class;
};

struct _MatenuMenuBarBox {
	GtkContainer parent_instance;
	MatenuMenuBarBoxPrivate * priv;
};

struct _MatenuMenuBarBoxClass {
	GtkContainerClass parent_class;
};

struct _MatenuMenuLabel {
	GtkContainer parent_instance;
	MatenuMenuLabelPrivate * priv;
};

struct _MatenuMenuLabelClass {
	GtkContainerClass parent_class;
};


GType matenu_item_type_get_type (void) G_GNUC_CONST;
GType matenu_item_state_get_type (void) G_GNUC_CONST;
GType matenu_item_get_type (void) G_GNUC_CONST;
GType matenu_shell_get_type (void) G_GNUC_CONST;
GType matenu_menu_bar_get_type (void) G_GNUC_CONST;
GType matenu_global_menu_bar_get_type (void) G_GNUC_CONST;
MatenuGlobalMenuBar* matenu_global_menu_bar_new (void);
MatenuGlobalMenuBar* matenu_global_menu_bar_construct (GType object_type);
gboolean matenu_global_menu_bar_get_per_monitor_mode (MatenuGlobalMenuBar* self);
void matenu_global_menu_bar_set_per_monitor_mode (MatenuGlobalMenuBar* self, gboolean value);
gboolean matenu_global_menu_bar_get_grab_keys (MatenuGlobalMenuBar* self);
void matenu_global_menu_bar_set_grab_keys (MatenuGlobalMenuBar* self, gboolean value);
gboolean matenu_global_menu_bar_get_grab_menu_key (MatenuGlobalMenuBar* self);
void matenu_global_menu_bar_set_grab_menu_key (MatenuGlobalMenuBar* self, gboolean value);
GType matenu_window_get_type (void) G_GNUC_CONST;
MatenuWindow* matenu_global_menu_bar_get_active_window (MatenuGlobalMenuBar* self);
GType matenu_global_menu_item_get_type (void) G_GNUC_CONST;
MatenuGlobalMenuItem* matenu_global_menu_item_new (void);
MatenuGlobalMenuItem* matenu_global_menu_item_construct (GType object_type);
gboolean matenu_global_menu_item_get_per_monitor_mode (MatenuGlobalMenuItem* self);
void matenu_global_menu_item_set_per_monitor_mode (MatenuGlobalMenuItem* self, gboolean value);
MatenuWindow* matenu_global_menu_item_get_active_window (MatenuGlobalMenuItem* self);
GType matenu_adapter_get_type (void) G_GNUC_CONST;
GType matenu_global_menu_adapter_get_type (void) G_GNUC_CONST;
MatenuGlobalMenuAdapter* matenu_global_menu_adapter_new (GtkMenuShell* gtk_shell);
MatenuGlobalMenuAdapter* matenu_global_menu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell);
MatenuWindow* matenu_global_menu_adapter_get_active_window (MatenuGlobalMenuAdapter* self);
MatenuAdapter* matenu_adapter_new (GtkMenuShell* gtk_shell);
MatenuAdapter* matenu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell);
MatenuAdapter* matenu_adapter_get_adapter (GtkMenuShell* gtk_shell);
GtkMenuShell* matenu_adapter_get_gtk_shell (MatenuAdapter* self);
void matenu_adapter_set_gtk_shell (MatenuAdapter* self, GtkMenuShell* value);
gboolean matenu_adapter_get_is_topmost (MatenuAdapter* self);
void matenu_adapter_set_is_topmost (MatenuAdapter* self, gboolean value);
#define MATENU_NET_GLOBALMENU_MENU_CONTEXT "_NET_GLOBALMENU_MENU_CONTEXT"
#define MATENU_NET_GLOBALMENU_MENU_EVENT "_NET_GLOBALMENU_MENU_EVENT"
#define MATENU_NET_GLOBALMENU_MENU_SELECT "_NET_GLOBALMENU_MENU_SELECT"
#define MATENU_NET_GLOBALMENU_MENU_DESELECT "_NET_GLOBALMENU_MENU_DESELECT"
GType matenu_background_type_get_type (void) G_GNUC_CONST;
GType matenu_gravity_get_type (void) G_GNUC_CONST;
gboolean matenu_window_is_on_active_workspace (MatenuWindow* self);
gint matenu_window_get_monitor_num (MatenuWindow* self);
guint matenu_window_get_xid (MatenuWindow* self);
MatenuWindow* matenu_window_new (GdkWindow* window);
MatenuWindow* matenu_window_construct (GType object_type, GdkWindow* window);
MatenuWindow* matenu_window_foreign_new (gulong xid);
void matenu_window_set_key_widget (MatenuWindow* self, GtkWidget* widget);
char* matenu_window_get (MatenuWindow* self, const char* property_name);
void matenu_window_set (MatenuWindow* self, const char* property_name, const char* value);
char* matenu_window_get_by_atom (MatenuWindow* self, GdkAtom atom);
void matenu_window_set_by_atom (MatenuWindow* self, GdkAtom atom, const char* value);
char* matenu_window_get_menu_context (MatenuWindow* self);
void matenu_window_set_menu_context (MatenuWindow* self, const char* value);
void matenu_window_emit_menu_event (MatenuWindow* self, const char* path);
void matenu_window_emit_menu_select (MatenuWindow* self, const char* path, const char* pos);
void matenu_window_emit_menu_deselect (MatenuWindow* self, const char* path);
gboolean matenu_window_grab_key (MatenuWindow* self, guint keyval, GdkModifierType state);
gboolean matenu_window_ungrab_key (MatenuWindow* self, guint keyval, GdkModifierType state);
GdkWindow* matenu_window_get_window (MatenuWindow* self);
void matenu_window_set_window (MatenuWindow* self, GdkWindow* value);
MatenuWindow* matenu_window_get_transient (MatenuWindow* self);
void matenu_window_set_transient (MatenuWindow* self, MatenuWindow* value);
void matenu_window_property_notify_event (MatenuWindow* self, const char* prop);
gpointer matenu_parser_ref (gpointer instance);
void matenu_parser_unref (gpointer instance);
GParamSpec* matenu_param_spec_parser (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void matenu_value_set_parser (GValue* value, gpointer v_object);
void matenu_value_take_parser (GValue* value, gpointer v_object);
gpointer matenu_value_get_parser (const GValue* value);
GType matenu_parser_get_type (void) G_GNUC_CONST;
void matenu_parser_parse (MatenuShell* shell, const char* description, GError** error);
gpointer matenu_serializer_ref (gpointer instance);
void matenu_serializer_unref (gpointer instance);
GParamSpec* matenu_param_spec_serializer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void matenu_value_set_serializer (GValue* value, gpointer v_object);
void matenu_value_take_serializer (GValue* value, gpointer v_object);
gpointer matenu_value_get_serializer (const GValue* value);
GType matenu_serializer_get_type (void) G_GNUC_CONST;
char* matenu_serializer_to_string (GObject* obj, gboolean pretty_print);
MatenuItem* matenu_shell_get_item (MatenuShell* self, gint position);
MatenuItem* matenu_shell_get_item_by_id (MatenuShell* self, const char* id);
gint matenu_shell_get_item_position (MatenuShell* self, MatenuItem* item);
MatenuItem* matenu_shell_get_item_by_path (MatenuShell* self, const char* path);
MatenuItem* matenu_shell_get_owner (MatenuShell* self);
gint matenu_shell_get_length (MatenuShell* self);
void matenu_shell_set_length (MatenuShell* self, gint value);
MatenuShell* matenu_shell_get_topmost_shell (MatenuShell* self);
gboolean matenu_item_is_child_of (MatenuItem* self, MatenuItem* possible_parent);
MatenuItemState matenu_item_state_from_string (const char* str);
const char* matenu_item_state_to_string (MatenuItemState state);
MatenuItemType matenu_item_type_from_string (const char* str);
gboolean matenu_item_type_has_label (MatenuItemType type);
const char* matenu_item_type_to_string (MatenuItemType type);
MatenuShell* matenu_item_get_shell (MatenuItem* self);
MatenuShell* matenu_item_get_sub_shell (MatenuItem* self);
gboolean matenu_item_get_has_sub_shell (MatenuItem* self);
void matenu_item_set_has_sub_shell (MatenuItem* self, gboolean value);
gboolean matenu_item_get_client_side_sub_shell (MatenuItem* self);
void matenu_item_set_client_side_sub_shell (MatenuItem* self, gboolean value);
MatenuShell* matenu_item_get_topmost_shell (MatenuItem* self);
gint matenu_item_get_item_position (MatenuItem* self);
const char* matenu_item_get_item_id (MatenuItem* self);
void matenu_item_set_item_id (MatenuItem* self, const char* value);
MatenuItemType matenu_item_get_item_type (MatenuItem* self);
void matenu_item_set_item_type (MatenuItem* self, MatenuItemType value);
gboolean matenu_item_get_item_use_underline (MatenuItem* self);
void matenu_item_set_item_use_underline (MatenuItem* self, gboolean value);
gboolean matenu_item_get_item_sensitive (MatenuItem* self);
void matenu_item_set_item_sensitive (MatenuItem* self, gboolean value);
gboolean matenu_item_get_item_visible (MatenuItem* self);
void matenu_item_set_item_visible (MatenuItem* self, gboolean value);
MatenuItemState matenu_item_get_item_state (MatenuItem* self);
void matenu_item_set_item_state (MatenuItem* self, MatenuItemState value);
const char* matenu_item_get_item_label (MatenuItem* self);
void matenu_item_set_item_label (MatenuItem* self, const char* value);
const char* matenu_item_get_item_icon (MatenuItem* self);
void matenu_item_set_item_icon (MatenuItem* self, const char* value);
const char* matenu_item_get_item_accel_text (MatenuItem* self);
void matenu_item_set_item_accel_text (MatenuItem* self, const char* value);
const char* matenu_item_get_item_font (MatenuItem* self);
void matenu_item_set_item_font (MatenuItem* self, const char* value);
char* matenu_item_get_item_path_name (MatenuItem* self);
char* matenu_item_get_item_path (MatenuItem* self);
GType matenu_menu_get_type (void) G_GNUC_CONST;
extern gboolean matenu_menu_default_use_rgba_colormap;
MatenuMenu* matenu_menu_new (void);
MatenuMenu* matenu_menu_construct (GType object_type);
gboolean matenu_menu_get_is_topmost (MatenuMenu* self);
void matenu_menu_set_is_topmost (MatenuMenu* self, gboolean value);
gboolean matenu_menu_get_use_rgba_colormap (MatenuMenu* self);
void matenu_menu_set_use_rgba_colormap (MatenuMenu* self, gboolean value);
gpointer matenu_background_ref (gpointer instance);
void matenu_background_unref (gpointer instance);
GParamSpec* matenu_param_spec_background (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void matenu_value_set_background (GValue* value, gpointer v_object);
void matenu_value_take_background (GValue* value, gpointer v_object);
gpointer matenu_value_get_background (const GValue* value);
GType matenu_background_get_type (void) G_GNUC_CONST;
MatenuBackground* matenu_background_clone (MatenuBackground* self);
MatenuBackground* matenu_background_new (void);
MatenuBackground* matenu_background_construct (GType object_type);
MatenuMenuBar* matenu_menu_bar_new (void);
MatenuMenuBar* matenu_menu_bar_construct (GType object_type);
GType matenu_menu_item_get_type (void) G_GNUC_CONST;
MatenuMenuItem* matenu_menu_bar_get (MatenuMenuBar* self, const char* path);
MatenuBackground* matenu_menu_bar_get_background (MatenuMenuBar* self);
void matenu_menu_bar_set_background (MatenuMenuBar* self, MatenuBackground* value);
MatenuGravity matenu_menu_bar_get_gravity (MatenuMenuBar* self);
void matenu_menu_bar_set_gravity (MatenuMenuBar* self, MatenuGravity value);
gboolean matenu_menu_bar_get_overflown (MatenuMenuBar* self);
MatenuMenuItem* matenu_menu_item_new (void);
MatenuMenuItem* matenu_menu_item_construct (GType object_type);
GtkShadowType matenu_menu_item_item_state_to_shadow_type (MatenuItemState state);
gint matenu_menu_item_get_max_width_chars (MatenuMenuItem* self);
void matenu_menu_item_set_max_width_chars (MatenuMenuItem* self, gint value);
MatenuGravity matenu_menu_item_get_gravity (MatenuMenuItem* self);
void matenu_menu_item_set_gravity (MatenuMenuItem* self, MatenuGravity value);
gboolean matenu_menu_item_get_show_underline (MatenuMenuItem* self);
void matenu_menu_item_set_show_underline (MatenuMenuItem* self, gboolean value);
gboolean matenu_menu_item_get_truncated (MatenuMenuItem* self);
void matenu_menu_item_set_truncated (MatenuMenuItem* self, gboolean value);
GtkImage* matenu_menu_item_get_image (MatenuMenuItem* self);
GType matenu_menu_bar_box_get_type (void) G_GNUC_CONST;
MatenuMenuBarBox* matenu_menu_bar_box_new (void);
MatenuMenuBarBox* matenu_menu_bar_box_construct (GType object_type);
gint* matenu_menu_bar_box_get_size_hints (MatenuMenuBarBox* self, int* result_length1);
GtkPackDirection matenu_menu_bar_box_get_pack_direction (MatenuMenuBarBox* self);
void matenu_menu_bar_box_set_pack_direction (MatenuMenuBarBox* self, GtkPackDirection value);
GtkPackDirection matenu_menu_bar_box_get_child_pack_direction (MatenuMenuBarBox* self);
void matenu_menu_bar_box_set_child_pack_direction (MatenuMenuBarBox* self, GtkPackDirection value);
MatenuGravity matenu_menu_bar_box_get_gravity (MatenuMenuBarBox* self);
void matenu_menu_bar_box_set_gravity (MatenuMenuBarBox* self, MatenuGravity value);
void matenu_menu_bar_box_set_background (MatenuMenuBarBox* self, MatenuBackground* value);
GType matenu_menu_label_get_type (void) G_GNUC_CONST;
MatenuMenuLabel* matenu_menu_label_new (void);
MatenuMenuLabel* matenu_menu_label_construct (GType object_type);
const char* matenu_menu_label_get_accel (MatenuMenuLabel* self);
void matenu_menu_label_set_accel (MatenuMenuLabel* self, const char* value);
gboolean matenu_menu_label_get_use_underline (MatenuMenuLabel* self);
void matenu_menu_label_set_use_underline (MatenuMenuLabel* self, gboolean value);
gint matenu_menu_label_get_max_width_chars (MatenuMenuLabel* self);
void matenu_menu_label_set_max_width_chars (MatenuMenuLabel* self, gint value);
const char* matenu_menu_label_get_label (MatenuMenuLabel* self);
void matenu_menu_label_set_label (MatenuMenuLabel* self, const char* value);
MatenuGravity matenu_menu_label_get_gravity (MatenuMenuLabel* self);
void matenu_menu_label_set_gravity (MatenuMenuLabel* self, MatenuGravity value);
GtkLabel* matenu_menu_label_get_label_widget (MatenuMenuLabel* self);
guint matenu_menu_label_get_mnemonic_keyval (MatenuMenuLabel* self);


G_END_DECLS

#endif
