/* globalmenuadapter.c generated by valac, the Vala compiler
 * generated from globalmenuadapter.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>


#define MATENU_TYPE_SHELL (matenu_shell_get_type ())
#define MATENU_SHELL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_SHELL, MatenuShell))
#define MATENU_IS_SHELL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_SHELL))
#define MATENU_SHELL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_SHELL, MatenuShellIface))

typedef struct _MatenuShell MatenuShell;
typedef struct _MatenuShellIface MatenuShellIface;

#define MATENU_TYPE_ITEM (matenu_item_get_type ())
#define MATENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_ITEM, MatenuItem))
#define MATENU_IS_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_ITEM))
#define MATENU_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), MATENU_TYPE_ITEM, MatenuItemIface))

typedef struct _MatenuItem MatenuItem;
typedef struct _MatenuItemIface MatenuItemIface;

#define MATENU_TYPE_ITEM_TYPE (matenu_item_type_get_type ())

#define MATENU_TYPE_ITEM_STATE (matenu_item_state_get_type ())

#define MATENU_TYPE_ADAPTER (matenu_adapter_get_type ())
#define MATENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_ADAPTER, MatenuAdapter))
#define MATENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_ADAPTER, MatenuAdapterClass))
#define MATENU_IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_ADAPTER))
#define MATENU_IS_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_ADAPTER))
#define MATENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_ADAPTER, MatenuAdapterClass))

typedef struct _MatenuAdapter MatenuAdapter;
typedef struct _MatenuAdapterClass MatenuAdapterClass;
typedef struct _MatenuAdapterPrivate MatenuAdapterPrivate;

#define MATENU_TYPE_GLOBAL_MENU_ADAPTER (matenu_global_menu_adapter_get_type ())
#define MATENU_GLOBAL_MENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_GLOBAL_MENU_ADAPTER, MatenuGlobalMenuAdapter))
#define MATENU_GLOBAL_MENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_GLOBAL_MENU_ADAPTER, MatenuGlobalMenuAdapterClass))
#define MATENU_IS_GLOBAL_MENU_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_GLOBAL_MENU_ADAPTER))
#define MATENU_IS_GLOBAL_MENU_ADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_GLOBAL_MENU_ADAPTER))
#define MATENU_GLOBAL_MENU_ADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_GLOBAL_MENU_ADAPTER, MatenuGlobalMenuAdapterClass))

typedef struct _MatenuGlobalMenuAdapter MatenuGlobalMenuAdapter;
typedef struct _MatenuGlobalMenuAdapterClass MatenuGlobalMenuAdapterClass;
typedef struct _MatenuGlobalMenuAdapterPrivate MatenuGlobalMenuAdapterPrivate;

#define MATENU_TYPE_MONITOR (matenu_monitor_get_type ())
#define MATENU_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MONITOR, MatenuMonitor))
#define MATENU_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MONITOR, MatenuMonitorClass))
#define MATENU_IS_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MONITOR))
#define MATENU_IS_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MONITOR))
#define MATENU_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MONITOR, MatenuMonitorClass))

typedef struct _MatenuMonitor MatenuMonitor;
typedef struct _MatenuMonitorClass MatenuMonitorClass;

#define MATENU_TYPE_MNEMONIC_KEYS (matenu_mnemonic_keys_get_type ())
#define MATENU_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_MNEMONIC_KEYS, MatenuMnemonicKeys))
#define MATENU_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_MNEMONIC_KEYS, MatenuMnemonicKeysClass))
#define MATENU_IS_MNEMONIC_KEYS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_MNEMONIC_KEYS))
#define MATENU_IS_MNEMONIC_KEYS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_MNEMONIC_KEYS))
#define MATENU_MNEMONIC_KEYS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_MNEMONIC_KEYS, MatenuMnemonicKeysClass))

typedef struct _MatenuMnemonicKeys MatenuMnemonicKeys;
typedef struct _MatenuMnemonicKeysClass MatenuMnemonicKeysClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _matenu_mnemonic_keys_unref0(var) ((var == NULL) ? NULL : (var = (matenu_mnemonic_keys_unref (var), NULL)))

#define MATENU_TYPE_WINDOW (matenu_window_get_type ())
#define MATENU_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATENU_TYPE_WINDOW, MatenuWindow))
#define MATENU_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATENU_TYPE_WINDOW, MatenuWindowClass))
#define MATENU_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATENU_TYPE_WINDOW))
#define MATENU_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATENU_TYPE_WINDOW))
#define MATENU_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATENU_TYPE_WINDOW, MatenuWindowClass))

typedef struct _MatenuWindow MatenuWindow;
typedef struct _MatenuWindowClass MatenuWindowClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_type_class_unref0(var) ((var == NULL) ? NULL : (var = (g_type_class_unref (var), NULL)))

typedef enum  {
	MATENU_ITEM_TYPE_NORMAL = 0,
	MATENU_ITEM_TYPE_CHECK = 1,
	MATENU_ITEM_TYPE_RADIO = 2,
	MATENU_ITEM_TYPE_IMAGE = 3,
	MATENU_ITEM_TYPE_SEPARATOR = 4,
	MATENU_ITEM_TYPE_ARROW = 5,
	MATENU_ITEM_TYPE_ICON = 6
} MatenuItemType;

typedef enum  {
	MATENU_ITEM_STATE_UNTOGGLED = 0,
	MATENU_ITEM_STATE_TOGGLED = 1,
	MATENU_ITEM_STATE_TRISTATE = 2
} MatenuItemState;

struct _MatenuItemIface {
	GTypeInterface parent_iface;
	MatenuShell* (*get_shell) (MatenuItem* self);
	MatenuShell* (*get_sub_shell) (MatenuItem* self);
	gboolean (*get_has_sub_shell) (MatenuItem* self);
	void (*set_has_sub_shell) (MatenuItem* self, gboolean value);
	gboolean (*get_client_side_sub_shell) (MatenuItem* self);
	void (*set_client_side_sub_shell) (MatenuItem* self, gboolean value);
	const char* (*get_item_id) (MatenuItem* self);
	void (*set_item_id) (MatenuItem* self, const char* value);
	MatenuItemType (*get_item_type) (MatenuItem* self);
	void (*set_item_type) (MatenuItem* self, MatenuItemType value);
	gboolean (*get_item_use_underline) (MatenuItem* self);
	void (*set_item_use_underline) (MatenuItem* self, gboolean value);
	gboolean (*get_item_sensitive) (MatenuItem* self);
	void (*set_item_sensitive) (MatenuItem* self, gboolean value);
	gboolean (*get_item_visible) (MatenuItem* self);
	void (*set_item_visible) (MatenuItem* self, gboolean value);
	MatenuItemState (*get_item_state) (MatenuItem* self);
	void (*set_item_state) (MatenuItem* self, MatenuItemState value);
	const char* (*get_item_label) (MatenuItem* self);
	void (*set_item_label) (MatenuItem* self, const char* value);
	const char* (*get_item_icon) (MatenuItem* self);
	void (*set_item_icon) (MatenuItem* self, const char* value);
	const char* (*get_item_accel_text) (MatenuItem* self);
	void (*set_item_accel_text) (MatenuItem* self, const char* value);
	const char* (*get_item_font) (MatenuItem* self);
	void (*set_item_font) (MatenuItem* self, const char* value);
};

struct _MatenuShellIface {
	GTypeInterface parent_iface;
	MatenuItem* (*get_item) (MatenuShell* self, gint position);
	MatenuItem* (*get_item_by_id) (MatenuShell* self, const char* id);
	gint (*get_item_position) (MatenuShell* self, MatenuItem* item);
	MatenuItem* (*get_owner) (MatenuShell* self);
	gint (*get_length) (MatenuShell* self);
	void (*set_length) (MatenuShell* self, gint value);
};

struct _MatenuAdapter {
	GObject parent_instance;
	MatenuAdapterPrivate * priv;
};

struct _MatenuAdapterClass {
	GObjectClass parent_class;
};

struct _MatenuGlobalMenuAdapter {
	MatenuAdapter parent_instance;
	MatenuGlobalMenuAdapterPrivate * priv;
};

struct _MatenuGlobalMenuAdapterClass {
	MatenuAdapterClass parent_class;
};

struct _MatenuGlobalMenuAdapterPrivate {
	MatenuMonitor* active_window_monitor;
	MatenuMnemonicKeys* mnemonic_keys;
};


static gpointer matenu_global_menu_adapter_parent_class = NULL;

GType matenu_item_type_get_type (void) G_GNUC_CONST;
GType matenu_item_state_get_type (void) G_GNUC_CONST;
GType matenu_item_get_type (void) G_GNUC_CONST;
GType matenu_shell_get_type (void) G_GNUC_CONST;
GType matenu_adapter_get_type (void) G_GNUC_CONST;
GType matenu_global_menu_adapter_get_type (void) G_GNUC_CONST;
GType matenu_monitor_get_type (void) G_GNUC_CONST;
gpointer matenu_mnemonic_keys_ref (gpointer instance);
void matenu_mnemonic_keys_unref (gpointer instance);
GParamSpec* matenu_param_spec_mnemonic_keys (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void matenu_value_set_mnemonic_keys (GValue* value, gpointer v_object);
void matenu_value_take_mnemonic_keys (GValue* value, gpointer v_object);
gpointer matenu_value_get_mnemonic_keys (const GValue* value);
GType matenu_mnemonic_keys_get_type (void) G_GNUC_CONST;
#define MATENU_GLOBAL_MENU_ADAPTER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), MATENU_TYPE_GLOBAL_MENU_ADAPTER, MatenuGlobalMenuAdapterPrivate))
enum  {
	MATENU_GLOBAL_MENU_ADAPTER_DUMMY_PROPERTY,
	MATENU_GLOBAL_MENU_ADAPTER_ACTIVE_WINDOW
};
void matenu_adapter_set_gtk_shell (MatenuAdapter* self, GtkMenuShell* value);
MatenuGlobalMenuAdapter* matenu_global_menu_adapter_new (GtkMenuShell* gtk_shell);
MatenuGlobalMenuAdapter* matenu_global_menu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell);
GType matenu_window_get_type (void) G_GNUC_CONST;
void matenu_mnemonic_keys_grab (MatenuMnemonicKeys* self, MatenuWindow* window);
MatenuWindow* matenu_global_menu_adapter_get_active_window (MatenuGlobalMenuAdapter* self);
static void matenu_global_menu_adapter_regrab_mnemonic_keys (MatenuGlobalMenuAdapter* self);
static void matenu_global_menu_adapter_emit_active_window_changed (MatenuGlobalMenuAdapter* self, MatenuWindow* prev_window);
void matenu_window_emit_menu_event (MatenuWindow* self, const char* path);
char* matenu_item_get_item_path (MatenuItem* self);
static void matenu_global_menu_adapter_item_activated (MatenuGlobalMenuAdapter* self, MatenuItem* item);
void matenu_window_emit_menu_select (MatenuWindow* self, const char* path, const char* pos);
static void matenu_global_menu_adapter_item_selected (MatenuGlobalMenuAdapter* self, MatenuItem* item);
void matenu_window_emit_menu_deselect (MatenuWindow* self, const char* path);
static void matenu_global_menu_adapter_item_deselected (MatenuGlobalMenuAdapter* self, MatenuItem* item);
GtkMenuShell* matenu_adapter_get_gtk_shell (MatenuAdapter* self);
static gboolean matenu_global_menu_adapter_sync_monitor_num (MatenuGlobalMenuAdapter* self);
static gboolean _matenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self);
static void _matenu_global_menu_adapter_hierarchy_changed (MatenuGlobalMenuAdapter* self, GtkWidget* old_toplevel);
void matenu_monitor_set_monitor_num (MatenuMonitor* self, gint value);
static void matenu_global_menu_adapter_chainup_key_changed (MatenuGlobalMenuAdapter* self, GtkWindow* window);
static void _matenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed (GtkPlug* _sender, gpointer self);
static void _matenu_global_menu_adapter_hierarchy_changed_chain_keys (MatenuGlobalMenuAdapter* self, GtkWidget* old_toplevel);
MatenuWindow* matenu_monitor_get_active_window (MatenuMonitor* self);
MatenuMnemonicKeys* matenu_mnemonic_keys_new (MatenuShell* shell);
MatenuMnemonicKeys* matenu_mnemonic_keys_construct (GType object_type, MatenuShell* shell);
MatenuMonitor* matenu_monitor_new (GdkScreen* screen);
MatenuMonitor* matenu_monitor_construct (GType object_type, GdkScreen* screen);
void matenu_monitor_set_managed_shell (MatenuMonitor* self, MatenuShell* value);
static void _matenu_global_menu_adapter_emit_active_window_changed_matenu_monitor_active_window_changed (MatenuMonitor* _sender, MatenuWindow* prev_window, gpointer self);
static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_changed (MatenuMonitor* _sender, MatenuWindow* prev_window, gpointer self);
static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_shell_rebuilt (MatenuMonitor* _sender, gpointer self);
static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_lost_focus (MatenuMonitor* _sender, gpointer self);
static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_received_focus (MatenuMonitor* _sender, gpointer self);
static void _matenu_global_menu_adapter_item_activated_matenu_shell_activate (MatenuGlobalMenuAdapter* _sender, MatenuItem* item, gpointer self);
static void _matenu_global_menu_adapter_item_selected_matenu_shell_select (MatenuGlobalMenuAdapter* _sender, MatenuItem* item, gpointer self);
static void _matenu_global_menu_adapter_item_deselected_matenu_shell_deselect (MatenuGlobalMenuAdapter* _sender, MatenuItem* item, gpointer self);
static void __matenu_global_menu_adapter_hierarchy_changed_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self);
static void __matenu_global_menu_adapter_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self);
static GObject * matenu_global_menu_adapter_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void matenu_global_menu_adapter_finalize (GObject* obj);
static void matenu_global_menu_adapter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);



MatenuGlobalMenuAdapter* matenu_global_menu_adapter_construct (GType object_type, GtkMenuShell* gtk_shell) {
	GParameter * __params;
	GParameter * __params_it;
	MatenuGlobalMenuAdapter * self;
	g_return_val_if_fail (gtk_shell != NULL, NULL);
	__params = g_new0 (GParameter, 1);
	__params_it = __params;
	__params_it->name = "gtk-shell";
	g_value_init (&__params_it->value, GTK_TYPE_MENU_SHELL);
	g_value_set_object (&__params_it->value, gtk_shell);
	__params_it++;
	self = g_object_newv (object_type, __params_it - __params, __params);
	while (__params_it > __params) {
		--__params_it;
		g_value_unset (&__params_it->value);
	}
	g_free (__params);
	return self;
}


MatenuGlobalMenuAdapter* matenu_global_menu_adapter_new (GtkMenuShell* gtk_shell) {
	return matenu_global_menu_adapter_construct (MATENU_TYPE_GLOBAL_MENU_ADAPTER, gtk_shell);
}


static void matenu_global_menu_adapter_regrab_mnemonic_keys (MatenuGlobalMenuAdapter* self) {
	g_return_if_fail (self != NULL);
	matenu_mnemonic_keys_grab (self->priv->mnemonic_keys, matenu_global_menu_adapter_get_active_window (self));
}


static void matenu_global_menu_adapter_emit_active_window_changed (MatenuGlobalMenuAdapter* self, MatenuWindow* prev_window) {
	g_return_if_fail (self != NULL);
	g_signal_emit_by_name (self, "active-window-changed", prev_window);
}


static void matenu_global_menu_adapter_item_activated (MatenuGlobalMenuAdapter* self, MatenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (matenu_global_menu_adapter_get_active_window (self) != NULL) {
		char* _tmp0_;
		matenu_window_emit_menu_event (matenu_global_menu_adapter_get_active_window (self), _tmp0_ = matenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static void matenu_global_menu_adapter_item_selected (MatenuGlobalMenuAdapter* self, MatenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (matenu_global_menu_adapter_get_active_window (self) != NULL) {
		char* _tmp0_;
		matenu_window_emit_menu_select (matenu_global_menu_adapter_get_active_window (self), _tmp0_ = matenu_item_get_item_path (item), NULL);
		_g_free0 (_tmp0_);
	}
}


static void matenu_global_menu_adapter_item_deselected (MatenuGlobalMenuAdapter* self, MatenuItem* item) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (item != NULL);
	if (matenu_global_menu_adapter_get_active_window (self) != NULL) {
		char* _tmp0_;
		matenu_window_emit_menu_deselect (matenu_global_menu_adapter_get_active_window (self), _tmp0_ = matenu_item_get_item_path (item));
		_g_free0 (_tmp0_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean _matenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event (GtkPlug* _sender, GdkEventConfigure* event, gpointer self) {
	gboolean result;
	result = matenu_global_menu_adapter_sync_monitor_num (self);
	return result;
}


static void _matenu_global_menu_adapter_hierarchy_changed (MatenuGlobalMenuAdapter* self, GtkWidget* old_toplevel) {
	GtkWidget* _tmp0_;
	GtkPlug* toplevel;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 ((_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self)), GTK_IS_PLUG (_tmp0_) ? ((GtkPlug*) _tmp0_) : NULL));
	if (toplevel != NULL) {
		g_signal_connect_object ((GtkWidget*) toplevel, "configure-event", (GCallback) _matenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event, self, 0);
	}
	if (old_toplevel != NULL) {
		guint _tmp1_;
		g_signal_parse_name ("configure-event", GTK_TYPE_WIDGET, &_tmp1_, NULL, FALSE);
		g_signal_handlers_disconnect_matched (old_toplevel, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp1_, 0, NULL, (GCallback) _matenu_global_menu_adapter_sync_monitor_num_gtk_widget_configure_event, self);
	}
	_g_object_unref0 (toplevel);
}


static gboolean matenu_global_menu_adapter_sync_monitor_num (MatenuGlobalMenuAdapter* self) {
	gboolean result = FALSE;
	GdkScreen* screen;
	g_return_val_if_fail (self != NULL, FALSE);
	screen = _g_object_ref0 (gtk_widget_get_screen ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self)));
	if (GTK_WIDGET_REALIZED ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self))) {
		matenu_monitor_set_monitor_num (self->priv->active_window_monitor, gdk_screen_get_monitor_at_window (screen, ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self))->window));
	} else {
		matenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
	}
	result = FALSE;
	_g_object_unref0 (screen);
	return result;
}


static void matenu_global_menu_adapter_chainup_key_changed (MatenuGlobalMenuAdapter* self, GtkWindow* window) {
	GType type;
	GtkWindowClass* window_class;
	g_return_if_fail (self != NULL);
	g_return_if_fail (window != NULL);
	type = GTK_TYPE_WINDOW;
	window_class = (GtkWindowClass*) g_type_class_ref (type);
	g_debug ("globalmenuadapter.vala:82: chainup to Gtk.Window keys changed");
	window_class->keys_changed (window);
	_g_type_class_unref0 (window_class);
}


static void _matenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed (GtkPlug* _sender, gpointer self) {
	matenu_global_menu_adapter_chainup_key_changed (self, _sender);
}


static void _matenu_global_menu_adapter_hierarchy_changed_chain_keys (MatenuGlobalMenuAdapter* self, GtkWidget* old_toplevel) {
	GtkWidget* _tmp0_;
	GtkPlug* toplevel;
	GtkWidget* _tmp1_;
	g_return_if_fail (self != NULL);
	toplevel = _g_object_ref0 ((_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self)), GTK_IS_PLUG (_tmp0_) ? ((GtkPlug*) _tmp0_) : NULL));
	if (toplevel != NULL) {
		g_signal_connect_object ((GtkWindow*) toplevel, "keys-changed", (GCallback) _matenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed, self, 0);
	}
	if ((_tmp1_ = old_toplevel, GTK_IS_PLUG (_tmp1_) ? ((GtkPlug*) _tmp1_) : NULL) != NULL) {
		guint _tmp3_;
		GtkWidget* _tmp2_;
		g_signal_parse_name ("keys-changed", GTK_TYPE_WINDOW, &_tmp3_, NULL, FALSE);
		g_signal_handlers_disconnect_matched ((GtkWindow*) (_tmp2_ = old_toplevel, GTK_IS_PLUG (_tmp2_) ? ((GtkPlug*) _tmp2_) : NULL), G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp3_, 0, NULL, (GCallback) _matenu_global_menu_adapter_chainup_key_changed_gtk_window_keys_changed, self);
	}
	_g_object_unref0 (toplevel);
}


MatenuWindow* matenu_global_menu_adapter_get_active_window (MatenuGlobalMenuAdapter* self) {
	MatenuWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = matenu_monitor_get_active_window (self->priv->active_window_monitor);
	return result;
}


static void _matenu_global_menu_adapter_emit_active_window_changed_matenu_monitor_active_window_changed (MatenuMonitor* _sender, MatenuWindow* prev_window, gpointer self) {
	matenu_global_menu_adapter_emit_active_window_changed (self, prev_window);
}


static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_changed (MatenuMonitor* _sender, MatenuWindow* prev_window, gpointer self) {
	matenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_shell_rebuilt (MatenuMonitor* _sender, gpointer self) {
	matenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_lost_focus (MatenuMonitor* _sender, gpointer self) {
	matenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_received_focus (MatenuMonitor* _sender, gpointer self) {
	matenu_global_menu_adapter_regrab_mnemonic_keys (self);
}


static void _matenu_global_menu_adapter_item_activated_matenu_shell_activate (MatenuGlobalMenuAdapter* _sender, MatenuItem* item, gpointer self) {
	matenu_global_menu_adapter_item_activated (self, item);
}


static void _matenu_global_menu_adapter_item_selected_matenu_shell_select (MatenuGlobalMenuAdapter* _sender, MatenuItem* item, gpointer self) {
	matenu_global_menu_adapter_item_selected (self, item);
}


static void _matenu_global_menu_adapter_item_deselected_matenu_shell_deselect (MatenuGlobalMenuAdapter* _sender, MatenuItem* item, gpointer self) {
	matenu_global_menu_adapter_item_deselected (self, item);
}


static void __matenu_global_menu_adapter_hierarchy_changed_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_matenu_global_menu_adapter_hierarchy_changed (self, previous_toplevel);
}


static void __matenu_global_menu_adapter_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed (GtkMenuShell* _sender, GtkWidget* previous_toplevel, gpointer self) {
	_matenu_global_menu_adapter_hierarchy_changed_chain_keys (self, previous_toplevel);
}


static GObject * matenu_global_menu_adapter_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MatenuGlobalMenuAdapter * self;
	parent_class = G_OBJECT_CLASS (matenu_global_menu_adapter_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = MATENU_GLOBAL_MENU_ADAPTER (obj);
	{
		MatenuMnemonicKeys* _tmp0_;
		MatenuMonitor* _tmp1_;
		self->priv->mnemonic_keys = (_tmp0_ = matenu_mnemonic_keys_new ((MatenuShell*) self), _matenu_mnemonic_keys_unref0 (self->priv->mnemonic_keys), _tmp0_);
		self->priv->active_window_monitor = (_tmp1_ = matenu_monitor_new (gtk_widget_get_screen ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self))), _g_object_unref0 (self->priv->active_window_monitor), _tmp1_);
		matenu_monitor_set_managed_shell (self->priv->active_window_monitor, (MatenuShell*) self);
		matenu_monitor_set_monitor_num (self->priv->active_window_monitor, -1);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-changed", (GCallback) _matenu_global_menu_adapter_emit_active_window_changed_matenu_monitor_active_window_changed, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-changed", (GCallback) _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_changed, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "shell-rebuilt", (GCallback) _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_shell_rebuilt, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-lost-focus", (GCallback) _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_lost_focus, self, 0);
		g_signal_connect_object (self->priv->active_window_monitor, "active-window-received-focus", (GCallback) _matenu_global_menu_adapter_regrab_mnemonic_keys_matenu_monitor_active_window_received_focus, self, 0);
		g_signal_connect_object ((MatenuShell*) self, "activate", (GCallback) _matenu_global_menu_adapter_item_activated_matenu_shell_activate, self, 0);
		g_signal_connect_object ((MatenuShell*) self, "select", (GCallback) _matenu_global_menu_adapter_item_selected_matenu_shell_select, self, 0);
		g_signal_connect_object ((MatenuShell*) self, "deselect", (GCallback) _matenu_global_menu_adapter_item_deselected_matenu_shell_deselect, self, 0);
		g_signal_connect_object ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self), "hierarchy-changed", (GCallback) __matenu_global_menu_adapter_hierarchy_changed_gtk_widget_hierarchy_changed, self, 0);
		g_signal_connect_object ((GtkWidget*) matenu_adapter_get_gtk_shell ((MatenuAdapter*) self), "hierarchy-changed", (GCallback) __matenu_global_menu_adapter_hierarchy_changed_chain_keys_gtk_widget_hierarchy_changed, self, 0);
	}
	return obj;
}


static void matenu_global_menu_adapter_class_init (MatenuGlobalMenuAdapterClass * klass) {
	matenu_global_menu_adapter_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MatenuGlobalMenuAdapterPrivate));
	G_OBJECT_CLASS (klass)->get_property = matenu_global_menu_adapter_get_property;
	G_OBJECT_CLASS (klass)->constructor = matenu_global_menu_adapter_constructor;
	G_OBJECT_CLASS (klass)->finalize = matenu_global_menu_adapter_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MATENU_GLOBAL_MENU_ADAPTER_ACTIVE_WINDOW, g_param_spec_object ("active-window", "active-window", "active-window", MATENU_TYPE_WINDOW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("active_window_changed", MATENU_TYPE_GLOBAL_MENU_ADAPTER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, MATENU_TYPE_WINDOW);
}


static void matenu_global_menu_adapter_instance_init (MatenuGlobalMenuAdapter * self) {
	self->priv = MATENU_GLOBAL_MENU_ADAPTER_GET_PRIVATE (self);
}


static void matenu_global_menu_adapter_finalize (GObject* obj) {
	MatenuGlobalMenuAdapter * self;
	self = MATENU_GLOBAL_MENU_ADAPTER (obj);
	_g_object_unref0 (self->priv->active_window_monitor);
	_matenu_mnemonic_keys_unref0 (self->priv->mnemonic_keys);
	G_OBJECT_CLASS (matenu_global_menu_adapter_parent_class)->finalize (obj);
}


GType matenu_global_menu_adapter_get_type (void) {
	static volatile gsize matenu_global_menu_adapter_type_id__volatile = 0;
	if (g_once_init_enter (&matenu_global_menu_adapter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MatenuGlobalMenuAdapterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) matenu_global_menu_adapter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MatenuGlobalMenuAdapter), 0, (GInstanceInitFunc) matenu_global_menu_adapter_instance_init, NULL };
		GType matenu_global_menu_adapter_type_id;
		matenu_global_menu_adapter_type_id = g_type_register_static (MATENU_TYPE_ADAPTER, "MatenuGlobalMenuAdapter", &g_define_type_info, 0);
		g_once_init_leave (&matenu_global_menu_adapter_type_id__volatile, matenu_global_menu_adapter_type_id);
	}
	return matenu_global_menu_adapter_type_id__volatile;
}


static void matenu_global_menu_adapter_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MatenuGlobalMenuAdapter * self;
	self = MATENU_GLOBAL_MENU_ADAPTER (object);
	switch (property_id) {
		case MATENU_GLOBAL_MENU_ADAPTER_ACTIVE_WINDOW:
		g_value_set_object (value, matenu_global_menu_adapter_get_active_window (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




